import type { CatalogResearch } from "./catalog-research";

const verifiedAt = "2026-09-11";

export const catalogResearchWazdan: Record<string, CatalogResearch> = {
  "wazdan-12-bells": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/12-bells", verifiedAt, evidence: "Official Wazdan game page lists two separate bonus modes, 12 Bells Bonus Game and Hold the Jackpot, using 12 reels and Cash Infinity." },
  "wazdan-15-coins-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/15-coins-grand-gold-edition", verifiedAt, evidence: "Fifteen independent reels; Cash Infinity, Hold the Jackpot, Chance Level up to 10x and Grand Jackpot 2000x." },
  "wazdan-15-coins-grand-platinum-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/15-coins-grand-platinum-edition", verifiedAt, evidence: "Fifteen reels and new Cash Out in base game alongside Cash Infinity and Hold the Jackpot with 2500x Grand." },
  "wazdan-16-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/16-coins", verifiedAt, evidence: "Sixteen individual reels in a 4x4 grid with Cash Infinity and Hold the Jackpot, maximum 1000x." },
  "wazdan-16-coins-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/16-coins-grand-gold-edition", verifiedAt, evidence: "Sixteen reels, enhanced Hold the Jackpot to 2000x, Cash Infinity and Chance Level." },
  "wazdan-16-coins-grand-platinum-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/16-coins-grand-platinum-edition", verifiedAt, evidence: "Sixteen-reel Platinum edition adds Cash Out and Hold the Jackpot to 2500x." },
  "wazdan-16-coins-x5000": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/16-coins-x5000", verifiedAt, evidence: "Official game specifies three resetting respins, Cash Out labels with countdown and Grand Jackpot 5000x." },
  "wazdan-20-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/20-coins", verifiedAt, evidence: "Twenty independent reels, Sticky to Infinity, Cash Infinity, Chance Level x2/x4/x6 and Hold the Jackpot." },
  "wazdan-20-coins-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/20-coins-grand-gold-edition", verifiedAt, evidence: "Twenty reels with higher 2000x Grand Jackpot, Cash Infinity, Sticky to Infinity and Hold the Jackpot." },
  "wazdan-24-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/24-coins", verifiedAt, evidence: "Twenty-four reels; Moving Cash Out debuted in this version alongside Cluster Collector and Hold the Jackpot." },
  "wazdan-25-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/25-coins", verifiedAt, evidence: "Twenty-five positions with Cluster Collector collecting nearby cash values, Sticky to Infinity and Hold the Jackpot." },
  "wazdan-25-coins-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/25-coins-grand-gold-edition", verifiedAt, evidence: "Grand Gold adds Collect to Infinity as modifier preserving Cluster Collector until bonus ends; Grand 2500x." },
  "wazdan-25-coins-x3000": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/25-coins-x3000", verifiedAt, evidence: "October 1, 2026 first-party Wazdan news release confirms Hold the Jackpot three resetting respins, full 25-position grid awarding 3000x, sticky Cash Infinity and five-spin Cluster Collector." },
  "wazdan-30-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/30-coins", verifiedAt, evidence: "Thirty reels, Cluster Collector, Cash Infinity and Sticky to Infinity with 1500x Grand Jackpot." },
  "wazdan-30-coins-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/30-coins-grand-gold-edition", verifiedAt, evidence: "Thirty reels with upgraded Collector and Collect to Infinity, Chance Level choices and 2500x Grand." },
  "wazdan-36-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/36-coins", verifiedAt, evidence: "Six-by-six, thirty-six-reel grid with Cluster Collector and Sticky to Infinity, 2000x maximum." },
  "wazdan-36-coins-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/36-coins-grand-gold-edition", verifiedAt, evidence: "Thirty-six reels with Collect to Infinity modifying Cluster Collector and Chance Level x2/x5/x10." },
  "wazdan-9-balls": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-balls", verifiedAt, evidence: "Nine-reel football slot with Penalty Kick countdown Cash Out, xG Chance Level and Hold the Jackpot." },
  "wazdan-9-bells": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-bells", verifiedAt, evidence: "Nine reels with Bonus Matrix, Bell Symbols activating Hold the Jackpot, Cash Out and Chance Level up to 6x." },
  "wazdan-9-burning-dragons": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-burning-dragons", verifiedAt, evidence: "Nine independent reels; Wild and direct Buy Feature for Hold the Jackpot; 2187x stated maximum." },
  "wazdan-back-to-the-70s": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/back-to-the-70s",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 20 lines.",
  },
  "wazdan-bars7s": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/bars7s",
    verifiedAt,
    evidence: "Official Game Info lists 3 reels and 8 lines and the page explicitly describes the winning payline.",
  },
  "wazdan-beach-party": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/beach-party",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 20 lines.",
  },
  "wazdan-beach-party-hot": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/beach-party-hot",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 20 lines.",
  },
  "wazdan-bell-wizard": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/bell-wizard",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 9 lines; Wazdan also describes it as a 5-reel, 9-payline video slot.",
  },
  "wazdan-black-hawk": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/black-hawk",
    verifiedAt,
    evidence: "Official Game Info lists 4 reels and 54 lines.",
  },
  "wazdan-black-hawk-deluxe": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/black-hawk-deluxe",
    verifiedAt,
    evidence: "Official page describes Black Hawk Deluxe as a 4-reel, 54-payline slot and Game Info lists 54 lines.",
  },
  "wazdan-black-horse": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/black-horse",
    verifiedAt,
    evidence: "Official page describes a classic 3-reel, 5-payline slot and Game Info lists 5 lines.",
  },
  "wazdan-black-horse-deluxe": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/black-horse-deluxe",
    verifiedAt,
    evidence: "Official Game Info lists 6 reels and 20 lines and the description explicitly refers to 20 paylines.",
  },
  "wazdan-book-of-faith": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/book-of-faith",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 10 lines.",
  },
  "wazdan-burning-reels": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/burning-reels",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 20 lines; the detailed description also states 20 paylines.",
  },
  "wazdan-burning-stars": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/burning-stars",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 20 lines.",
  },
  "wazdan-captain-shark": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/captain-shark",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 20 lines.",
  },
  "wazdan-colin-the-cat": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/colin-the-cat",
    verifiedAt,
    evidence: "Official Game Info lists 4 reels and 10 lines; the detailed description also states 10 paylines.",
  },
  "wazdan-corrida-romance": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/corrida-romance",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 20 lines.",
  },
  "wazdan-corrida-romance-deluxe": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/corrida-romance-deluxe",
    verifiedAt,
    evidence: "Official page describes a 5-reel, 20-payline slot and Game Info lists 20 lines.",
  },
  "wazdan-crazy-cars": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/crazy-cars",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 5 lines.",
  },
  "wazdan-criss-cross-81": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/criss-cross-81",
    verifiedAt,
    evidence: "Official Game Info lists 4 reels and 81 lines.",
  },
  "wazdan-cube-mania-deluxe": {
    mechanics: ["Линии", "Каскады"],
    source: "https://wazdan.com/games/cube-mania-deluxe",
    verifiedAt,
    evidence: "Official Game Info lists 4 reels and 9 lines, while the official features explicitly list Cascading Reels and describe winning symbols disappearing before new symbols fall into place.",
  },
  "wazdan-9-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-coins", verifiedAt, evidence: "Official page confirms nine independent reels with no base-game payouts, Cash Infinity and Hold the Jackpot with a 500x Grand Jackpot." },
  "wazdan-9-coins-1000-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-coins-1000-edition", verifiedAt, evidence: "Official page confirms nine independent reels without base-game pays, Cash Infinity and Hold the Jackpot, and a 1000x Grand Jackpot." },
  "wazdan-9-coins-extremely-light": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-coins-extremely-light", verifiedAt, evidence: "Official page confirms an optimized lightweight nine-reel version with Cash Infinity and Hold the Jackpot and a 500x Grand Jackpot." },
  "wazdan-9-coins-grand-diamond-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-coins-grand-diamond-edition", verifiedAt, evidence: "Official page confirms nine reels with Cash Infinity, Cash Out, Chance Level and a 5000x Grand Jackpot." },
  "wazdan-9-coins-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-coins-grand-gold-edition", verifiedAt, evidence: "Official page confirms nine reels with Cash Infinity and Hold the Jackpot featuring a 1500x Grand Jackpot." },
  "wazdan-9-coins-grand-platinum-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-coins-grand-platinum-edition", verifiedAt, evidence: "Official page confirms nine reels with Chance Level, Cash Out, Cash Infinity and a 2500x Grand Jackpot." },
  "wazdan-9-lions": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-lions", verifiedAt, evidence: "Official page identifies nine independent reels and separate Lions Bonus and Dragons Bonus, as well as Block Symbols Mode." },
  "wazdan-9-lions-hold-the-jackpot": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-lions-hold-the-jackpot", verifiedAt, evidence: "Official page confirms Cash Infinity, Bonus Matrix, Hold the Jackpot and a separate 9 Lions Bonus with One Click 2 Grand." },
  "wazdan-beauty-fruity": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/beauty-fruity", verifiedAt, evidence: "Official page identifies nine independent positions with wins from four identical symbols anywhere, Love Spins, nine Free Spins with x3 and Block Symbols." },
  "wazdan-bells-of-fortune": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/bells-of-fortune", verifiedAt, evidence: "Official page confirms 16 independent reels, Hold the Jackpot after four central bonus symbols, a separate Bells of Fortune Bonus Game, Cash Infinity and Chance Level." },

  "wazdan-black-horse-cash-out-edition": { mechanics: ["Линии","Сбор символов"], source: "https://wazdan.com/games/black-horse-cash-out-edition", verifiedAt, evidence: "Official page confirms 5 reels, 20 lines, Cash Out, Sticky Cash Out, Jackpot Coins and Chance Level." },
  "wazdan-bumba-meu-boi-coin": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/bumba-meu-boi-coin", verifiedAt, evidence: "Official page confirms one main reel and three upper mini reels, Magic Coin, back matrix, Extra Life and Boi Da Fortuna Bonus." },
  "wazdan-burning-stars-3": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/burning-stars-3", verifiedAt, evidence: "Official page confirms nine independent reels in a 3x3 matrix and Hold the Jackpot triggered by three Bonus stars, with three resetting respins." },
  "wazdan-burning-sun": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/burning-sun", verifiedAt, evidence: "Official page confirms sixteen-reel 4x4 grid, Sticky to Infinity and Hold the Jackpot triggered by six Bonus symbols." },
  "wazdan-burning-sun-extremely-light": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/burning-sun-extremely-light", verifiedAt, evidence: "Official release confirms lighter graphics with the original Burning Sun 4x4 and its Sticky to Infinity and Hold the Jackpot features preserved." },
  "wazdan-butterfly-lovers": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/butterfly-lovers", verifiedAt, evidence: "Official page confirms 16 separate reels and wins from eight identical symbols; Liang Shanbo Bonus Spins, Magic Sack and Zhu Yingtai Free Spins are distinct." },
  "wazdan-cash-grotto": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/cash-grotto", verifiedAt, evidence: "Official page confirms 24 reels, Hold the Jackpot triggered by four central Bonus symbols, Moving Cash Out, Cash Infinity and Sticky to Infinity." },
  "wazdan-demon-jack-27": { mechanics: ["Линии"], source: "https://wazdan.com/games/demon-jack-27", verifiedAt: "2026-10-08", evidence: "Official Game Info gives 3 reels/27 lines, RTP 96.09%, 1104x max, high volatility, 2016-02-11; features Wild and x3 Wall Multiplier." },
  "wazdan-dino-reels-81": { mechanics: ["Линии"], source: "https://wazdan.com/games/dino-reels-81", verifiedAt: "2026-10-08", evidence: "Official Game Info lists 4 reels, 7 lines, 96.44%, 691x, medium-high, 2016-12-01; long official description calls it 81-payline and Wild feature increases to 81 lines. Conflict explicitly preserved." },
  "wazdan-double-tigers": { mechanics: ["Линии"], source: "https://wazdan.com/games/double-tigers", verifiedAt: "2026-10-08", evidence: "Official Game Info says 3 reels/8 lines, 96.43%, 40x, low-medium, 2018-08-05. Long first-party text says 5 reels/8 paylines: unresolved internal reel-count conflict recorded." },
  "wazdan-draculas-castle": { mechanics: ["Линии"], source: "https://wazdan.com/games/draculas-castle", verifiedAt: "2026-10-08", evidence: "Official Game Info: 5 reels/5 lines, 96.56 RTP, 1000x, high, 2017-12-27; article confirms expanding Dracula Wild, x3/x4/x5 wall and goblet gamble." },
  "wazdan-dragons-lucky-8": { mechanics: ["Линии"], source: "https://wazdan.com/games/dragons-lucky-8", verifiedAt: "2026-10-08", evidence: "Official Game Info lists 6 reels/20 lines, 96.26%, 1150x, low-medium, 2019-08-20; long first-party description confirms sticky variable x1/x2/x4/x8 multiplier, free spins and Wild." },
  "wazdan-dwarfs-fortune": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/dwarfs-fortune", verifiedAt: "2026-10-08", evidence: "Official Game Info: 5 reels/0 lines, RTP 96.16%, max 2500x, high, 2022-03-09. Full Wazdan description: six Bonus trigger Hold the Jackpot, twenty positions grant Grand, Increasing Value Sticky Bonus up to nine respins." },
  "wazdan-easter-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/easter-coins", verifiedAt: "2026-10-08", evidence: "Wazdan game page explicitly lists 25 reels / 0 ways, RTP 96.17%, max 2000x, high volatility, 2026-03-20, and Hold the Jackpot, Cash Infinity, Sticky to Infinity, Cluster Collector." },
  "wazdan-eggs-of-fortune": { mechanics: ["Линии","Сбор символов"], source: "https://wazdan.com/games/eggs-of-fortune", verifiedAt: "2026-10-08", evidence: "Official page lists 5 reels/5 lines, 96.12%, max 5000x, extreme, 2025-08-07. Intro confirms two base-game Cash Out features, Countdown Boosters and Collector in Free Spins and Chance Level x2/x5/x10." },
  "wazdan-fenix-play": { mechanics: ["Линии"], source: "https://wazdan.com/games/fenix-play", verifiedAt: "2026-10-08", evidence: "Official game page is titled Fenix Play; catalog name Fenix. Game Info: 3 reels/5 lines, 96.44 RTP, max 75x, medium, 2014-09-08. Lists Extra Drawings and Gamble Feature." },
  "wazdan-fenix-play-27": { mechanics: ["Линии"], source: "https://wazdan.com/games/fenix-play-27", verifiedAt: "2026-10-08", evidence: "Official Game Info lists 3 reels/27 lines, RTP 96.25%, max 748x, high; no release-date field. Wazdan describes phoenix Wild and x3 wall." },
  "wazdan-fenix-play-27-deluxe": { mechanics: ["Линии"], source: "https://wazdan.com/games/fenix-play-27-deluxe", verifiedAt: "2026-10-08", evidence: "Official Game Info 3/27, 96.25%, 748x, high, 2017-09-15; long official description confirms cross paylines, Wild phoenix, x3 Wall and egg gamble." },
  "wazdan-fenix-play-deluxe": { mechanics: ["Линии"], source: "https://wazdan.com/games/fenix-play-deluxe", verifiedAt: "2026-10-08", evidence: "Official Game Info 3 reels/5 lines, 96.44%, 75x, medium, 2017-09-15. Wazdan details refreshed design, 7 possible doubles in Gamble and Volatility Levels." },
  "wazdan-fire-bird": { mechanics: ["Линии"], source: "https://wazdan.com/games/fire-bird", verifiedAt: "2026-10-08", evidence: "Official Wazdan Game Info: 3 reels, 5 lines, RTP 96.05%, 72x, standard; official list contains Bonus Symbol, page copy describes Gamble. Release date not listed." },
  "wazdan-fishermans-luck": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/fishermans-luck", verifiedAt: "2026-10-08", evidence: "Official Game Info: 10 reels/0 lines, 96.13%, 2500x, medium, 2026-03-05; source explicitly describes Gainer up to ten spins, Free Spins Gain to Infinity, top Cash Out and Chance Level x2/5/10." },
  "wazdan-football-mania": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/football-mania", verifiedAt: "2026-10-08", evidence: "Official Game Info lists 9 reels/0 lines, RTP 96.59%, max 1000x, high; feature list includes Block Symbols Mode, Football Bonus and Football Lottery Bonus. Release date omitted." },
  "wazdan-football-mania-deluxe": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/football-mania-deluxe", verifiedAt: "2026-10-08", evidence: "Official Game Info 9 reels/0 lines, 96.59%, max 1000x, high, 2018-05-30. Detailed first-party copy describes revamped version, Football Bonus and Football Lottery selection up to 1000x." },
  "wazdan-fortune-reels": { mechanics: ["Способы","Каскады","Сбор символов"], source: "https://wazdan.com/games/fortune-reels", verifiedAt: "2026-10-08", evidence: "Official Game Info 6 reels / 6 Ways to Win, RTP 96.12%, 2100x, high, 2021-07-27; game text explicitly says 46,656 ways and Cascading Reels, expanding Wild and Sack up to five bonus values. Different representations preserved." },
  "wazdan-fruit-fiesta": { mechanics: ["Линии"], source: "https://wazdan.com/games/fruit-fiesta", verifiedAt: "2026-10-08", evidence: "Official Wazdan Game Info: 5 reels/20 lines, 96.32%, 730x, high, 2017-12-01. Official description: chilli Wild, sheriff-star Scatter pays for 3+ anywhere and piñata Gamble." },
  "wazdan-fruit-mania": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/fruit-mania", verifiedAt: "2026-10-08", evidence: "Official Game Info: 9 reels/0 lines, 96.59%, 1000x, high, 2014-09-08; official page details Diamond Matrix full -> 9 spins with locked diamonds, Block Symbols and three central Lotto symbols." },
  "wazdan-fruit-mania-deluxe": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/fruit-mania-deluxe", verifiedAt: "2026-10-09", evidence: "Official 9 reels/0 lines, 96.59% RTP, max 1000x, 2018-06-20; official detailed description confirms 3x3 horizontal/vertical pays, diamond matrix for 9 bonus spins, Lotto gift boxes and block symbols." },
  "wazdan-fruits-go-bananas": { mechanics: ["Линии"], source: "https://wazdan.com/games/fruits-go-bananas", verifiedAt: "2026-10-09", evidence: "Official Game Info: 5 reels/5 lines, 96.34%, 850x, medium, 2018-09-11; pineapple Wild x2, Random Wilds, banana Scatter 3/4/5 => 10/20/30 Free Spins." },
  "wazdan-gem-splitter": { mechanics: ["Способы"], source: "https://wazdan.com/games/gem-splitter", verifiedAt: "2026-10-09", evidence: "Official Game Info: 5 reels/243 ways, RTP 96.27%, max 9000x, high, 2021-01-19; 5 variants of Symbol Splitter, Scatter, Wild, Free Spins and Buy Feature." },
  "wazdan-golden-sphinx": { mechanics: ["Линии"], source: "https://wazdan.com/games/golden-sphinx", verifiedAt: "2026-10-09", evidence: "Official Game Info: 5 reels/20 lines, RTP 96.48%, max 4650x, high, 2014-08-09; x2 Wild sphinx and 15 Free Spins with x3 multiplier." },
  "wazdan-good-luck-40": { mechanics: ["Линии"], source: "https://wazdan.com/games/good-luck-40", verifiedAt: "2026-10-09", evidence: "Official Game Info: 5 reels/40 lines, RTP 96.62%, max 2000x, low, 2014-08-09; lists Wild, Scatter and Free Spins without a specific spin count." },
  "wazdan-great-book-of-magic": { mechanics: ["Линии"], source: "https://wazdan.com/games/great-book-of-magic", verifiedAt: "2026-10-09", evidence: "Official Game Info 5 reels/20 lines, RTP 96.47%, 5150x max, high, 2018-05-30. Free Spins with Expanding Bonus Symbol and Scatter are official game features." },
  "wazdan-great-book-of-magic-deluxe": { mechanics: ["Линии"], source: "https://wazdan.com/games/great-book-of-magic-deluxe", verifiedAt: "2026-10-09", evidence: "Official Deluxe page 5 reels/20 lines, 96.47%, 5150x, high, 2018-05-30; detailed official copy confirms 3 books => 10 Free Spins, expanding bonus symbol, scatters act as Wild in free spins." },
  "wazdan-haunted-coins-x1000": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/haunted-coins-x1000", verifiedAt: "2026-10-09", evidence: "Official page: 16 reels/0 ways, 96.18%, max 1000x, high, 2025-10-21, Hold the Jackpot, Cash Infinity and Chance Level x2/x4/x6." },
  "wazdan-haunted-hospital": { mechanics: ["Линии"], source: "https://wazdan.com/games/haunted-hospital", verifiedAt: "2026-10-09", evidence: "Official Game Info 3 reels/27 lines, RTP 96.49%, max 820x, high, 2017-05-02; separate listed features: Wild, Scatter, Free Spins and Mystery Bonus." },
  "wazdan-highschool-manga": { mechanics: ["Линии"], source: "https://wazdan.com/games/highschool-manga", verifiedAt: "2026-10-09", evidence: "Official Game Info 3 reels/5 lines, 96.41%, max 320x, 2016-01-12, adjustable Low/Standard/High; x2 Wall Multiplier triggered by 3x3 wall of four applicable symbols." },
  "wazdan-highway-to-hell": { mechanics: ["Линии"], source: "https://wazdan.com/games/highway-to-hell", verifiedAt: "2026-10-09", evidence: "Official 5 reels/5 lines, RTP 96.18%, max 2500x, low-medium, official expansion-truck Wild and x3/x4/x5 Wall Multiplier." },
  "wazdan-highway-to-hell-deluxe": { mechanics: ["Линии"], source: "https://wazdan.com/games/highway-to-hell-deluxe", verifiedAt: "2026-10-09", evidence: "Official Deluxe Game Info 5 reels/5 lines, 96.56%, max 1000x, high, 2018-07-13; 9/10/J/Q x3/x4/x5 wall, expanding lorry Wild." },
  "wazdan-hot-777-deluxe": { mechanics: ["Линии"], source: "https://wazdan.com/games/hot-777-deluxe", verifiedAt: "2026-10-09", evidence: "Official Deluxe 3 reels/5 lines, 96.47%, 200x, medium, 2018-10-10. Detail text: each Hot 7 grants bullet; ten bullets plus Hot 7 trigger 10 Hot Spins with sticky Hot 7." },
  "wazdan-hot-party-deluxe": { mechanics: ["Линии"], source: "https://wazdan.com/games/hot-party-deluxe", verifiedAt: "2026-10-09", evidence: "Official Deluxe 5 reels/20 lines, 96.42%, max 305x, low-medium, 2018-06-27. Three or more beach-ball scatters pay anywhere; Gamble hides drink behind two leaves." },

};

export function getCatalogResearchWazdan(slug: string) {
  return catalogResearchWazdan[slug];
}
