import type { CatalogResearch } from "./catalog-research";

const verifiedAt = "2026-09-11";

export const catalogResearchWazdan: Record<string, CatalogResearch> = {
  "wazdan-12-bells": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/12-bells", verifiedAt, evidence: "Official Wazdan game page lists two separate bonus modes, 12 Bells Bonus Game and Hold the Jackpot, using 12 reels and Cash Infinity." },
  "wazdan-15-coins-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/15-coins-grand-gold-edition", verifiedAt, evidence: "Fifteen independent reels; Cash Infinity, Hold the Jackpot, Chance Level up to 10x and Grand Jackpot 2000x." },
  "wazdan-15-coins-grand-platinum-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/15-coins-grand-platinum-edition", verifiedAt, evidence: "Fifteen reels and new Cash Out in base game alongside Cash Infinity and Hold the Jackpot with 2500x Grand." },
  "wazdan-16-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/16-coins", verifiedAt, evidence: "Sixteen individual reels in a 4x4 grid with Cash Infinity and Hold the Jackpot, maximum 1000x." },
  "wazdan-16-coins-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/16-coins-grand-gold-edition", verifiedAt, evidence: "Sixteen reels, enhanced Hold the Jackpot to 2000x, Cash Infinity and Chance Level." },
  "wazdan-16-coins-grand-platinum-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/16-coins-grand-platinum-edition", verifiedAt, evidence: "Sixteen-reel Platinum edition adds Cash Out and Hold the Jackpot to 2500x." },
  "wazdan-16-coins-x5000": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/16-coins-x5000", verifiedAt, evidence: "Official game specifies three resetting respins, Cash Out labels with countdown and Grand Jackpot 5000x." },
  "wazdan-20-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/20-coins", verifiedAt, evidence: "Twenty independent reels, Sticky to Infinity, Cash Infinity, Chance Level x2/x4/x6 and Hold the Jackpot." },
  "wazdan-20-coins-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/20-coins-grand-gold-edition", verifiedAt, evidence: "Twenty reels with higher 2000x Grand Jackpot, Cash Infinity, Sticky to Infinity and Hold the Jackpot." },
  "wazdan-24-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/24-coins", verifiedAt, evidence: "Twenty-four reels; Moving Cash Out debuted in this version alongside Cluster Collector and Hold the Jackpot." },
  "wazdan-25-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/25-coins", verifiedAt, evidence: "Twenty-five positions with Cluster Collector collecting nearby cash values, Sticky to Infinity and Hold the Jackpot." },
  "wazdan-25-coins-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/25-coins-grand-gold-edition", verifiedAt, evidence: "Grand Gold adds Collect to Infinity as modifier preserving Cluster Collector until bonus ends; Grand 2500x." },
  "wazdan-25-coins-x3000": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/25-coins-x3000", verifiedAt, evidence: "October 1, 2026 first-party Wazdan news release confirms Hold the Jackpot three resetting respins, full 25-position grid awarding 3000x, sticky Cash Infinity and five-spin Cluster Collector." },
  "wazdan-30-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/30-coins", verifiedAt, evidence: "Thirty reels, Cluster Collector, Cash Infinity and Sticky to Infinity with 1500x Grand Jackpot." },
  "wazdan-30-coins-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/30-coins-grand-gold-edition", verifiedAt, evidence: "Thirty reels with upgraded Collector and Collect to Infinity, Chance Level choices and 2500x Grand." },
  "wazdan-36-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/36-coins", verifiedAt, evidence: "Six-by-six, thirty-six-reel grid with Cluster Collector and Sticky to Infinity, 2000x maximum." },
  "wazdan-36-coins-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/36-coins-grand-gold-edition", verifiedAt, evidence: "Thirty-six reels with Collect to Infinity modifying Cluster Collector and Chance Level x2/x5/x10." },
  "wazdan-9-balls": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-balls", verifiedAt, evidence: "Nine-reel football slot with Penalty Kick countdown Cash Out, xG Chance Level and Hold the Jackpot." },
  "wazdan-9-bells": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-bells", verifiedAt, evidence: "Nine reels with Bonus Matrix, Bell Symbols activating Hold the Jackpot, Cash Out and Chance Level up to 6x." },
  "wazdan-9-burning-dragons": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-burning-dragons", verifiedAt, evidence: "Nine independent reels; Wild and direct Buy Feature for Hold the Jackpot; 2187x stated maximum." },
  "wazdan-back-to-the-70s": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/back-to-the-70s",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 20 lines.",
  },
  "wazdan-bars7s": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/bars7s",
    verifiedAt,
    evidence: "Official Game Info lists 3 reels and 8 lines and the page explicitly describes the winning payline.",
  },
  "wazdan-beach-party": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/beach-party",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 20 lines.",
  },
  "wazdan-beach-party-hot": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/beach-party-hot",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 20 lines.",
  },
  "wazdan-bell-wizard": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/bell-wizard",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 9 lines; Wazdan also describes it as a 5-reel, 9-payline video slot.",
  },
  "wazdan-black-hawk": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/black-hawk",
    verifiedAt,
    evidence: "Official Game Info lists 4 reels and 54 lines.",
  },
  "wazdan-black-hawk-deluxe": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/black-hawk-deluxe",
    verifiedAt,
    evidence: "Official page describes Black Hawk Deluxe as a 4-reel, 54-payline slot and Game Info lists 54 lines.",
  },
  "wazdan-black-horse": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/black-horse",
    verifiedAt,
    evidence: "Official page describes a classic 3-reel, 5-payline slot and Game Info lists 5 lines.",
  },
  "wazdan-black-horse-deluxe": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/black-horse-deluxe",
    verifiedAt,
    evidence: "Official Game Info lists 6 reels and 20 lines and the description explicitly refers to 20 paylines.",
  },
  "wazdan-book-of-faith": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/book-of-faith",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 10 lines.",
  },
  "wazdan-burning-reels": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/burning-reels",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 20 lines; the detailed description also states 20 paylines.",
  },
  "wazdan-burning-stars": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/burning-stars",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 20 lines.",
  },
  "wazdan-captain-shark": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/captain-shark",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 20 lines.",
  },
  "wazdan-colin-the-cat": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/colin-the-cat",
    verifiedAt,
    evidence: "Official Game Info lists 4 reels and 10 lines; the detailed description also states 10 paylines.",
  },
  "wazdan-corrida-romance": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/corrida-romance",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 20 lines.",
  },
  "wazdan-corrida-romance-deluxe": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/corrida-romance-deluxe",
    verifiedAt,
    evidence: "Official page describes a 5-reel, 20-payline slot and Game Info lists 20 lines.",
  },
  "wazdan-crazy-cars": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/crazy-cars",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 5 lines.",
  },
  "wazdan-criss-cross-81": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/criss-cross-81",
    verifiedAt,
    evidence: "Official Game Info lists 4 reels and 81 lines.",
  },
  "wazdan-cube-mania-deluxe": {
    mechanics: ["Линии", "Каскады"],
    source: "https://wazdan.com/games/cube-mania-deluxe",
    verifiedAt,
    evidence: "Official Game Info lists 4 reels and 9 lines, while the official features explicitly list Cascading Reels and describe winning symbols disappearing before new symbols fall into place.",
  },
  "wazdan-9-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-coins", verifiedAt, evidence: "Official page confirms nine independent reels with no base-game payouts, Cash Infinity and Hold the Jackpot with a 500x Grand Jackpot." },
  "wazdan-9-coins-1000-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-coins-1000-edition", verifiedAt, evidence: "Official page confirms nine independent reels without base-game pays, Cash Infinity and Hold the Jackpot, and a 1000x Grand Jackpot." },
  "wazdan-9-coins-extremely-light": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-coins-extremely-light", verifiedAt, evidence: "Official page confirms an optimized lightweight nine-reel version with Cash Infinity and Hold the Jackpot and a 500x Grand Jackpot." },
  "wazdan-9-coins-grand-diamond-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-coins-grand-diamond-edition", verifiedAt, evidence: "Official page confirms nine reels with Cash Infinity, Cash Out, Chance Level and a 5000x Grand Jackpot." },
  "wazdan-9-coins-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-coins-grand-gold-edition", verifiedAt, evidence: "Official page confirms nine reels with Cash Infinity and Hold the Jackpot featuring a 1500x Grand Jackpot." },
  "wazdan-9-coins-grand-platinum-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-coins-grand-platinum-edition", verifiedAt, evidence: "Official page confirms nine reels with Chance Level, Cash Out, Cash Infinity and a 2500x Grand Jackpot." },
  "wazdan-9-lions": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-lions", verifiedAt, evidence: "Official page identifies nine independent reels and separate Lions Bonus and Dragons Bonus, as well as Block Symbols Mode." },
  "wazdan-9-lions-hold-the-jackpot": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-lions-hold-the-jackpot", verifiedAt, evidence: "Official page confirms Cash Infinity, Bonus Matrix, Hold the Jackpot and a separate 9 Lions Bonus with One Click 2 Grand." },
  "wazdan-beauty-fruity": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/beauty-fruity", verifiedAt, evidence: "Official page identifies nine independent positions with wins from four identical symbols anywhere, Love Spins, nine Free Spins with x3 and Block Symbols." },
  "wazdan-bells-of-fortune": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/bells-of-fortune", verifiedAt, evidence: "Official page confirms 16 independent reels, Hold the Jackpot after four central bonus symbols, a separate Bells of Fortune Bonus Game, Cash Infinity and Chance Level." },

  "wazdan-black-horse-cash-out-edition": { mechanics: ["Линии","Сбор символов"], source: "https://wazdan.com/games/black-horse-cash-out-edition", verifiedAt, evidence: "Official page confirms 5 reels, 20 lines, Cash Out, Sticky Cash Out, Jackpot Coins and Chance Level." },
  "wazdan-bumba-meu-boi-coin": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/bumba-meu-boi-coin", verifiedAt, evidence: "Official page confirms one main reel and three upper mini reels, Magic Coin, back matrix, Extra Life and Boi Da Fortuna Bonus." },
  "wazdan-burning-stars-3": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/burning-stars-3", verifiedAt, evidence: "Official page confirms nine independent reels in a 3x3 matrix and Hold the Jackpot triggered by three Bonus stars, with three resetting respins." },
  "wazdan-burning-sun": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/burning-sun", verifiedAt, evidence: "Official page confirms sixteen-reel 4x4 grid, Sticky to Infinity and Hold the Jackpot triggered by six Bonus symbols." },
  "wazdan-burning-sun-extremely-light": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/burning-sun-extremely-light", verifiedAt, evidence: "Official release confirms lighter graphics with the original Burning Sun 4x4 and its Sticky to Infinity and Hold the Jackpot features preserved." },
  "wazdan-butterfly-lovers": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/butterfly-lovers", verifiedAt, evidence: "Official page confirms 16 separate reels and wins from eight identical symbols; Liang Shanbo Bonus Spins, Magic Sack and Zhu Yingtai Free Spins are distinct." },
  "wazdan-cash-grotto": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/cash-grotto", verifiedAt, evidence: "Official page confirms 24 reels, Hold the Jackpot triggered by four central Bonus symbols, Moving Cash Out, Cash Infinity and Sticky to Infinity." },

};

export function getCatalogResearchWazdan(slug: string) {
  return catalogResearchWazdan[slug];
}
