import type { CatalogVerifiedDetails } from "./catalog-verified-details";

const verifiedAt = "2026-09-14";

type SourcedCatalogVerifiedDetails = CatalogVerifiedDetails & {
  fieldSource?: string;
  maxWinSource?: string;
};

const details: Record<string, SourcedCatalogVerifiedDetails> = {
  "playn-go-1001-mystery-genie-fortunes": {
    field: "5×3",
    releaseDate: "2025-04-10",
    source: "https://www.playngo.com/games/1001-mystery-genie-fortunes",
    fieldSource: "https://www.playngo.com/posts/super-summer-slots",
    verifiedAt,
  },
  "playn-go-13th-trial-hercules-abyssways": {
    field: "динамическая сетка Abyssways™ в Free Spins",
    releaseDate: "2025-08-14",
    source: "https://www.playngo.com/games/13th-trial-hercules-abyssways",
    fieldSource: "https://www.playngo.com/abyssways",
    verifiedAt,
  },
  "playn-go-15-crystal-roses-a-tale-of-love": {
    field: "5×3",
    releaseDate: "2022-01-13",
    source: "https://www.playngo.com/games/15-crystal-roses%3A-a-tale-of-love",
    fieldSource: "https://www.playngo.com/valentines-slots",
    verifiedAt,
  },
  "playn-go-3-blades-and-blessings": {
    field: "5×5 · 40 линий в Boost/Super/Mega Free Spins",
    releaseDate: "2026-02-12",
    source: "https://www.playngo.com/games/3-blades-%26-blessings",
    fieldSource: "https://www.playngo.com/games/3-blades-%26-blessings",
    verifiedAt,
  },
  "playn-go-3-clown-monty": {
    field: "5×3",
    maxWin: "20000x",
    releaseDate: "2021-05-13",
    source: "https://www.playngo.com/games/3-clown-monty",
    fieldSource: "https://www.playngo.com/post/play-n-go-put-on-a-show-with-new-title-three-clown-monty",
    maxWinSource: "https://www.playngo.com/post/play-n-go-put-on-a-show-with-new-title-three-clown-monty",
    verifiedAt,
  },
  "playn-go-animal-madness": {
    field: "5×5",
    maxWin: "2250x",
    releaseDate: "2022-05-19",
    source: "https://www.playngo.com/games/animal-madness",
    fieldSource: "https://www.playngo.com/post/review-animal-madness-play-n-go-grid-slot",
    maxWinSource: "https://www.playngo.com/post/review-animal-madness-play-n-go-grid-slot",
    verifiedAt,
  },
  "playn-go-ankh-of-anubis-awakening": {
    field: "5 барабанов",
    releaseDate: "2024-08-22",
    source: "https://www.playngo.com/games/ankh-of-anubis-awakening",
    fieldSource: "https://www.playngo.com/post/ankh-of-anubis-awakening",
    verifiedAt,
  },
  "playn-go-big-win-cat-pawsperity": {
    field: "3×3",
    releaseDate: "2025-06-24",
    source: "https://www.playngo.com/games/big-win-cat-pawsperity",
    fieldSource: "https://www.playngo.com/posts/big-win-cat-pawsperity",
    verifiedAt,
  },
  "playn-go-book-of-dead-go-collect": {
    field: "5×3",
    releaseDate: "2026-02-26",
    source: "https://www.playngo.com/games/book-of-dead-go-collect",
    fieldSource: "https://www.playngo.com/post/book-of-dead-go-collect",
    verifiedAt,
  },
  "playn-go-bubblin-riches": {
    field: "6×4",
    releaseDate: "2025-10-16",
    source: "https://www.playngo.com/games/bubblin'-riches",
    fieldSource: "https://www.playngo.com/post/bubblin-riches",
    verifiedAt,
  },
  "playn-go-buildin-bucks": {
    field: "5×3 · 243 способа",
    releaseDate: "2024-09-12",
    source: "https://www.playngo.com/games/buildin'-bucks",
    fieldSource: "https://www.playngo.com/post/buildin-bucks",
    verifiedAt,
  },
  "playn-go-buildin-even-more-bucks": {
    field: "5×5 в Free Spins",
    releaseDate: "2026-06-11",
    source: "https://www.playngo.com/games/buildin'-even-more-bucks",
    fieldSource: "https://www.playngo.com/games/buildin%27-even-more-bucks",
    verifiedAt,
  },
  "playn-go-buildin-more-bucks": {
    field: "5 барабанов · 243 способа",
    releaseDate: "2025-12-11",
    source: "https://www.playngo.com/games/buildin'-more-bucks",
    fieldSource: "https://www.playngo.com/posts/buildin-more-bucks",
    verifiedAt,
  },
  "playn-go-crabbys-gold": {
    field: "6×4 · 4096 способов",
    maxWin: "11520x",
    releaseDate: "2025-05-08",
    source: "https://www.playngo.com/games/crabby's-gold",
    fieldSource: "https://www.playngo.com/post/crabby-s-gold",
    maxWinSource: "https://www.playngo.com/post/crabby-s-gold",
    verifiedAt,
  },
  "playn-go-crystal-hall": {
    field: "сетка +1 ряд в Free Spins",
    releaseDate: "2025-02-13",
    source: "https://www.playngo.com/games/crystal-hall",
    fieldSource: "https://www.playngo.com/post/crystal-hall",
    verifiedAt,
  },
  "playn-go-easter-eggs": {
    field: "5×3",
    releaseDate: "2015-03-17",
    source: "https://www.playngo.com/games/easter-eggs",
    fieldSource: "https://www.playngo.com/post/top-easter-themed-slots-2025",
    verifiedAt,
  },
  "playn-go-easter-eggspedition": {
    field: "5×3",
    releaseDate: "2024-03-28",
    source: "https://www.playngo.com/games/easter-eggspedition",
    fieldSource: "https://www.playngo.com/post/easter-eggspedition-game-review",
    verifiedAt,
  },
  "playn-go-fangs-and-fire": {
    field: "5×3 → 5×7",
    releaseDate: "2025-11-27",
    source: "https://www.playngo.com/games/fangs-%26-fire",
    fieldSource: "https://www.playngo.com/posts/fangs-and-fire",
    verifiedAt,
  },
  "playn-go-fire-joker-100": {
    field: "3×3",
    releaseDate: "2025-05-29",
    source: "https://www.playngo.com/games/fire-joker-100",
    fieldSource: "https://www.playngo.com/post/fire-joker-100",
    verifiedAt,
  },
  "playn-go-fire-joker-blitz": {
    field: "6 барабанов",
    releaseDate: "2025-08-28",
    source: "https://www.playngo.com/games/fire-joker-blitz",
    fieldSource: "https://www.playngo.com/posts/fire-joker-blitz",
    verifiedAt,
  },
  "playn-go-free-reelin-joker-1000": {
    field: "3×1",
    maxWin: "1000x",
    releaseDate: "2023-05-25",
    source: "https://www.playngo.com/games/free-reelin'-joker-1000",
    fieldSource: "https://www.playngo.com/post/playngos-free-reelin-joker-1000-is-the-winning-card-of-the-deck",
    maxWinSource: "https://www.playngo.com/post/the-evolution-of-joker-slot-series-retrospective",
    verifiedAt,
  },
  "playn-go-gargantoonz": {
    field: "7×7",
    releaseDate: "2023-11-30",
    source: "https://www.playngo.com/games/gargantoonz",
    fieldSource: "https://www.playngo.com/posts/garagantoonz",
    verifiedAt,
  },
  "playn-go-gerards-gambit": {
    field: "3×1 · 1 линия → 5×3 · 10 линий",
    releaseDate: "2023-04-27",
    source: "https://www.playngo.com/games/gerard's-gambit",
    fieldSource: "https://www.playngo.com/post/gerards-gambit",
    verifiedAt,
  },
  "playn-go-ghost-of-dead": {
    field: "5×3",
    maxWin: "10000x",
    releaseDate: "2021-09-16",
    source: "https://www.playngo.com/games/ghost-of-dead",
    fieldSource: "https://www.playngo.com/post/playngo-awaken-akh-as-the-dead-series-continues",
    maxWinSource: "https://www.playngo.com/post/playngo-awaken-akh-as-the-dead-series-continues",
    verifiedAt,
  },
  "playn-go-hugo-legacy": {
    field: "7×7",
    releaseDate: "2023-08-10",
    source: "https://www.playngo.com/games/hugo-legacy",
    fieldSource: "https://www.playngo.com/posts/hugo-legacy",
    verifiedAt,
  },
  "playn-go-ice-joker": {
    field: "5×3 · 20 линий",
    releaseDate: "2020-12-03",
    source: "https://www.playngo.com/games/ice-joker",
    fieldSource: "https://www.playngo.com/posts/top-winter-themed-slots",
    verifiedAt,
  },
  "playn-go-kings-mask": {
    maxWin: "10000x",
    releaseDate: "2022-05-26",
    source: "https://www.playngo.com/games/king's-mask",
    verifiedAt,
  },
  "playn-go-lady-of-fortune-destiny-spins": {
    field: "3 направления выплат",
    releaseDate: "2025-08-07",
    source: "https://www.playngo.com/games/lady-of-fortune-destiny-spins",
    verifiedAt,
  },
  "playn-go-loot-and-labyrinths": {
    field: "5×3",
    releaseDate: "2025-04-03",
    source: "https://www.playngo.com/games/loot-%26-labyrinths",
    fieldSource: "https://www.playngo.com/posts/loot-and-labyrinths",
    verifiedAt,
  },
  "playn-go-merlin-journey-of-flame": {
    field: "6 барабанов в Free Spins",
    releaseDate: "2023-07-13",
    source: "https://www.playngo.com/games/merlin%3A-journey-of-flame",
    verifiedAt,
  },
  "playn-go-moon-princess-100": {
    field: "5×5",
    releaseDate: "2022-04-07",
    source: "https://www.playngo.com/games/moon-princess-100",
    fieldSource: "https://it.playngo.com/series/grid-slots",
    verifiedAt,
  },
  "playn-go-mystery-egg-surprise": {
    field: "3 барабана · 5 линий",
    releaseDate: "2025-03-20",
    source: "https://www.playngo.com/games/mystery-egg-surprise",
    fieldSource: "https://www.playngo.com/post/mystery-egg-surprise",
    verifiedAt,
  },
  "playn-go-naughty-nicks-book": {
    field: "6 барабанов в Free Spins",
    releaseDate: "2022-12-08",
    source: "https://www.playngo.com/games/naughty-nick's-book",
    verifiedAt,
  },
  "playn-go-oasis-of-dead": {
    field: "5×3 · 20 линий",
    releaseDate: "2024-07-04",
    source: "https://www.playngo.com/games/oasis-of-dead",
    fieldSource: "https://www.playngo.com/posts/oasis-of-dead-review",
    verifiedAt,
  },
  "playn-go-octopus-treasure": {
    field: "5×3 · 20 линий",
    releaseDate: "2020-09-10",
    source: "https://www.playngo.com/games/octopus-treasure",
    fieldSource: "https://www.playngo.com/post/the-top-4-underwater-slots-to-play-in-2023",
    verifiedAt,
  },
  "playn-go-pandastic-adventure": {
    field: "5×3",
    maxWin: "6500x",
    releaseDate: "2024-01-11",
    source: "https://www.playngo.com/games/pandastic-adventure",
    fieldSource: "https://www.playngo.com/post/pandastic-adventure",
    maxWinSource: "https://www.playngo.com/post/pandastic-adventure",
    verifiedAt,
  },
  "playn-go-phoenix-reborn": {
    field: "5 барабанов",
    releaseDate: "2019-04-16",
    source: "https://www.playngo.com/games/phoenix-reborn",
    fieldSource: "https://www.playngo.com/post/play-n-go-rise-to-the-occasion-with-phoenix-reborn",
    verifiedAt,
  },
  "playn-go-piggy-blitz": {
    field: "4096 способов",
    maxWin: "5000x",
    releaseDate: "2023-09-21",
    source: "https://www.playngo.com/games/piggy-blitz",
    fieldSource: "https://www.playngo.com/post/piggy-blitz",
    maxWinSource: "https://www.playngo.com/post/piggy-blitz",
    verifiedAt,
  },
  "playn-go-piggy-blitz-casino-gold": {
    field: "6 барабанов · 4096 способов",
    releaseDate: "2026-01-29",
    source: "https://www.playngo.com/games/piggy-blitz-casino-gold",
    fieldSource: "https://www.playngo.com/posts/piggy-blitz-casino-gold",
    verifiedAt,
  },
  "playn-go-piggy-blitz-disco-gold": {
    field: "6×4",
    maxWin: "5000x",
    releaseDate: "2024-11-07",
    source: "https://www.playngo.com/games/piggy-blitz-disco-gold",
    fieldSource: "https://www.playngo.com/post/play-n-go-music-launches-piggy-blitz-disco-gold-visualiser",
    maxWinSource: "https://www.playngo.com/post/play-n-go-music-launches-piggy-blitz-disco-gold-visualiser",
    verifiedAt,
  },
  "playn-go-piggy-heist": {
    field: "6 барабанов",
    releaseDate: "2025-12-16",
    source: "https://www.playngo.com/games/piggy-heist",
    fieldSource: "https://www.playngo.com/posts/piggy-heist",
    verifiedAt,
  },
  "playn-go-piranha-pays": {
    field: "5×4 · 30 линий → 5×8",
    releaseDate: "2024-03-21",
    source: "https://www.playngo.com/games/piranha-pays",
    fieldSource: "https://www.playngo.com/post/piranha-pays",
    verifiedAt,
  },
  "playn-go-potion-of-madness": {
    field: "5 барабанов → 5×6 · 40 линий в Free Spins",
    releaseDate: "2025-01-30",
    source: "https://www.playngo.com/games/potion-of-madness",
    fieldSource: "https://www.playngo.com/post/potion-of-madness",
    verifiedAt,
  },
  "playn-go-puebla-parade": {
    field: "5×4 → 5×7",
    releaseDate: "2022-04-21",
    source: "https://www.playngo.com/games/puebla-parade",
    fieldSource: "https://www.playngo.com/post/puebla-parade-gets-the-party-started",
    verifiedAt,
  },
  "playn-go-rabbit-hole-riches": {
    field: "3×3",
    releaseDate: "2020-10-08",
    source: "https://www.playngo.com/games/rabbit-hole-riches",
    fieldSource: "https://www.playngo.com/post/play-n-go-bring-back-the-wonder-in-court-of-hearts",
    verifiedAt,
  },
};

export function getCatalogVerifiedDetailsPlayngoProviderWide(slug: string) {
  return details[slug];
}
