import type { CatalogVerifiedDetails } from "./catalog-verified-details";

type WazdanScore4Values = Partial<Pick<CatalogVerifiedDetails, "rtp" | "maxWin" | "volatility">>;

const verifiedAt = "2026-09-18";

const values: Record<string, WazdanScore4Values> = {
  "wazdan-12-coins": { rtp: "96,13%", maxWin: "750x", volatility: "Высокая" },
  "wazdan-12-coins-grand-diamond-edition": { rtp: "96,14%", maxWin: "5000x", volatility: "Высокая" },
  "wazdan-12-coins-grand-gold-edition": { rtp: "96,13%", maxWin: "1500x", volatility: "Высокая" },
  "wazdan-12-coins-grand-platinum-edition": { rtp: "96,15%", maxWin: "2500x", volatility: "Высокая" },
  "wazdan-15-coins": { rtp: "96,07%", maxWin: "1000x", volatility: "Высокая" },
  "wazdan-15-coins-grand-diamond-edition": { rtp: "96,15%", maxWin: "5000x", volatility: "Высокая" },
  "wazdan-15-coins-grand-gold-edition": { rtp: "96,18%", maxWin: "2000x", volatility: "Высокая" },
  "wazdan-15-coins-grand-platinum-edition": { rtp: "96,17%", maxWin: "2500x", volatility: "Высокая" },
  "wazdan-16-coins": { rtp: "96,18%", maxWin: "1000x", volatility: "Высокая" },
  "wazdan-16-coins-grand-gold-edition": { rtp: "96,15%", maxWin: "2000x", volatility: "Высокая" },
  "wazdan-16-coins-grand-platinum-edition": { rtp: "96,16%", maxWin: "2500x", volatility: "Высокая" },
  "wazdan-16-coins-x5000": { rtp: "96,17%", maxWin: "5000x", volatility: "Высокая" },
  "wazdan-20-coins": { rtp: "96,18%", maxWin: "1500x", volatility: "Высокая" },
  "wazdan-20-coins-grand-gold-edition": { rtp: "96,15%", maxWin: "2000x", volatility: "Высокая" },
  "wazdan-24-coins": { rtp: "96,15%", maxWin: "1200x", volatility: "Высокая" },
  "wazdan-25-coins": { rtp: "96,17%", maxWin: "2000x", volatility: "Высокая" },
  "wazdan-25-coins-grand-gold-edition": { rtp: "96,13%", maxWin: "2500x", volatility: "Очень высокая" },
  "wazdan-25-coins-x3000": { rtp: "96,19%", volatility: "Высокая" },
  "wazdan-30-coins": { rtp: "96,18%", maxWin: "1500x", volatility: "Высокая" },
  "wazdan-30-coins-grand-gold-edition": { rtp: "96,2%", maxWin: "2500x", volatility: "Очень высокая" },
  "wazdan-36-coins": { rtp: "96,16%", maxWin: "2000x", volatility: "Высокая" },
  "wazdan-36-coins-grand-gold-edition": { rtp: "96,14%", maxWin: "2500x", volatility: "Очень высокая" },
  "wazdan-9-balls": { rtp: "96,04%", maxWin: "2500x", volatility: "Высокая" },
  "wazdan-9-bells": { rtp: "96,16%", maxWin: "1500x", volatility: "Высокая" },
  "wazdan-9-burning-dragons": { rtp: "96,12%", maxWin: "2187x", volatility: "Очень высокая" },
  "wazdan-9-burning-stars": { rtp: "96,14%", maxWin: "1500x", volatility: "Высокая" },
  "wazdan-9-coins": { rtp: "96,06%", maxWin: "500x", volatility: "Средняя–высокая" },
  "wazdan-9-coins-1000-edition": { rtp: "96,14%", maxWin: "1000x", volatility: "Высокая" },
  "wazdan-9-coins-extremely-light": { rtp: "96,06%", maxWin: "500x", volatility: "Средняя–высокая" },
  "wazdan-9-coins-grand-diamond-edition": { rtp: "96,15%", maxWin: "5000x", volatility: "Очень высокая" },
  "wazdan-9-coins-grand-gold-edition": { rtp: "96,14%", maxWin: "1500x", volatility: "Высокая" },
  "wazdan-9-coins-grand-platinum-edition": { rtp: "96,04%", maxWin: "2500x", volatility: "Высокая" },
  "wazdan-9-lions": { rtp: "96,59%", maxWin: "1000x" },
  "wazdan-9-lions-hold-the-jackpot": { rtp: "96,14%", maxWin: "750x", volatility: "Высокая" },
  "wazdan-arcade": { rtp: "96,62%", maxWin: "409x", volatility: "Высокая" },
  "wazdan-beauty-fruity": { rtp: "96,27%", maxWin: "2500x", volatility: "Средняя" },
  "wazdan-black-hawk": { rtp: "96,23%", maxWin: "600x", volatility: "Средняя" },
  "wazdan-bumba-meu-boi-coin": { rtp: "96,14%", maxWin: "500x", volatility: "Средняя–высокая" },
  "wazdan-burning-stars-3": { rtp: "96,12%", maxWin: "2187x", volatility: "Очень высокая" },
  "wazdan-burning-sun": { rtp: "96,12%", maxWin: "5000x", volatility: "Очень высокая" },
  "wazdan-burning-sun-extremely-light": { rtp: "96,12%", maxWin: "5000x", volatility: "Очень высокая" },
  "wazdan-butterfly-lovers": { rtp: "96,16%", maxWin: "1600x", volatility: "Средняя–высокая" },
  "wazdan-cash-grotto": { rtp: "96,13%", maxWin: "1500x", volatility: "Высокая" },
  "wazdan-double-tigers": { rtp: "96,43%", maxWin: "40x", volatility: "Низкая–средняя" },
  "wazdan-dwarfs-fortune": { rtp: "96,16%", maxWin: "2500x", volatility: "Высокая" },
  "wazdan-easter-coins": { rtp: "96,17%", maxWin: "2000x", volatility: "Высокая" },
  "wazdan-eggs-of-fortune": { rtp: "96,12%", maxWin: "5000x", volatility: "Экстремальная" },
  "wazdan-fishermans-luck": { rtp: "96,13%", maxWin: "2500x", volatility: "Средняя" },
  "wazdan-football-mania": { rtp: "96,59%", maxWin: "1000x", volatility: "Высокая" },
  "wazdan-football-mania-deluxe": { rtp: "96,59%", maxWin: "1000x", volatility: "Высокая" },
  "wazdan-fruit-mania": { rtp: "96,59%", maxWin: "1000x", volatility: "Высокая" },
  "wazdan-fruit-mania-deluxe": { rtp: "96,59%", maxWin: "1000x", volatility: "Высокая" },
  "wazdan-fruits-go-bananas": { rtp: "96,34%", maxWin: "850x", volatility: "Средняя" },
  "wazdan-gem-splitter": { rtp: "96,27%", maxWin: "9000x", volatility: "Высокая" },
  "wazdan-golden-sphinx": { rtp: "96,48%", maxWin: "4650x", volatility: "Высокая" },
  "wazdan-good-luck-40": { rtp: "96,62%", maxWin: "2000x", volatility: "Низкая" },
  "wazdan-great-book-of-magic": { rtp: "96,47%", maxWin: "5150x", volatility: "Высокая" },
  "wazdan-great-book-of-magic-deluxe": { rtp: "96,47%", maxWin: "5150x", volatility: "Высокая" },
  "wazdan-haunted-coins-x1000": { rtp: "96,18%", maxWin: "1000x", volatility: "Высокая" },
  "wazdan-haunted-hospital": { rtp: "96,49%", maxWin: "820x", volatility: "Высокая" },
  "wazdan-highschool-manga": { rtp: "96,41%", maxWin: "320x" },
  "wazdan-highway-to-hell": { rtp: "96,18%", maxWin: "2500x", volatility: "Низкая–средняя" },
  "wazdan-highway-to-hell-deluxe": { rtp: "96,56%", maxWin: "1000x", volatility: "Высокая" },
  "wazdan-hot-777-deluxe": { rtp: "96,47%", maxWin: "200x", volatility: "Средняя" },
  "wazdan-hot-party": { rtp: "96,48%", maxWin: "305x", volatility: "Низкая–средняя" },
  "wazdan-hot-party-deluxe": { rtp: "96,42%", maxWin: "305x", volatility: "Низкая–средняя" },
  "wazdan-hot-slot-777-crown-extremely-light": { rtp: "96,42%", maxWin: "305x", volatility: "Низкая–средняя" },
  "wazdan-hot-slot-diamond-coins": { rtp: "96,18%", maxWin: "3000x", volatility: "Высокая" },
  "wazdan-hot-slot-magic-pearls": { rtp: "96,19%", maxWin: "2500x", volatility: "Высокая" },
  "wazdan-hot-slot-mystery-jackpot-joker": { rtp: "96,11%", maxWin: "1000x", volatility: "Высокая" },
  "wazdan-hot-slot-platinum-coins": { rtp: "96,15%", maxWin: "2500x", volatility: "Высокая" },
  "wazdan-hungry-shark": { rtp: "96,47%", maxWin: "5150x", volatility: "Высокая" },
  "wazdan-in-the-forest": { rtp: "96,63%", maxWin: "1250x", volatility: "Низкая" },
  "wazdan-infinity-hero": { rtp: "96,24%", maxWin: "13000x", volatility: "Средняя–высокая" },
  "wazdan-jacks-ride": { rtp: "96,4%", maxWin: "81x", volatility: "Низкая–средняя" },
  "wazdan-joker-explosion": { rtp: "96,5%", maxWin: "2350x", volatility: "Низкая–средняя" },
  "wazdan-juicy-reels": { rtp: "96,49%", maxWin: "750x", volatility: "Низкая" },
  "wazdan-jumping-fruits": { rtp: "96,4%", maxWin: "81x", volatility: "Низкая–средняя" },
  "wazdan-kick-off": { rtp: "96,42%", maxWin: "440x", volatility: "Стандартная" },
  "wazdan-larry-the-leprechaun": { rtp: "96,47%", maxWin: "350x", volatility: "Низкая–средняя" },
  "wazdan-los-muertos": { rtp: "96,29%", maxWin: "850x", volatility: "Низкая–средняя" },
  "wazdan-los-muertos-ii": { rtp: "96,41%", maxWin: "40x", volatility: "Низкая–средняя" },
  "wazdan-lost-treasure": { rtp: "96,13%", maxWin: "3500x", volatility: "Низкая–средняя" },
  "wazdan-magic-eggs": { rtp: "96,41%", maxWin: "40x", volatility: "Низкая–средняя" },
  "wazdan-magic-fruit-cherries": { rtp: "96,13%", maxWin: "500x", volatility: "Средняя" },
  "wazdan-magic-fruit-oranges": { rtp: "96,14%", maxWin: "100x", volatility: "Низкая–средняя" },
  "wazdan-magic-hot": { rtp: "96,35%", maxWin: "1000x", volatility: "Низкая–средняя" },
  "wazdan-magic-hot-4": { rtp: "96,1%", maxWin: "260x", volatility: "Средняя" },
  "wazdan-magic-of-the-ring": { rtp: "96,47%", maxWin: "5150x", volatility: "Высокая" },
  "wazdan-magic-of-the-ring-deluxe": { rtp: "96,47%", maxWin: "5150x", volatility: "Высокая" },
  "wazdan-magic-stars": { rtp: "96,25%", maxWin: "40x", volatility: "Низкая–средняя" },
  "wazdan-magic-stars-9": { rtp: "96,21%", maxWin: "10500x", volatility: "Высокая" },
  "wazdan-mighty-crown-empire-of-gold": { rtp: "96,13%", maxWin: "1500x", volatility: "Очень высокая" },
  "wazdan-mighty-crown-legacy-of-mars": { rtp: "96,15%", maxWin: "3000x", volatility: "Средняя" },
  "wazdan-mighty-fish-blue-marlin": { rtp: "96,18%", maxWin: "2500x", volatility: "Очень высокая" },
  "wazdan-mighty-symbols-crowns": { rtp: "96,15%", maxWin: "2500x", volatility: "Низкая–средняя" },
  "wazdan-mighty-symbols-diamonds": { rtp: "96,13%", maxWin: "2500x", volatility: "Низкая–средняя" },
  "wazdan-mighty-symbols-jokers": { rtp: "96,14%", maxWin: "750x", volatility: "Высокая" },
  "wazdan-mighty-symbols-sevens": { rtp: "96,17%", maxWin: "2000x", volatility: "Низкая–средняя" },
  "wazdan-mighty-wild-gorilla": { rtp: "96,2%", maxWin: "2500x", volatility: "Очень высокая" },
  "wazdan-mighty-wild-jaguar": { rtp: "96,14%", maxWin: "750x", volatility: "Высокая" },
  "wazdan-mighty-wild-panther-grand-gold-edition": { rtp: "96,15%", maxWin: "1500x", volatility: "Высокая" },
  "wazdan-mighty-wild-panther-grand-platinum-edition": { rtp: "96,12%", maxWin: "2500x", volatility: "Высокая" },
  "wazdan-moon-of-fortune": { rtp: "96,12%", maxWin: "1500x", volatility: "Высокая" },
  "wazdan-neon-city": { rtp: "96,25%", maxWin: "1250x", volatility: "Низкая–средняя" },
  "wazdan-one-coin": { rtp: "96,17%", maxWin: "500x", volatility: "Средняя" },
  "wazdan-ox-coin": { rtp: "96,21%", maxWin: "2500x", volatility: "Высокая" },
  "wazdan-power-of-gods-egypt": { rtp: "96,19%", maxWin: "8000x", volatility: "Высокая" },
  "wazdan-power-of-gods-hades": { rtp: "96,14%", maxWin: "5000x", volatility: "Высокая" },
  "wazdan-power-of-gods-medusa": { rtp: "96,18%", maxWin: "2500x", volatility: "Высокая" },
  "wazdan-power-of-gods-medusa-extremely-light": { rtp: "96,18%", maxWin: "2500x", volatility: "Высокая" },
  "wazdan-power-of-gods-the-pantheon": { rtp: "96,2%", maxWin: "1450x", volatility: "Средняя" },
  "wazdan-power-of-gods-valhalla": { rtp: "96,23%", maxWin: "2145x", volatility: "Высокая" },
  "wazdan-power-of-gods-valhalla-extremely-light": { rtp: "96,23%", maxWin: "2145x", volatility: "Высокая" },
  "wazdan-power-of-sun-svarog": { rtp: "96,15%", maxWin: "5000x", volatility: "Высокая" },
  "wazdan-prosperity-pearls": { rtp: "96,15%", maxWin: "4000x", volatility: "Очень высокая" },
  "wazdan-santas-gifts-frenzy": { rtp: "96,12%", maxWin: "1500x", volatility: "Средняя–высокая" },
  "wazdan-sizzling-eggs-grand-gold-edition": { rtp: "96,16%", maxWin: "3000x", volatility: "Экстремальная" },
  "wazdan-sizzling-eggs-grand-platinum-edition": { rtp: "96,11%", maxWin: "4000x", volatility: "Экстремальная" },
  "wazdan-sizzling-moon": { rtp: "96,14%", maxWin: "2500x", volatility: "Высокая" },
  "wazdan-slot-jam": { rtp: "96,59%", maxWin: "570x", volatility: "Средняя" },
  "wazdan-sonic-reels": { rtp: "96,24%", maxWin: "5400x", volatility: "Средняя" },
  "wazdan-space-gem": { rtp: "96,4%", maxWin: "1000x", volatility: "Низкая" },
  "wazdan-space-spins": { rtp: "96,66%", maxWin: "1650x", volatility: "Низкая–средняя" },
  "wazdan-spectrum": { rtp: "96,53%", maxWin: "500x", volatility: "Низкая–средняя" },
  "wazdan-sun-of-fortune": { rtp: "96,15%", maxWin: "1450x", volatility: "Высокая" },
  "wazdan-super-hot": { rtp: "96,16%", maxWin: "340x", volatility: "Средняя" },
  "wazdan-throne-of-elements-platinum": { rtp: "96,15%", maxWin: "2500x", volatility: "Высокая" },
  "wazdan-mighty-wild-panther-grand-diamond-edition": { rtp: "96,16%", maxWin: "5000x", volatility: "Высокая" },
  "wazdan-triple-star": { rtp: "96,28%", maxWin: "1000x", volatility: "Низкая" },
  "wazdan-unicorn-reels": { rtp: "96,14%", maxWin: "1000x", volatility: "Очень высокая" },
  "wazdan-valentines-coins": { rtp: "96,06%", maxWin: "500x", volatility: "Средняя–высокая" },
  "wazdan-valhalla": { rtp: "96,47%", maxWin: "600x", volatility: "Средняя" },
  "wazdan-vegas-hot": { rtp: "96,05%", maxWin: "340x", volatility: "Средняя" },
  "wazdan-vegas-reels-ii": { rtp: "96,16%", maxWin: "3000x", volatility: "Высокая" },
  "wazdan-welcome-to-hell-81": { rtp: "96,35%", maxWin: "5850x", volatility: "Средняя–высокая" },
  "wazdan-wild-girls": { rtp: "96,53%", maxWin: "532x", volatility: "Средняя" },
  "wazdan-wild-guns": { rtp: "96,34%", maxWin: "850x", volatility: "Средняя" },
  "wazdan-wild-jack": { rtp: "96,34%", maxWin: "748x", volatility: "Высокая" },
  "wazdan-wild-jack-81": { rtp: "96,73%", maxWin: "2240x", volatility: "Низкая–средняя" },
};

export function getCatalogVerifiedDetailsWazdanScore4Fill(slug: string) {
  const value = values[slug];
  return value ? { ...value, verifiedAt } : undefined;
}
