const artworkBySlug: Record<string, string> = {
  "3-oaks-gaming-15-dragon-pearls": "/images/catalog/3-oaks-gaming-15-dragon-pearls.webp",
  "3-oaks-gaming-3-african-drums": "/images/catalog/3-oaks-gaming-3-african-drums.webp",
  "3-oaks-gaming-3-aztec-temples": "/images/catalog/3-oaks-gaming-3-aztec-temples.webp",
  "3-oaks-gaming-3-china-pots": "/images/catalog/3-oaks-gaming-3-china-pots.webp",
  "3-oaks-gaming-3-clover-pots": "/images/catalog/3-oaks-gaming-3-clover-pots.webp",
  "3-oaks-gaming-3-clover-pots-extra": "/images/catalog/3-oaks-gaming-3-clover-pots-extra.webp",
  "3-oaks-gaming-3-coin-volcanoes": "/images/catalog/3-oaks-gaming-3-coin-volcanoes.webp",
  "3-oaks-gaming-3-coins": "/images/catalog/3-oaks-gaming-3-coins.webp",
  "3-oaks-gaming-3-egypt-chests": "/images/catalog/3-oaks-gaming-3-egypt-chests.webp",
  "3-oaks-gaming-3-hot-chillies": "/images/catalog/3-oaks-gaming-3-hot-chillies.webp",
  "3-oaks-gaming-3-hot-teapots": "/images/catalog/3-oaks-gaming-3-hot-teapots.webp",
  "3-oaks-gaming-3-jewel-crowns": "/images/catalog/3-oaks-gaming-3-jewel-crowns.webp",
  "3-oaks-gaming-3-lucky-sparks": "/images/catalog/3-oaks-gaming-3-lucky-sparks.webp",
  "3-oaks-gaming-3-olymp-fortunes": "/images/catalog/3-oaks-gaming-3-olymp-fortunes.webp",
  "3-oaks-gaming-3-pots-of-egypt": "/images/catalog/3-oaks-gaming-3-pots-of-egypt.webp",
  "3-oaks-gaming-3-super-coin-volcanoes": "/images/catalog/3-oaks-gaming-3-super-coin-volcanoes.webp",
  "3-oaks-gaming-3-super-hot-chillies": "/images/catalog/3-oaks-gaming-3-super-hot-chillies.webp",
  "3-oaks-gaming-3-super-hot-teapots": "/images/catalog/3-oaks-gaming-3-super-hot-teapots.webp",
  "3-oaks-gaming-4-african-drums": "/images/catalog/3-oaks-gaming-4-african-drums.webp",
  "3-oaks-gaming-4-clover-pots": "/images/catalog/3-oaks-gaming-4-clover-pots.webp",
  "3-oaks-gaming-4-fairy-flowers": "/images/catalog/3-oaks-gaming-4-fairy-flowers.webp",
  "3-oaks-gaming-4-fortune-clovers": "/images/catalog/3-oaks-gaming-4-fortune-clovers.webp",
  "3-oaks-gaming-4-pots-of-egypt": "/images/catalog/3-oaks-gaming-4-pots-of-egypt.webp",
  "3-oaks-gaming-4-wolf-drums": "/images/catalog/3-oaks-gaming-4-wolf-drums.webp",
  "3-oaks-gaming-777-fruity-coins": "/images/catalog/3-oaks-gaming-777-fruity-coins.webp",
  "3-oaks-gaming-777-gems-respin": "/images/catalog/3-oaks-gaming-777-gems-respin.webp",
  "3-oaks-gaming-amazonia-wins": "/images/catalog/3-oaks-gaming-amazonia-wins.webp",
  "3-oaks-gaming-aztec-fire": "/images/catalog/3-oaks-gaming-aztec-fire.webp",
  "3-oaks-gaming-aztec-fire-2": "/images/catalog/3-oaks-gaming-aztec-fire-2.webp",
  "3-oaks-gaming-aztec-sun": "/images/catalog/3-oaks-gaming-aztec-sun.webp",
  "3-oaks-gaming-big-heist": "/images/catalog/3-oaks-gaming-big-heist.webp",
  "3-oaks-gaming-black-wolf": "/images/catalog/3-oaks-gaming-black-wolf.webp",
  "3-oaks-gaming-black-wolf-2": "/images/catalog/3-oaks-gaming-black-wolf-2.webp",
  "3-oaks-gaming-book-of-sun-multichance": "/images/catalog/3-oaks-gaming-book-of-sun-multichance.webp",
  "3-oaks-gaming-buddha-megaways": "/images/catalog/3-oaks-gaming-buddha-megaways.webp",
  "3-oaks-gaming-chili-coins": "/images/catalog/3-oaks-gaming-chili-coins.webp",
  "3-oaks-gaming-china-festival": "/images/catalog/3-oaks-gaming-china-festival.webp",
  "3-oaks-gaming-coin-express": "/images/catalog/3-oaks-gaming-coin-express.webp",
  "3-oaks-gaming-coin-lamp": "/images/catalog/3-oaks-gaming-coin-lamp.webp",
  "3-oaks-gaming-coin-princess-x1000": "/images/catalog/3-oaks-gaming-coin-princess-x1000.webp",
  "3-oaks-gaming-coin-up-volcano": "/images/catalog/3-oaks-gaming-coin-up-volcano.webp",
  "3-oaks-gaming-coin-volcano": "/images/catalog/3-oaks-gaming-coin-volcano.webp",
  "3-oaks-gaming-coin-volcano-2": "/images/catalog/3-oaks-gaming-coin-volcano-2.webp",
  "3-oaks-gaming-crystal-scarabs": "/images/catalog/3-oaks-gaming-crystal-scarabs.webp",
  "3-oaks-gaming-dancing-joker": "/images/catalog/3-oaks-gaming-dancing-joker.webp",
  "3-oaks-gaming-dj-tiger-x1000": "/images/catalog/3-oaks-gaming-dj-tiger-x1000.webp",
  "3-oaks-gaming-dragon-pearls": "/images/catalog/3-oaks-gaming-dragon-pearls.webp",
  "3-oaks-gaming-egypt-fire-2": "/images/catalog/3-oaks-gaming-egypt-fire-2.webp",
  "3-oaks-gaming-egypt-power-x1000": "/images/catalog/3-oaks-gaming-egypt-power-x1000.webp",
  "3-oaks-gaming-fortune-globe": "/images/catalog/3-oaks-gaming-fortune-globe.webp",
  "3-oaks-gaming-gold-express": "/images/catalog/3-oaks-gaming-gold-express.webp",
  "3-oaks-gaming-gold-nuggets": "/images/catalog/3-oaks-gaming-gold-nuggets.webp",
  "3-oaks-gaming-golden-teapot": "/images/catalog/3-oaks-gaming-golden-teapot.webp",
  "3-oaks-gaming-grab-more-gold": "/images/catalog/3-oaks-gaming-grab-more-gold.webp",
  "3-oaks-gaming-grab-the-gold": "/images/catalog/3-oaks-gaming-grab-the-gold.webp",
};

export function getCatalogArtwork(slug: string) {
  return artworkBySlug[slug] ?? null;
}
