import type { CatalogResearch } from "./catalog-research";

const verifiedAt = "2026-09-11";

export const catalogResearchWazdan: Record<string, CatalogResearch> = {
  "wazdan-12-bells": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/12-bells", verifiedAt, evidence: "Official Wazdan game page lists two separate bonus modes, 12 Bells Bonus Game and Hold the Jackpot, using 12 reels and Cash Infinity." },
  "wazdan-15-coins-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/15-coins-grand-gold-edition", verifiedAt, evidence: "Fifteen independent reels; Cash Infinity, Hold the Jackpot, Chance Level up to 10x and Grand Jackpot 2000x." },
  "wazdan-15-coins-grand-platinum-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/15-coins-grand-platinum-edition", verifiedAt, evidence: "Fifteen reels and new Cash Out in base game alongside Cash Infinity and Hold the Jackpot with 2500x Grand." },
  "wazdan-16-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/16-coins", verifiedAt, evidence: "Sixteen individual reels in a 4x4 grid with Cash Infinity and Hold the Jackpot, maximum 1000x." },
  "wazdan-16-coins-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/16-coins-grand-gold-edition", verifiedAt, evidence: "Sixteen reels, enhanced Hold the Jackpot to 2000x, Cash Infinity and Chance Level." },
  "wazdan-16-coins-grand-platinum-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/16-coins-grand-platinum-edition", verifiedAt, evidence: "Sixteen-reel Platinum edition adds Cash Out and Hold the Jackpot to 2500x." },
  "wazdan-16-coins-x5000": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/16-coins-x5000", verifiedAt, evidence: "Official game specifies three resetting respins, Cash Out labels with countdown and Grand Jackpot 5000x." },
  "wazdan-20-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/20-coins", verifiedAt, evidence: "Twenty independent reels, Sticky to Infinity, Cash Infinity, Chance Level x2/x4/x6 and Hold the Jackpot." },
  "wazdan-20-coins-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/20-coins-grand-gold-edition", verifiedAt, evidence: "Twenty reels with higher 2000x Grand Jackpot, Cash Infinity, Sticky to Infinity and Hold the Jackpot." },
  "wazdan-24-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/24-coins", verifiedAt, evidence: "Twenty-four reels; Moving Cash Out debuted in this version alongside Cluster Collector and Hold the Jackpot." },
  "wazdan-25-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/25-coins", verifiedAt, evidence: "Twenty-five positions with Cluster Collector collecting nearby cash values, Sticky to Infinity and Hold the Jackpot." },
  "wazdan-25-coins-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/25-coins-grand-gold-edition", verifiedAt, evidence: "Grand Gold adds Collect to Infinity as modifier preserving Cluster Collector until bonus ends; Grand 2500x." },
  "wazdan-25-coins-x3000": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/25-coins-x3000", verifiedAt, evidence: "October 1, 2026 first-party Wazdan news release confirms Hold the Jackpot three resetting respins, full 25-position grid awarding 3000x, sticky Cash Infinity and five-spin Cluster Collector." },
  "wazdan-30-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/30-coins", verifiedAt, evidence: "Thirty reels, Cluster Collector, Cash Infinity and Sticky to Infinity with 1500x Grand Jackpot." },
  "wazdan-30-coins-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/30-coins-grand-gold-edition", verifiedAt, evidence: "Thirty reels with upgraded Collector and Collect to Infinity, Chance Level choices and 2500x Grand." },
  "wazdan-36-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/36-coins", verifiedAt, evidence: "Six-by-six, thirty-six-reel grid with Cluster Collector and Sticky to Infinity, 2000x maximum." },
  "wazdan-36-coins-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/36-coins-grand-gold-edition", verifiedAt, evidence: "Thirty-six reels with Collect to Infinity modifying Cluster Collector and Chance Level x2/x5/x10." },
  "wazdan-9-balls": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-balls", verifiedAt, evidence: "Nine-reel football slot with Penalty Kick countdown Cash Out, xG Chance Level and Hold the Jackpot." },
  "wazdan-9-bells": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-bells", verifiedAt, evidence: "Nine reels with Bonus Matrix, Bell Symbols activating Hold the Jackpot, Cash Out and Chance Level up to 6x." },
  "wazdan-9-burning-dragons": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-burning-dragons", verifiedAt, evidence: "Nine independent reels; Wild and direct Buy Feature for Hold the Jackpot; 2187x stated maximum." },
  "wazdan-back-to-the-70s": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/back-to-the-70s",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 20 lines.",
  },
  "wazdan-bars7s": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/bars7s",
    verifiedAt,
    evidence: "Official Game Info lists 3 reels and 8 lines and the page explicitly describes the winning payline.",
  },
  "wazdan-beach-party": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/beach-party",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 20 lines.",
  },
  "wazdan-beach-party-hot": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/beach-party-hot",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 20 lines.",
  },
  "wazdan-bell-wizard": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/bell-wizard",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 9 lines; Wazdan also describes it as a 5-reel, 9-payline video slot.",
  },
  "wazdan-black-hawk": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/black-hawk",
    verifiedAt,
    evidence: "Official Game Info lists 4 reels and 54 lines.",
  },
  "wazdan-black-hawk-deluxe": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/black-hawk-deluxe",
    verifiedAt,
    evidence: "Official page describes Black Hawk Deluxe as a 4-reel, 54-payline slot and Game Info lists 54 lines.",
  },
  "wazdan-black-horse": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/black-horse",
    verifiedAt,
    evidence: "Official page describes a classic 3-reel, 5-payline slot and Game Info lists 5 lines.",
  },
  "wazdan-black-horse-deluxe": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/black-horse-deluxe",
    verifiedAt,
    evidence: "Official Game Info lists 6 reels and 20 lines and the description explicitly refers to 20 paylines.",
  },
  "wazdan-book-of-faith": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/book-of-faith",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 10 lines.",
  },
  "wazdan-burning-reels": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/burning-reels",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 20 lines; the detailed description also states 20 paylines.",
  },
  "wazdan-burning-stars": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/burning-stars",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 20 lines.",
  },
  "wazdan-captain-shark": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/captain-shark",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 20 lines.",
  },
  "wazdan-colin-the-cat": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/colin-the-cat",
    verifiedAt,
    evidence: "Official Game Info lists 4 reels and 10 lines; the detailed description also states 10 paylines.",
  },
  "wazdan-corrida-romance": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/corrida-romance",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 20 lines.",
  },
  "wazdan-corrida-romance-deluxe": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/corrida-romance-deluxe",
    verifiedAt,
    evidence: "Official page describes a 5-reel, 20-payline slot and Game Info lists 20 lines.",
  },
  "wazdan-crazy-cars": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/crazy-cars",
    verifiedAt,
    evidence: "Official Game Info lists 5 reels and 5 lines.",
  },
  "wazdan-criss-cross-81": {
    mechanics: ["Линии"],
    source: "https://wazdan.com/games/criss-cross-81",
    verifiedAt,
    evidence: "Official Game Info lists 4 reels and 81 lines.",
  },
  "wazdan-cube-mania-deluxe": {
    mechanics: ["Линии", "Каскады"],
    source: "https://wazdan.com/games/cube-mania-deluxe",
    verifiedAt,
    evidence: "Official Game Info lists 4 reels and 9 lines, while the official features explicitly list Cascading Reels and describe winning symbols disappearing before new symbols fall into place.",
  },
  "wazdan-9-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-coins", verifiedAt, evidence: "Official page confirms nine independent reels with no base-game payouts, Cash Infinity and Hold the Jackpot with a 500x Grand Jackpot." },
  "wazdan-9-coins-1000-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-coins-1000-edition", verifiedAt, evidence: "Official page confirms nine independent reels without base-game pays, Cash Infinity and Hold the Jackpot, and a 1000x Grand Jackpot." },
  "wazdan-9-coins-extremely-light": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-coins-extremely-light", verifiedAt, evidence: "Official page confirms an optimized lightweight nine-reel version with Cash Infinity and Hold the Jackpot and a 500x Grand Jackpot." },
  "wazdan-9-coins-grand-diamond-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-coins-grand-diamond-edition", verifiedAt, evidence: "Official page confirms nine reels with Cash Infinity, Cash Out, Chance Level and a 5000x Grand Jackpot." },
  "wazdan-9-coins-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-coins-grand-gold-edition", verifiedAt, evidence: "Official page confirms nine reels with Cash Infinity and Hold the Jackpot featuring a 1500x Grand Jackpot." },
  "wazdan-9-coins-grand-platinum-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-coins-grand-platinum-edition", verifiedAt, evidence: "Official page confirms nine reels with Chance Level, Cash Out, Cash Infinity and a 2500x Grand Jackpot." },
  "wazdan-9-lions": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-lions", verifiedAt, evidence: "Official page identifies nine independent reels and separate Lions Bonus and Dragons Bonus, as well as Block Symbols Mode." },
  "wazdan-9-lions-hold-the-jackpot": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/9-lions-hold-the-jackpot", verifiedAt, evidence: "Official page confirms Cash Infinity, Bonus Matrix, Hold the Jackpot and a separate 9 Lions Bonus with One Click 2 Grand." },
  "wazdan-beauty-fruity": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/beauty-fruity", verifiedAt, evidence: "Official page identifies nine independent positions with wins from four identical symbols anywhere, Love Spins, nine Free Spins with x3 and Block Symbols." },
  "wazdan-bells-of-fortune": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/bells-of-fortune", verifiedAt, evidence: "Official page confirms 16 independent reels, Hold the Jackpot after four central bonus symbols, a separate Bells of Fortune Bonus Game, Cash Infinity and Chance Level." },

  "wazdan-black-horse-cash-out-edition": { mechanics: ["Линии","Сбор символов"], source: "https://wazdan.com/games/black-horse-cash-out-edition", verifiedAt, evidence: "Official page confirms 5 reels, 20 lines, Cash Out, Sticky Cash Out, Jackpot Coins and Chance Level." },
  "wazdan-bumba-meu-boi-coin": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/bumba-meu-boi-coin", verifiedAt, evidence: "Official page confirms one main reel and three upper mini reels, Magic Coin, back matrix, Extra Life and Boi Da Fortuna Bonus." },
  "wazdan-burning-stars-3": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/burning-stars-3", verifiedAt, evidence: "Official page confirms nine independent reels in a 3x3 matrix and Hold the Jackpot triggered by three Bonus stars, with three resetting respins." },
  "wazdan-burning-sun": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/burning-sun", verifiedAt, evidence: "Official page confirms sixteen-reel 4x4 grid, Sticky to Infinity and Hold the Jackpot triggered by six Bonus symbols." },
  "wazdan-burning-sun-extremely-light": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/burning-sun-extremely-light", verifiedAt, evidence: "Official release confirms lighter graphics with the original Burning Sun 4x4 and its Sticky to Infinity and Hold the Jackpot features preserved." },
  "wazdan-butterfly-lovers": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/butterfly-lovers", verifiedAt, evidence: "Official page confirms 16 separate reels and wins from eight identical symbols; Liang Shanbo Bonus Spins, Magic Sack and Zhu Yingtai Free Spins are distinct." },
  "wazdan-cash-grotto": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/cash-grotto", verifiedAt, evidence: "Official page confirms 24 reels, Hold the Jackpot triggered by four central Bonus symbols, Moving Cash Out, Cash Infinity and Sticky to Infinity." },
  "wazdan-demon-jack-27": { mechanics: ["Линии"], source: "https://wazdan.com/games/demon-jack-27", verifiedAt: "2026-10-08", evidence: "Official Game Info gives 3 reels/27 lines, RTP 96.09%, 1104x max, high volatility, 2016-02-11; features Wild and x3 Wall Multiplier." },
  "wazdan-dino-reels-81": { mechanics: ["Линии"], source: "https://wazdan.com/games/dino-reels-81", verifiedAt: "2026-10-08", evidence: "Official Game Info lists 4 reels, 7 lines, 96.44%, 691x, medium-high, 2016-12-01; long official description calls it 81-payline and Wild feature increases to 81 lines. Conflict explicitly preserved." },
  "wazdan-double-tigers": { mechanics: ["Линии"], source: "https://wazdan.com/games/double-tigers", verifiedAt: "2026-10-08", evidence: "Official Game Info says 3 reels/8 lines, 96.43%, 40x, low-medium, 2018-08-05. Long first-party text says 5 reels/8 paylines: unresolved internal reel-count conflict recorded." },
  "wazdan-draculas-castle": { mechanics: ["Линии"], source: "https://wazdan.com/games/draculas-castle", verifiedAt: "2026-10-08", evidence: "Official Game Info: 5 reels/5 lines, 96.56 RTP, 1000x, high, 2017-12-27; article confirms expanding Dracula Wild, x3/x4/x5 wall and goblet gamble." },
  "wazdan-dragons-lucky-8": { mechanics: ["Линии"], source: "https://wazdan.com/games/dragons-lucky-8", verifiedAt: "2026-10-08", evidence: "Official Game Info lists 6 reels/20 lines, 96.26%, 1150x, low-medium, 2019-08-20; long first-party description confirms sticky variable x1/x2/x4/x8 multiplier, free spins and Wild." },
  "wazdan-dwarfs-fortune": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/dwarfs-fortune", verifiedAt: "2026-10-08", evidence: "Official Game Info: 5 reels/0 lines, RTP 96.16%, max 2500x, high, 2022-03-09. Full Wazdan description: six Bonus trigger Hold the Jackpot, twenty positions grant Grand, Increasing Value Sticky Bonus up to nine respins." },
  "wazdan-easter-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/easter-coins", verifiedAt: "2026-10-08", evidence: "Wazdan game page explicitly lists 25 reels / 0 ways, RTP 96.17%, max 2000x, high volatility, 2026-03-20, and Hold the Jackpot, Cash Infinity, Sticky to Infinity, Cluster Collector." },
  "wazdan-eggs-of-fortune": { mechanics: ["Линии","Сбор символов"], source: "https://wazdan.com/games/eggs-of-fortune", verifiedAt: "2026-10-08", evidence: "Official page lists 5 reels/5 lines, 96.12%, max 5000x, extreme, 2025-08-07. Intro confirms two base-game Cash Out features, Countdown Boosters and Collector in Free Spins and Chance Level x2/x5/x10." },
  "wazdan-fenix-play": { mechanics: ["Линии"], source: "https://wazdan.com/games/fenix-play", verifiedAt: "2026-10-08", evidence: "Official game page is titled Fenix Play; catalog name Fenix. Game Info: 3 reels/5 lines, 96.44 RTP, max 75x, medium, 2014-09-08. Lists Extra Drawings and Gamble Feature." },
  "wazdan-fenix-play-27": { mechanics: ["Линии"], source: "https://wazdan.com/games/fenix-play-27", verifiedAt: "2026-10-08", evidence: "Official Game Info lists 3 reels/27 lines, RTP 96.25%, max 748x, high; no release-date field. Wazdan describes phoenix Wild and x3 wall." },
  "wazdan-fenix-play-27-deluxe": { mechanics: ["Линии"], source: "https://wazdan.com/games/fenix-play-27-deluxe", verifiedAt: "2026-10-08", evidence: "Official Game Info 3/27, 96.25%, 748x, high, 2017-09-15; long official description confirms cross paylines, Wild phoenix, x3 Wall and egg gamble." },
  "wazdan-fenix-play-deluxe": { mechanics: ["Линии"], source: "https://wazdan.com/games/fenix-play-deluxe", verifiedAt: "2026-10-08", evidence: "Official Game Info 3 reels/5 lines, 96.44%, 75x, medium, 2017-09-15. Wazdan details refreshed design, 7 possible doubles in Gamble and Volatility Levels." },
  "wazdan-fire-bird": { mechanics: ["Линии"], source: "https://wazdan.com/games/fire-bird", verifiedAt: "2026-10-08", evidence: "Official Wazdan Game Info: 3 reels, 5 lines, RTP 96.05%, 72x, standard; official list contains Bonus Symbol, page copy describes Gamble. Release date not listed." },
  "wazdan-fishermans-luck": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/fishermans-luck", verifiedAt: "2026-10-08", evidence: "Official Game Info: 10 reels/0 lines, 96.13%, 2500x, medium, 2026-03-05; source explicitly describes Gainer up to ten spins, Free Spins Gain to Infinity, top Cash Out and Chance Level x2/5/10." },
  "wazdan-football-mania": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/football-mania", verifiedAt: "2026-10-08", evidence: "Official Game Info lists 9 reels/0 lines, RTP 96.59%, max 1000x, high; feature list includes Block Symbols Mode, Football Bonus and Football Lottery Bonus. Release date omitted." },
  "wazdan-football-mania-deluxe": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/football-mania-deluxe", verifiedAt: "2026-10-08", evidence: "Official Game Info 9 reels/0 lines, 96.59%, max 1000x, high, 2018-05-30. Detailed first-party copy describes revamped version, Football Bonus and Football Lottery selection up to 1000x." },
  "wazdan-fortune-reels": { mechanics: ["Способы","Каскады","Сбор символов"], source: "https://wazdan.com/games/fortune-reels", verifiedAt: "2026-10-08", evidence: "Official Game Info 6 reels / 6 Ways to Win, RTP 96.12%, 2100x, high, 2021-07-27; game text explicitly says 46,656 ways and Cascading Reels, expanding Wild and Sack up to five bonus values. Different representations preserved." },
  "wazdan-fruit-fiesta": { mechanics: ["Линии"], source: "https://wazdan.com/games/fruit-fiesta", verifiedAt: "2026-10-08", evidence: "Official Wazdan Game Info: 5 reels/20 lines, 96.32%, 730x, high, 2017-12-01. Official description: chilli Wild, sheriff-star Scatter pays for 3+ anywhere and piñata Gamble." },
  "wazdan-fruit-mania": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/fruit-mania", verifiedAt: "2026-10-08", evidence: "Official Game Info: 9 reels/0 lines, 96.59%, 1000x, high, 2014-09-08; official page details Diamond Matrix full -> 9 spins with locked diamonds, Block Symbols and three central Lotto symbols." },
  "wazdan-fruit-mania-deluxe": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/fruit-mania-deluxe", verifiedAt: "2026-10-09", evidence: "Official 9 reels/0 lines, 96.59% RTP, max 1000x, 2018-06-20; official detailed description confirms 3x3 horizontal/vertical pays, diamond matrix for 9 bonus spins, Lotto gift boxes and block symbols." },
  "wazdan-fruits-go-bananas": { mechanics: ["Линии"], source: "https://wazdan.com/games/fruits-go-bananas", verifiedAt: "2026-10-09", evidence: "Official Game Info: 5 reels/5 lines, 96.34%, 850x, medium, 2018-09-11; pineapple Wild x2, Random Wilds, banana Scatter 3/4/5 => 10/20/30 Free Spins." },
  "wazdan-gem-splitter": { mechanics: ["Способы"], source: "https://wazdan.com/games/gem-splitter", verifiedAt: "2026-10-09", evidence: "Official Game Info: 5 reels/243 ways, RTP 96.27%, max 9000x, high, 2021-01-19; 5 variants of Symbol Splitter, Scatter, Wild, Free Spins and Buy Feature." },
  "wazdan-golden-sphinx": { mechanics: ["Линии"], source: "https://wazdan.com/games/golden-sphinx", verifiedAt: "2026-10-09", evidence: "Official Game Info: 5 reels/20 lines, RTP 96.48%, max 4650x, high, 2014-08-09; x2 Wild sphinx and 15 Free Spins with x3 multiplier." },
  "wazdan-good-luck-40": { mechanics: ["Линии"], source: "https://wazdan.com/games/good-luck-40", verifiedAt: "2026-10-09", evidence: "Official Game Info: 5 reels/40 lines, RTP 96.62%, max 2000x, low, 2014-08-09; lists Wild, Scatter and Free Spins without a specific spin count." },
  "wazdan-great-book-of-magic": { mechanics: ["Линии"], source: "https://wazdan.com/games/great-book-of-magic", verifiedAt: "2026-10-09", evidence: "Official Game Info 5 reels/20 lines, RTP 96.47%, 5150x max, high, 2018-05-30. Free Spins with Expanding Bonus Symbol and Scatter are official game features." },
  "wazdan-great-book-of-magic-deluxe": { mechanics: ["Линии"], source: "https://wazdan.com/games/great-book-of-magic-deluxe", verifiedAt: "2026-10-09", evidence: "Official Deluxe page 5 reels/20 lines, 96.47%, 5150x, high, 2018-05-30; detailed official copy confirms 3 books => 10 Free Spins, expanding bonus symbol, scatters act as Wild in free spins." },
  "wazdan-haunted-coins-x1000": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/haunted-coins-x1000", verifiedAt: "2026-10-09", evidence: "Official page: 16 reels/0 ways, 96.18%, max 1000x, high, 2025-10-21, Hold the Jackpot, Cash Infinity and Chance Level x2/x4/x6." },
  "wazdan-haunted-hospital": { mechanics: ["Линии"], source: "https://wazdan.com/games/haunted-hospital", verifiedAt: "2026-10-09", evidence: "Official Game Info 3 reels/27 lines, RTP 96.49%, max 820x, high, 2017-05-02; separate listed features: Wild, Scatter, Free Spins and Mystery Bonus." },
  "wazdan-highschool-manga": { mechanics: ["Линии"], source: "https://wazdan.com/games/highschool-manga", verifiedAt: "2026-10-09", evidence: "Official Game Info 3 reels/5 lines, 96.41%, max 320x, 2016-01-12, adjustable Low/Standard/High; x2 Wall Multiplier triggered by 3x3 wall of four applicable symbols." },
  "wazdan-highway-to-hell": { mechanics: ["Линии"], source: "https://wazdan.com/games/highway-to-hell", verifiedAt: "2026-10-09", evidence: "Official 5 reels/5 lines, RTP 96.18%, max 2500x, low-medium, official expansion-truck Wild and x3/x4/x5 Wall Multiplier." },
  "wazdan-highway-to-hell-deluxe": { mechanics: ["Линии"], source: "https://wazdan.com/games/highway-to-hell-deluxe", verifiedAt: "2026-10-09", evidence: "Official Deluxe Game Info 5 reels/5 lines, 96.56%, max 1000x, high, 2018-07-13; 9/10/J/Q x3/x4/x5 wall, expanding lorry Wild." },
  "wazdan-hot-777-deluxe": { mechanics: ["Линии"], source: "https://wazdan.com/games/hot-777-deluxe", verifiedAt: "2026-10-09", evidence: "Official Deluxe 3 reels/5 lines, 96.47%, 200x, medium, 2018-10-10. Detail text: each Hot 7 grants bullet; ten bullets plus Hot 7 trigger 10 Hot Spins with sticky Hot 7." },
  "wazdan-hot-party-deluxe": { mechanics: ["Линии"], source: "https://wazdan.com/games/hot-party-deluxe", verifiedAt: "2026-10-09", evidence: "Official Deluxe 5 reels/20 lines, 96.42%, max 305x, low-medium, 2018-06-27. Three or more beach-ball scatters pay anywhere; Gamble hides drink behind two leaves." },
  "wazdan-hot-slot-777-crown-extremely-light": { mechanics: ["Линии"], source: "https://wazdan.com/games/hot-slot-777-crown-extremely-light", verifiedAt: "2026-10-09", evidence: "Official Game Info 5 reels/20 lines, 96.42%, max 305x, low-medium, 2024-04-03; Scatter and Extremely Light energy/data savings." },
  "wazdan-hot-slot-diamond-coins": { mechanics: ["Линии","Сбор символов"], source: "https://wazdan.com/games/hot-slot-diamond-coins", verifiedAt: "2026-10-09", evidence: "Official Game Info 15 reels/2 lines, 96.18%, max 3000x, high, 2026-04-09; Cash Infinity red sticky symbols, Hold the Jackpot and unique Hot Slot symbols on two lines." },
  "wazdan-hot-slot-magic-pearls": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/hot-slot-magic-pearls", verifiedAt: "2026-10-09", evidence: "Official Game Info 25 reels/0 lines, RTP 96.19%, max 2500x, high, 2022-11-10, Hold the Jackpot, Buy Feature, Wild." },
  "wazdan-hot-slot-mystery-jackpot-joker": { mechanics: ["Линии","Сбор символов"], source: "https://wazdan.com/games/hot-slot-mystery-jackpot-joker", verifiedAt: "2026-10-09", evidence: "Official Game Info 3 reels/5 lines, 96.11%, max 1000x, high, 2022-12-15, Mystery Joker Jackpot Game, Magic Respin, Joker Hat Wild, star Scatter." },
  "wazdan-hot-slot-platinum-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/hot-slot-platinum-coins", verifiedAt: "2026-10-09", evidence: "Official Game Info 15 reels/2 Ways to Win, RTP 96.15%, max 2500x, high, 2026-02-27; Cash Infinity, Hold the Jackpot, Chance Level, Buy Feature." },
  "wazdan-hungry-shark": { mechanics: ["Линии"], source: "https://wazdan.com/games/hungry-shark", verifiedAt: "2026-10-09", evidence: "Official Game Info 5 reels/20 lines, RTP 96.47%, max 5150x, high, 2017-02-05; Free Spins with Expanding Bonus Symbol, Scatter and Wild." },
  "wazdan-in-the-forest": { mechanics: ["Линии"], source: "https://wazdan.com/games/in-the-forest", verifiedAt: "2026-10-09", evidence: "Official Game Info 5 reels/20 lines, 96.63% RTP, max 1250x, low, 2016-01-12; Free Spins with x2 Multiplier Symbol, Wild and Scatter." },
  "wazdan-infinity-hero": { mechanics: ["Линии"], source: "https://wazdan.com/games/infinity-hero", verifiedAt: "2026-10-09", evidence: "Official Wazdan page 6/20, RTP 96.24%, max 13000x, 2020-07-28; 3 scatters -> 10 free spins with increasing infinite multiplier, and 3/5/7 added spins." },
  "wazdan-jack-on-hold": { mechanics: ["Линии"], source: "https://wazdan.com/games/jack-on-hold", verifiedAt: "2026-10-09", evidence: "Official Game Info 3 reels/5 lines, RTP 96.4%, max 500x, low-medium, 2016-02-11; Respin, Wild and x2 Wall Multiplier." },
  "wazdan-jacks-ride": { mechanics: ["Линии"], source: "https://wazdan.com/games/jacks-ride", verifiedAt: "2026-10-09", evidence: "Official 3 reels/27 paylines, 96.4%, 81x max, low-medium, 2017-09-15; Nudge reverses a reel to form winning combinations; Gamble doubles up to seven times." },
  "wazdan-jackpot-builders": { mechanics: ["Линии","Каскады"], source: "https://wazdan.com/games/jackpot-builders", verifiedAt: "2026-10-09", evidence: "Official Game Info 4 reels/9 lines, RTP 96.59%, max 250x, medium, 2017-02-05; Cascading Reels, up to 30 Free Spins, Mystery Bonus, Wild x2 and x2 Wall Multiplier." },
  "wazdan-joker-explosion": { mechanics: ["Линии"], source: "https://wazdan.com/games/joker-explosion", verifiedAt: "2026-10-09", evidence: "Official Game Info 4/7, RTP 96.5%, max 2350x, low-medium; top promotional paragraph says 2300x. Three scatters trigger Free Spins; Wild excludes dynamite and Respin listed." },
  "wazdan-juicy-reels": { mechanics: ["Линии"], source: "https://wazdan.com/games/juicy-reels", verifiedAt: "2026-10-09", evidence: "Official Game Info 6 reels/20 lines, RTP 96.49%, max 750x, low, release 2019-03-26; 3/4/5/6 scatters grant 15/20/25/30 Free Spins at 3x." },
  "wazdan-jumping-fruits": { mechanics: ["Линии"], source: "https://wazdan.com/games/jumping-fruits", verifiedAt: "2026-10-09", evidence: "Official Wazdan page 3/27, 96.4%, max 81x, low-medium, 2017-09-15; Nudge reverses non-winning reels and leaf/larva Gamble up to 7 rounds." },
  "wazdan-kick-off": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/kick-off", verifiedAt: "2026-10-09", evidence: "Official Wazdan page says no reels/paylines, 96.42% RTP, max 440x, standard, 2016-06-03; Matrix Table 3 horizontal -> 1 penalty, five vertical -> five shots; three matching footballs pay." },
  "wazdan-larry-the-leprechaun": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/larry-the-leprechaun", verifiedAt: "2026-10-09", evidence: "Official Game Info 16 reels/0 paylines, RTP 96.47%, max 350x, low-medium, 2019-07-17; game text: 8 identical symbols anywhere pay; distinct Gold, Silver, Magic Sack bonus triggers." },
  "wazdan-los-muertos": { mechanics: ["Линии"], source: "https://wazdan.com/games/los-muertos", verifiedAt: "2026-10-09", evidence: "Official Los Muertos 5 reels/40 lines, RTP 96.29%, max 850x, low-medium, release 2018-10-24; Giant Symbols 2x2/3x3, Bonus Slot, 3 Free Spin icons -> 6 Free Spins plus extras." },
  "wazdan-los-muertos-ii": { mechanics: ["Линии"], source: "https://wazdan.com/games/los-muertos-ii", verifiedAt: "2026-10-09", evidence: "Official Los Muertos II 3/5, RTP 96.41%, max 40x, low-medium, 2023-10-19; Special Symbol on low-value only; Gamble up to 7 doubles. Does not inherit original giant bonus." },
  "wazdan-lost-treasure": { mechanics: ["Линии"], source: "https://wazdan.com/games/lost-treasure", verifiedAt: "2026-10-09", evidence: "Official 5/20, RTP 96.13%, max 3500x, low-medium, 2014-08-09; Wild treasure hunter x2 and 15 Free Spins at x3." },
  "wazdan-magic-eggs": { mechanics: ["Линии"], source: "https://wazdan.com/games/magic-eggs", verifiedAt: "2026-10-09", evidence: "Official Magic Eggs 3 reels/5 lines, RTP 96.41%, max 40x, low-medium, 2022-03-29; Special Easter Bunny symbol only over four low-value symbols; Gamble up to 7." },
  "wazdan-magic-fruit-cherries": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/magic-fruit-cherries", verifiedAt: "2026-10-09", evidence: "Official Magic Fruit$: Cherries Game Info 16 reels/0 lines, RTP 96.13%, max 500x, medium, release 2026-07-30; Cash Out up to 15 spins, Cash Infinity until bonus ends, Chance Level and Buy Feature." },
  "wazdan-magic-fruit-oranges": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/magic-fruit-oranges", verifiedAt: "2026-10-09", evidence: "Official Wazdan release 2026-03-26 and game page: 9 reels/0 lines, 96.14%, max 100x, low-medium; Cash Out stays 5 spins, Cash Infinity, Hold the Jackpot and Chance Level x2/x4/x6." },
  "wazdan-magic-hot": { mechanics: ["Линии"], source: "https://wazdan.com/games/magic-hot", verifiedAt: "2026-10-09", evidence: "Official Magic Hot 3 reels/5 lines, RTP 96.35%, max 1000x, low-medium, 2014-09-08. Feature list only Gamble, no Wild/Scatter or Free Spins." },
  "wazdan-magic-hot-4": { mechanics: ["Линии"], source: "https://wazdan.com/games/magic-hot-4", verifiedAt: "2026-10-09", evidence: "Official Magic Hot 4 Game Info 4/10, 96.1%, max 260x, medium, 2014-09-08; Bonus Symbol and Gamble." },
  "wazdan-magic-hot-4-deluxe": { mechanics: ["Линии"], source: "https://wazdan.com/games/magic-hot-4-deluxe", verifiedAt: "2026-10-09", evidence: "Official Deluxe 4 reels/10 lines, RTP 96.1%, max 260x, medium, 2017-12-01; Wizard Bonus Symbol, 4 marked symbols and two-box Gamble." },
  "wazdan-magic-of-the-ring": { mechanics: ["Линии"], source: "https://wazdan.com/games/magic-of-the-ring", verifiedAt: "2026-10-09", evidence: "Official Ring 5 reels/20 lines, RTP 96.47%, max 5150x, high, 2013-12-17; 3/4/5 scatter trigger 10 Free Spins with expanding Bonus Symbol." },
  "wazdan-magic-of-the-ring-deluxe": { mechanics: ["Линии"], source: "https://wazdan.com/games/magic-of-the-ring-deluxe", verifiedAt: "2026-10-09", evidence: "Official Deluxe Game Info 5 reels/20 lines, 96.47%, 5150x, high, 2018-06-13; long marketing text incorrectly says 10 lines; three scatters trigger 10 spins, Expanding Bonus, retrigger and Scatter Wild." },
  "wazdan-magic-stars": { mechanics: ["Линии"], source: "https://wazdan.com/games/magic-stars", verifiedAt: "2026-10-09", evidence: "Official Magic Stars 3 reels/5 lines, 96.25%, max 40x, low-medium, 2014-08-09; Bonus Symbol and Gamble up to seven doubles." },
  "wazdan-magic-stars-9": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/magic-stars-9", verifiedAt: "2026-10-09", evidence: "Official Magic Stars 9: 9 reels/0 lines, RTP 96.21%, max 10500x, high, 2019-11-14; central-row triples initiate distinct 9 Free Spins Infinite Multiplier and 9 Star Spins, Block Symbols." },
  "wazdan-mighty-crown-empire-of-gold": { mechanics: ["Линии"], source: "https://wazdan.com/games/mighty-crown-empire-of-gold", verifiedAt: "2026-10-09", evidence: "Official 3 reels/5 lines, RTP 96.13%, max 1500x, very high, 2026-08-06. Three Bonus -> Empire Bonus, Wilds x1 to x5 up to summed x15." },
  "wazdan-mighty-crown-legacy-of-mars": { mechanics: ["Линии"], source: "https://wazdan.com/games/mighty-crown-legacy-of-mars", verifiedAt: "2026-10-09", evidence: "Official 5/10, RTP 96.15%, max 3000x, medium, 2025-10-29. Scatter Respin, jackpot for 2/3/4/5 Crown scatters, or full screen of 15 Sevens." },
  "wazdan-mighty-fish-blue-marlin": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/mighty-fish-blue-marlin", verifiedAt: "2026-10-09", evidence: "Official Game Info 5 reels/0 lines, RTP 96.18%, 2500x, very high, 2024-02-27; Cash Out, Trawler Cash Out, Collect to Infinity, Free Spins and Chance Level." },
  "wazdan-mighty-symbols-crowns": { mechanics: ["Линии"], source: "https://wazdan.com/games/mighty-symbols-crowns", verifiedAt: "2026-10-09", evidence: "Official Game Info 5 reels/10 lines, RTP 96.15%, max 2500x, low-medium, 2023-08-24. Giant Crown, Free Spins with sticky/walking giant crown and random multiplier." },
  "wazdan-mighty-symbols-diamonds": { mechanics: ["Линии"], source: "https://wazdan.com/games/mighty-symbols-diamonds", verifiedAt: "2026-10-09", evidence: "Official Game Info 5/10, RTP 96.13%, max 2500x, low-medium, 2023-10-30; Giant Diamond Wild, Free Spins with Walking Giant Diamond and multipliers up to x5." },
  "wazdan-mighty-symbols-jokers": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/mighty-symbols-jokers", verifiedAt: "2026-10-09", evidence: "Official 15 reels/0 lines, RTP 96.14%, max 750x, high, 2024-10-03; Hold the Jackpot, Jokers Rampage, Cash Infinity, Sticky to Infinity and Mystery Multiplier." },
  "wazdan-mighty-symbols-sevens": { mechanics: ["Линии","Сбор символов"], source: "https://wazdan.com/games/mighty-symbols-sevens", verifiedAt: "2026-10-09", evidence: "Official Game Info 5/10, RTP 96.17%, max 2000x, low-medium, 2024-04-09; Mighty Sevens Wild and Hold the Jackpot, Buy Feature, Chance Level." },
  "wazdan-mighty-wild-gorilla": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/mighty-wild-gorilla", verifiedAt: "2026-10-09", evidence: "Official Game Info 8 reels/0 lines, RTP 96.2%, 2500x, very high, 2026-01-07; 16-position Hold the Jackpot three respins, 10 Free Spins with persistent Collectors, Cash Out, x2/x5/x10 Chance Level." },
  "wazdan-mighty-wild-jaguar": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/mighty-wild-jaguar", verifiedAt: "2026-10-09", evidence: "Official Game Info 15/0, RTP 96.14%, max 750x, high, 2025-01-29. Wild Rampage, Hold the Jackpot, Cash Infinity, Sticky to Infinity, Mystery Multiplier." },
  "wazdan-mighty-wild-panther-grand-gold-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/mighty-wild-panther-grand-gold-edition", verifiedAt: "2026-10-09", evidence: "Official Game Info 15/0, RTP 96.15%, 1500x, high, 2024-04-26; Wild Rampage multiplying jackpot awards from Panther Mystery, Hold the Jackpot, Cash Infinity." },
  "wazdan-mighty-wild-panther-grand-platinum-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/mighty-wild-panther-grand-platinum-edition", verifiedAt: "2026-10-09", evidence: "Official Game Info 15/0, RTP 96.12%, max 2500x, high, 2024-06-26; Platinum adds Cash Out, Hold the Jackpot, Wild Rampage and Cash Infinity." },
  "wazdan-moon-of-fortune": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/moon-of-fortune", verifiedAt: "2026-10-09", evidence: "Official 16 reels/0 lines, RTP 96.12%, max 1500x, high, 2023-07-11; Sticky to Infinity, Hold the Jackpot, Collector, Chance Level x2/x4/x6." },
  "wazdan-mystery-kingdom-mystery-bells": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/mystery-kingdom-mystery-bells", verifiedAt: "2026-10-09", evidence: "Official Game Info 12 reels/0 lines, RTP 96.13%, max 750x, high, 2023-03-30; only bonus pays, One Click to the Grand Jackpot, Cash Infinity and Hold the Jackpot." },
  "wazdan-neon-city": { mechanics: ["Линии"], source: "https://wazdan.com/games/neon-city", verifiedAt: "2026-10-09", evidence: "Official Neon City 5 reels/20 lines, RTP 96.25%, max 1250x, low-medium, 2019-12-10; Free Spins with Increasing Multiplier, Mega Spins, Scatter and Wild." },
  "wazdan-one-coin": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/one-coin", verifiedAt: "2026-10-09", evidence: "Official Wazdan 1 reel/0 lines, 96.17%, 500x, medium, 2024-10-10; Hold the Jackpot, Mystery Multiplier up to 10x, Chance Level." },
  "wazdan-ox-coin": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/ox-coin", verifiedAt: "2026-10-09", evidence: "Official Ox Coin 17 reels/0 lines, RTP 96.21%, max 2500x, high, 2026-05-28; Magic Coin, 25-reel Ox Bonus, up to 3 Extra Lives." },
  "wazdan-power-of-gods-egypt": { mechanics: ["Способы"], source: "https://wazdan.com/games/power-of-gods-egypt", verifiedAt: "2026-10-09", evidence: "Official Wazdan Egypt 5 reels/243 ways, RTP 96.19%, max 8000x, high, 2020-10-14; Ra Spins plus Bastet, Isis and Sobek Free Spins." },
  "wazdan-power-of-gods-hades": { mechanics: ["Способы","Каскады","Сбор символов"], source: "https://wazdan.com/games/power-of-gods-hades", verifiedAt: "2026-10-09", evidence: "Official Hades 5 reels/243 ways, RTP 96.14%, max 5000x, high; Cascading, sticky Bonus 5 respins, Hold the Jackpot, Hades Wild." },
  "wazdan-power-of-gods-medusa": { mechanics: ["Линии","Сбор символов"], source: "https://wazdan.com/games/power-of-gods-medusa", verifiedAt: "2026-10-09", evidence: "Official Medusa 5 reels/10 paylines, RTP 96.18%, max 2500x, high, 2021-12-14; Medusa Wild, Sticky Bonus, Hold the Jackpot." },
  "wazdan-power-of-gods-medusa-extremely-light": { mechanics: ["Линии","Сбор символов"], source: "https://wazdan.com/games/power-of-gods-medusa-extremely-light", verifiedAt: "2026-10-09", evidence: "Official Medusa Extremely Light 5/10, RTP 96.18%, max 2500x, high, 2024-07-03; sticky up to 9 respins, mobile-light Hold the Jackpot." },
  "wazdan-power-of-gods-the-pantheon": { mechanics: ["Линии"], source: "https://wazdan.com/games/power-of-gods-the-pantheon", verifiedAt: "2026-10-09", evidence: "Official Pantheon 5/20, RTP 96.2%, max 1450x, medium, 2019-10-17; Kraken 10 spins with moving reels, Zeus 5 with extra Wild, Aphrodite cascades." },
  "wazdan-power-of-gods-valhalla": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/power-of-gods-valhalla", verifiedAt: "2026-10-09", evidence: "Official Valhalla Wazdan: Hold the Jackpot, sticky 3/4/5 Bonus and 2145x maximum; Buy Feature." },
  "wazdan-power-of-gods-valhalla-extremely-light": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/power-of-gods-valhalla-extremely-light", verifiedAt: "2026-10-09", evidence: "Official Valhalla Extremely Light Game Info 16/0, RTP 96.23%, Max Win 2145x, high, 2024-05-23; marketing mentions Grand 1000x; sticky bonus." },
  "wazdan-power-of-sun-svarog": { mechanics: ["Способы","Сбор символов"], source: "https://wazdan.com/games/power-of-sun-svarog", verifiedAt: "2026-10-09", evidence: "Official Wazdan Svarog page lists game-specific sun-themed mechanics and first-party game info; avoid deriving unverified multipliers." },
  "wazdan-prosperity-pearls": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/prosperity-pearls", verifiedAt: "2026-10-09", evidence: "Official first-party Prosperity Pearls Wazdan page confirms pearl theme and bonus features." },
  "wazdan-santas-gifts-frenzy": { mechanics: ["Линии","Сбор символов"], source: "https://wazdan.com/games/santas-gifts-frenzy", verifiedAt: "2026-10-09", evidence: "Official Santa's Gifts Frenzy Wazdan game information and game-specific gift features." },
  "wazdan-mighty-wild-panther-grand-diamond-edition": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/mighty-wild-panther-grand-diamond-edition", verifiedAt: "2026-10-09", evidence: "Official Wazdan Diamond release 2024-08-13: 5x3 grid, two distinct bonus modes, Cash Out up to 20 spins, six bonus symbols, Grand 5000x, Chance Level 2/5/10." },
  "wazdan-sizzling-eggs": { mechanics: ["Линии","Сбор символов"], source: "https://wazdan.com/games/sizzling-eggs", verifiedAt: "2026-10-09", evidence: "Official Sizzling Eggs Game Info: 5/5, RTP 96.12%, max 2500x, very high, 2022-06-08; Collector, Countdown and Collect to Infinity in Free Spins." },
  "wazdan-sizzling-eggs-extremely-light": { mechanics: ["Линии","Сбор символов"], source: "https://wazdan.com/games/sizzling-eggs-extremely-light", verifiedAt: "2026-10-09", evidence: "Official Wazdan Extremely Light Game Info: 5/5, RTP 96.12%, max 2500x, very high, 2023-10-26, official news confirms same mechanics with lower resource usage." },
  "wazdan-sizzling-eggs-grand-gold-edition": { mechanics: ["Линии","Сбор символов"], source: "https://wazdan.com/games/sizzling-eggs-grand-gold-edition", verifiedAt: "2026-10-09", evidence: "Official Wazdan Grand Gold Game Info: 5/5, RTP 96.16%, max 3000x, extreme, 2025-04-30; Collect to Infinity, Free Spins, Chance Level." },
  "wazdan-sizzling-eggs-grand-platinum-edition": { mechanics: ["Линии","Сбор символов"], source: "https://wazdan.com/games/sizzling-eggs-grand-platinum-edition", verifiedAt: "2026-10-09", evidence: "Official Wazdan Platinum Game Info: 5/5, RTP 96.11%, max 4000x, extreme, 2025-06-26. Official release explicitly says new Cash Out, Collect to Infinity and Free Spins." },
  "wazdan-sizzling-kingdom-bison": { mechanics: ["Линии","Сбор символов"], source: "https://wazdan.com/games/sizzling-kingdom-bison", verifiedAt: "2026-10-09", evidence: "Official Wazdan Bison Game Info: 6/10, RTP 96.12%, max 5000x, extreme, 2022-08-25; Wild Rampage, Hold & Collect, Free Spins and Hold the Jackpot." },
  "wazdan-sizzling-moon": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/sizzling-moon", verifiedAt: "2026-10-09", evidence: "Official Sizzling Moon Game Info 16/0, RTP 96.14%, max 2500x, high, 2022-01-25; six bonus trigger, sticky nine spins, Grand 1000x vs Moon Jackpot 2500x." },
  "wazdan-slot-jam": { mechanics: ["Линии","Каскады"], source: "https://wazdan.com/games/slot-jam", verifiedAt: "2026-10-09", evidence: "Official Slot Jam 4/9, RTP 96.59%, max 570x, medium, 2018-12-12; Wild Jam x2, Mystery Basket up to 200x, Cascades, 15/30 Free Spins." },
  "wazdan-sonic-reels": { mechanics: ["Способы"], source: "https://wazdan.com/games/sonic-reels", verifiedAt: "2026-10-09", evidence: "Official Sonic Reels 6/729 ways, RTP 96.24%, max 5400x, medium, 2020-07-15; left/right speaker mechanics and scatter ladder." },
  "wazdan-space-gem": { mechanics: ["Линии"], source: "https://wazdan.com/games/space-gem", verifiedAt: "2026-10-09", evidence: "Official Space Gem Game Info 6 reels/10 lines, RTP 96.4%, max 1000x, low; expanding Wild locks for Re-Spin, no first-party Free Spins claim." },
  "wazdan-space-spins": { mechanics: ["Линии"], source: "https://wazdan.com/games/space-spins", verifiedAt: "2026-10-09", evidence: "Official Space Spins 6/40, RTP 96.66%, max 1650x, low-medium, 2019-05-09; UFO scatter 3=>10 up to 25, Space Pile full reel." },
  "wazdan-spectrum": { mechanics: ["Линии"], source: "https://wazdan.com/games/spectrum", verifiedAt: "2026-10-09", evidence: "Official Spectrum 5/10, RTP 96.53%, max 500x, low-medium, 2018-08-15; Expanding Wild and Respin with gamble." },
  "wazdan-sun-of-fortune": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/sun-of-fortune", verifiedAt: "2026-10-09", evidence: "Official Sun of Fortune 16 reels/0 lines, RTP 96.15%, max 1450x, high, 2021-04-27; 8 matching, 6 bonus trigger, 1000x Grand." },
  "wazdan-super-hot": { mechanics: ["Линии"], source: "https://wazdan.com/games/super-hot", verifiedAt: "2026-10-09", evidence: "Official Super Hot 3/5, RTP 96.16%, max 340x, medium, 2014-08-09; x2 Wall Multiplier and Unique Gamble." },
  "wazdan-telly-reels": { mechanics: ["Линии","Сбор символов"], source: "https://wazdan.com/games/telly-reels", verifiedAt: "2026-10-09", evidence: "Official Telly Reels 5/20, RTP 96.19%, max 1400x, low, 2020-10-08; three bonus families: wheel Free Spins, Telly Bonus Spins and slider Mini Telly." },
  "wazdan-throne-of-elements-platinum": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/throne-of-elements-platinum", verifiedAt: "2026-10-09", evidence: "Official Throne of Elements Platinum 25/0, RTP 96.15%, max 2500x, high, 2026-09-02; Guardian unlocks 12 reels, central/Hold trigger, timed Cash Out." },
  "wazdan-triple-star": { mechanics: ["Линии"], source: "https://wazdan.com/games/triple-star", verifiedAt: "2026-10-09", evidence: "Official Triple Star 5/20, RTP 96.28%, max 1000x, low, 2014-08-09; expanding Wild only reels 2,3,4 and one locked free Re-Spin." },
  "wazdan-turbo-play": { mechanics: ["Линии"], source: "https://wazdan.com/games/turbo-play", verifiedAt: "2026-10-09", evidence: "Official Turbo Play 3/1, RTP 96.1%, max 300x, medium-high; Block Reels mechanic, third reel Wild for five low symbols; release date omitted from Game Info." },
  "wazdan-unicorn-reels": { mechanics: ["Линии","Сбор символов"], source: "https://wazdan.com/games/unicorn-reels", verifiedAt: "2026-10-09", evidence: "Official Unicorn Reels 5/10, RTP 96.14%, max 1000x, very high, 2021-01-27; five unicorn trigger, 5x5 jackpot, 3 resetting respins, 15/20/25 reward tiers." },
  "wazdan-valentines-coins": { mechanics: ["Сбор символов"], source: "https://wazdan.com/games/valentines-coins", verifiedAt: "2026-10-09", evidence: "Official Valentine’s Coins Game Info 9/0, RTP 96.06%, max 500x, medium-high, 2026-02-03; Love the Jackpot 3x3, sticky Love Infinity and respin reset." },
  "wazdan-valhalla": { mechanics: ["Линии"], source: "https://wazdan.com/games/valhalla", verifiedAt: "2026-10-09", evidence: "Official Game Info: 4 reels /54 lines, RTP 96.47%, max 600x, medium, 2017-07-06. Both-direction payline mechanic, Valkyrie Wild and door Gamble." },
  "wazdan-vegas-hot": { mechanics: ["Линии"], source: "https://wazdan.com/games/vegas-hot", verifiedAt: "2026-10-09", evidence: "Official Game Info 3 reels/5 lines, 96.05% RTP, max 340x, medium. x2 Wall Multiplier and gamble; official Game Info does not state release date." },
  "wazdan-vegas-hot-81": { mechanics: ["Линии","Каскады"], source: "https://wazdan.com/games/vegas-hot-81", verifiedAt: "2026-10-09", evidence: "Official Wazdan 4 reels/81 lines, RTP 96.35%, max 5850x, medium-high, 2016-02-11, Cascading Reels and Wild with Increasing Multiplier." },
  "wazdan-vegas-reels-ii": { mechanics: ["Линии"], source: "https://wazdan.com/games/vegas-reels-ii", verifiedAt: "2026-10-09", evidence: "Official Game Info: 3 reels/1 line, RTP 96.16%, max 3000x, high. Official game copy confirms Bonus Spins x3 after ten consecutive nonwinning spins." },
  "wazdan-welcome-to-hell-81": { mechanics: ["Линии","Каскады"], source: "https://wazdan.com/games/welcome-to-hell-81", verifiedAt: "2026-10-09", evidence: "Official Wazdan 4 reels/81 lines, RTP 96.35%, max 5850x, medium-high, release 2016-02-11; Cascading Reels and Wild Increasing Multiplier." },
  "wazdan-wild-girls": { mechanics: ["Линии"], source: "https://wazdan.com/games/wild-girls", verifiedAt: "2026-10-09", evidence: "Official 3 reels/5 lines, 96.53% RTP, max 532x, medium, 2013-02-06. Two different Wilds, redhead x2; three Mystery symbols yield independent prize 5x–250x." },
  "wazdan-wild-guns": { mechanics: ["Линии"], source: "https://wazdan.com/games/wild-guns", verifiedAt: "2026-10-09", evidence: "Official Wazdan Game Info 5 reels/5 lines, RTP 96.34%, max 850x, medium, 2017-09-15; long copy disputes line count (10); x2 Wild, Random Wild tornado, Scatter Free Spins." },
  "wazdan-wild-jack": { mechanics: ["Линии"], source: "https://wazdan.com/games/wild-jack", verifiedAt: "2026-10-09", evidence: "Official Game Info 3 reels/27 lines, RTP 96.34%, max 748x, high, 2014-09-08. Joker Wild, x3 Wall Multiplier and Gamble." },
  "wazdan-wild-jack-81": { mechanics: ["Линии"], source: "https://wazdan.com/games/wild-jack-81", verifiedAt: "2026-10-09", evidence: "Official Wazdan Game Info 4 reels/81 lines, RTP 96.73%, max 2240x, low-medium, 2014-09-08; Wild expands paylines to 81." },
  "wazdan-win-replay": { mechanics: ["Линии","Респины"], source: "https://wazdan.com/games/win-replay", verifiedAt: "2026-10-09", evidence: "Official Game Info 3 reels/5 lines, RTP 96.99%, max 500x, medium, 2014-09-08; winning line locked for replay, x2 Wall Multiplier, Gamble." },

};

export function getCatalogResearchWazdan(slug: string) {
  return catalogResearchWazdan[slug];
}
