import type { CatalogVerifiedDetails } from "./catalog-verified-details";

type HacksawVolatilityDetails = Pick<CatalogVerifiedDetails, "source" | "verifiedAt" | "volatility"> & {
  volatilitySource: string;
};

const verifiedAt = "2026-09-21";
const newVerifiedAt = "2026-09-23";
const volatilitySource = "https://www.hacksawgaming.com/games";

const details: Record<string, HacksawVolatilityDetails> = {
  "hacksaw-gaming-2-wild-2-die": { volatility: "5/5", volatilitySource, source: "https://www.hacksawgaming.com/games/2-wild-2-die", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-aiko-and-the-wind-spirit": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/aiko-and-the-wind-spirit", verifiedAt },
  "hacksaw-gaming-army-of-ares": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/army-of-ares", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-bash-bros": { volatility: "2/5", volatilitySource, source: "https://www.hacksawgaming.com/games/bash-bros", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-booze-bash": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/booze-bash", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-bouncy-bombs": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/bouncy-bombs", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-bullets-and-bounty": { volatility: "2/5", volatilitySource, source: "https://www.hacksawgaming.com/games/Bullets-and-bounty", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-cash-crew": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/cash-crew", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-chaos-crew-3": { volatility: "5/5", volatilitySource, source: "https://www.hacksawgaming.com/games/chaos-crew-3", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-circle-of-life": { volatility: "5/5", volatilitySource, source: "https://www.hacksawgaming.com/games/circle-of-life", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-cloud-princess": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/cloud-princess", verifiedAt },
  "hacksaw-gaming-cursed-crypt": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/cursed-crypt", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-dandy-diamonds": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/dandy-diamonds", verifiedAt },
  "hacksaw-gaming-dark-spiral": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/dark-spiral", verifiedAt },
  "hacksaw-gaming-dawn-of-kings": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/dawn-of-kings", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-deal-with-death": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/deal-with-death", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-donny-and-danny": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/donny-and-danny", verifiedAt },
  "hacksaw-gaming-donny-dough": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/donny-dough", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-donut-division": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/donut-division", verifiedAt },
  "hacksaw-gaming-dorks-of-the-deep": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/dorks-of-the-deep", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-dragons-domain": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/dragons-domain", verifiedAt },
  "hacksaw-gaming-duel-at-dawn": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/duel-at-dawn", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-dusk-princess": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/dusk-princess", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-dynasty-of-death": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/dynasty-of-death", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-epic-bullets-and-bounty": { volatility: "5/5", volatilitySource, source: "https://www.hacksawgaming.com/games/epic-bullets-and-bounty", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-eternal-duel": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/eternal-duel", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-evil-eyes": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/evil-eyes", verifiedAt },
  "hacksaw-gaming-eye-of-medusa": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/eye-of-medusa", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-feel-the-beat": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/feel-the-beat", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-fighter-pit": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/fighter-pit", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-fire-my-laser": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/fire-my-laser", verifiedAt },
  "hacksaw-gaming-fist-of-destruction": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/fist-of-destruction", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-freds-food-truck": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/freds-food-truck", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-frkn-bananas": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/frkn-bananas", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-get-the-cheese": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/get-the-cheese", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-hot-ross": { volatility: "5/5", volatilitySource, source: "https://www.hacksawgaming.com/games/hot-ross", verifiedAt },
  "hacksaw-gaming-hounds-of-hell": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/hounds-of-hell", verifiedAt },
  "hacksaw-gaming-invictus": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/invictus", verifiedAt },
  "hacksaw-gaming-jaws-of-justice": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/jaws-of-justice", verifiedAt },
  "hacksaw-gaming-klowns": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/klowns", verifiedAt },
  "hacksaw-gaming-le-bunny": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/le-bunny", verifiedAt },
  "hacksaw-gaming-le-cowboy": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/le-cowboy", verifiedAt },
  "hacksaw-gaming-le-digger": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/le-digger", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-le-fisherman": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/le-fisherman", verifiedAt },
  "hacksaw-gaming-le-king": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/le-king", verifiedAt },
  "hacksaw-gaming-le-pharaoh": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/le-pharaoh", verifiedAt },
  "hacksaw-gaming-le-santa": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/le-santa", verifiedAt },
  "hacksaw-gaming-le-viking": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/le-viking", verifiedAt },
  "hacksaw-gaming-le-zeus": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/le-zeus", verifiedAt },
  "hacksaw-gaming-marlin-masters": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/marlin-masters", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-marlin-masters-atlantis": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/marlin-masters-atlantis", verifiedAt },
  "hacksaw-gaming-marlin-masters-the-big-haul": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/marlin-masters-the-big-haul", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-miami-mayhem": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/miami-mayhem", verifiedAt },
  "hacksaw-gaming-munchy-milo": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/munchy-milo", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-octo-attack": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/octo-attack", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-phoenix-duelreels": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/phoenix-duelreels", verifiedAt },
  "hacksaw-gaming-pray-for-six": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/pray-for-six", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-pray-for-three": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/pray-for-three", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-rainbow-princess": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/rainbow-princess", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-reign-of-rome": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/reign-of-rome", verifiedAt },
  "hacksaw-gaming-rise-of-fortuna": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/rise-of-fortuna", verifiedAt },
  "hacksaw-gaming-rise-of-ymir": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/rise-of-ymir", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-rusty-and-curly": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/rusty-and-curly", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-shaolin-master": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/shaolin-master", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-sixsixsix": { volatility: "5/5", volatilitySource, source: "https://www.hacksawgaming.com/games/sixsixsix", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-smoking-dragon": { volatility: "2/5", volatilitySource, source: "https://www.hacksawgaming.com/games/smoking-dragon", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-snow-slingers": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/snow-slingers", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-spear-of-athena": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/spear-of-athena", verifiedAt },
  "hacksaw-gaming-spinman": { volatility: "2/5", volatilitySource, source: "https://www.hacksawgaming.com/games/spinman", verifiedAt },
  "hacksaw-gaming-stormborn": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/stormborn", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-strength-of-hercules": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/strength-of-hercules", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-sun-princess": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/sun-princess", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-superstar-sevens": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/superstar-sevens", verifiedAt },
  "hacksaw-gaming-tai-the-toad": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/tai-the-toad", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-the-count": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/the-count", verifiedAt },
  "hacksaw-gaming-the-luxe": { volatility: "2/5", volatilitySource, source: "https://www.hacksawgaming.com/games/the-luxe", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-the-wildwood-curse": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/the-wildwood-curse", verifiedAt },
  "hacksaw-gaming-tiger-legends": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/tiger-legends", verifiedAt },
  "hacksaw-gaming-toshi-ways-club": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/toshi-ways-club", verifiedAt },
  "hacksaw-gaming-ultimate-slot-of-america": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/ultimate-slot-of-america", verifiedAt },
  "hacksaw-gaming-wings-of-horus": { volatility: "4/5", volatilitySource, source: "https://www.hacksawgaming.com/games/wings-of-horus", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-wishbringer": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/wishbringer", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-ze-zeus": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/ze-zeus", verifiedAt: newVerifiedAt },
  "hacksaw-gaming-zeus-ze-zecond": { volatility: "3/5", volatilitySource, source: "https://www.hacksawgaming.com/games/zeus-ze-zecond", verifiedAt: newVerifiedAt },
};

export function getCatalogVerifiedDetailsHacksawVolatilityProviderWide(slug: string) {
  return details[slug];
}
