import type { CatalogVerifiedDetails } from "./catalog-verified-details";

const verifiedAt = "2026-09-16";
const verifiedAtLatest = "2026-09-17";

const details: Record<string, CatalogVerifiedDetails> = {
  "wazdan-16-coins-x5000": {
    rtp: "96,17%",
    releaseDate: "2025-10-09",
    source: "https://wazdan.com/games/16-coins-x5000",
    verifiedAt,
  },
  "wazdan-9-burning-stars": {
    field: "9 барабанов",
    rtp: "96,14%",
    source: "https://wazdan.com/games/9-burning-stars",
    verifiedAt,
  },
  "wazdan-9-coins": {
    rtp: "96,06%",
    releaseDate: "2022-07-07",
    source: "https://wazdan.com/games/9-coins",
    verifiedAt,
  },
  "wazdan-bumba-meu-boi-coin": {
    rtp: "96,14%",
    releaseDate: "2026-01-29",
    source: "https://wazdan.com/games/bumba-meu-boi-coin",
    verifiedAt,
  },
  "wazdan-choco-reels": {
    field: "6 барабанов · до 46 656 способов",
    rtp: "96,22%",
    maxWin: "9500x",
    volatility: "Средняя–высокая",
    releaseDate: "2020-08-26",
    source: "https://wazdan.com/games/choco-reels",
    verifiedAt: verifiedAtLatest,
  },
  "wazdan-cube-mania": {
    field: "4 барабана · 9 линий",
    rtp: "96,43%",
    maxWin: "1400x",
    volatility: "Стандартная",
    releaseDate: "2013-07-28",
    source: "https://wazdan.com/games/cube-mania",
    verifiedAt: verifiedAtLatest,
  },
  "wazdan-cube-mania-deluxe": {
    field: "4 барабана · 9 линий",
    rtp: "96,59%",
    maxWin: "570x",
    volatility: "Средняя",
    releaseDate: "2018-06-06",
    source: "https://wazdan.com/games/cube-mania-deluxe",
    verifiedAt: verifiedAtLatest,
  },
  "wazdan-football-mania": {
    "field": "9 барабанов",
    "rtp": "96,59%",
    "maxWin": "1000x",
    "volatility": "Высокая",
    "source": "https://wazdan.com/games/football-mania",
    "verifiedAt": "2026-10-08"
  },
  "wazdan-highway-to-hell": {
    field: "5 барабанов · 5 линий",
    rtp: "96,18%",
    source: "https://wazdan.com/games/highway-to-hell",
    verifiedAt,
  },
  "wazdan-hot-party": {
    field: "5 барабанов · 20 линий",
    rtp: "96,48%",
    source: "https://wazdan.com/games/hot-party",
    verifiedAt,
  },
  "wazdan-jelly-reels": {
    field: "8 барабанов · 16 777 216 способов",
    rtp: "96,22%",
    maxWin: "2500x",
    volatility: "Очень высокая",
    releaseDate: "2021-11-18",
    source: "https://wazdan.com/games/jelly-reels",
    verifiedAt: verifiedAtLatest,
  },
  "wazdan-joker-explosion": {
    field: "4 барабана · 7 линий",
    rtp: "96,50%",
    source: "https://wazdan.com/games/joker-explosion",
    verifiedAt,
  },
  "wazdan-kick-off": {
    rtp: "96,42%",
    releaseDate: "2016-06-03",
    source: "https://wazdan.com/games/kick-off",
    verifiedAt,
  },
  "wazdan-lucky-fish": {
    field: "5 барабанов · 243 способа",
    rtp: "96,50%",
    maxWin: "350x",
    volatility: "Низкая–средняя",
    releaseDate: "2019-07-02",
    source: "https://wazdan.com/games/lucky-fish",
    verifiedAt: verifiedAtLatest,
  },
  "wazdan-power-of-gods-hades": {
    field: "5 барабанов · 243 способа",
    rtp: "96,14%",
    source: "https://wazdan.com/games/power-of-gods-hades",
    verifiedAt,
  },
  "wazdan-space-gem": {
    field: "6 барабанов · 10 линий",
    rtp: "96,40%",
    source: "https://wazdan.com/games/space-gem",
    verifiedAt,
  },
  "wazdan-valentines-coins": {
    field: "9 барабанов",
    rtp: "96,06%",
    releaseDate: "2026-02-03",
    source: "https://wazdan.com/games/valentines-coins",
    verifiedAt,
  },
  "wazdan-vegas-hot": {
    field: "3 барабана · 5 линий",
    rtp: "96,05%",
    source: "https://wazdan.com/games/vegas-hot",
    verifiedAt,
  },
  "wazdan-vegas-reels-ii": {
    field: "3 барабана · 1 линия",
    rtp: "96,16%",
    source: "https://wazdan.com/games/vegas-reels-ii",
    verifiedAt,
  },
  "wazdan-black-horse-deluxe": { field: "6 барабанов · 20 линий", rtp: "96,23%", maxWin: "950x", volatility: "Средняя", releaseDate: "2020-07-01", source: "https://wazdan.com/games/black-horse-deluxe", verifiedAt: verifiedAtLatest },
  "wazdan-book-of-faith": { field: "5 барабанов · 10 линий", rtp: "96,13%", maxWin: "5000x", volatility: "Высокая", releaseDate: "2023-12-05", source: "https://wazdan.com/games/book-of-faith", verifiedAt: verifiedAtLatest },
  "wazdan-burning-reels": { field: "5 барабанов · 20 линий", rtp: "96,63%", maxWin: "1250x", volatility: "Низкая", releaseDate: "2017-07-14", source: "https://wazdan.com/games/burning-reels", verifiedAt: verifiedAtLatest },
  "wazdan-burning-stars": { field: "5 барабанов · 20 линий", rtp: "96,50%", maxWin: "305x", volatility: "Низкая–средняя", releaseDate: "2014-08-09", source: "https://wazdan.com/games/burning-stars", verifiedAt: verifiedAtLatest },
  "wazdan-captain-shark": { field: "5 барабанов · 20 линий", rtp: "96,25%", maxWin: "5350x", volatility: "Высокая", releaseDate: "2017-02-05", source: "https://wazdan.com/games/captain-shark", verifiedAt: verifiedAtLatest },
  "wazdan-clover-lady": { field: "6 барабанов · 10 линий", rtp: "96,21%", maxWin: "3500x", volatility: "Высокая", releaseDate: "2021-02-10", source: "https://wazdan.com/games/clover-lady", verifiedAt: verifiedAtLatest },
  "wazdan-colin-the-cat": { field: "4 барабана · 10 линий", rtp: "96,10%", maxWin: "260x", volatility: "Средняя", releaseDate: "2016-01-12", source: "https://wazdan.com/games/colin-the-cat", verifiedAt: verifiedAtLatest },
  "wazdan-corrida-romance-deluxe": { field: "5 барабанов · 20 линий", rtp: "96,29%", maxWin: "4650x", volatility: "Средняя", releaseDate: "2018-07-04", source: "https://wazdan.com/games/corrida-romance-deluxe", verifiedAt: verifiedAtLatest },
  "wazdan-crazy-cars": { field: "5 барабанов · 5 линий", rtp: "96,27%", maxWin: "1750x", volatility: "Высокая", releaseDate: "2016-02-11", source: "https://wazdan.com/games/crazy-cars", verifiedAt: verifiedAtLatest },
  "wazdan-criss-cross-81": { field: "4 барабана · 81 линия", rtp: "96,29%", maxWin: "2144x", volatility: "Средняя–высокая", releaseDate: "2012-11-19", source: "https://wazdan.com/games/criss-cross-81", verifiedAt: verifiedAtLatest },
  "wazdan-demon-jack-27": {"field":"3 барабана · 27 линий","rtp":"96,09%","maxWin":"1104x","volatility":"Высокая","releaseDate":"2016-02-11","source":"https://wazdan.com/games/demon-jack-27","verifiedAt":"2026-10-08"},
  "wazdan-dino-reels-81": {"field":"4 барабана · 7 линий в Game Info","rtp":"96,44%","maxWin":"691x","volatility":"Средняя–высокая","releaseDate":"2016-12-01","source":"https://wazdan.com/games/dino-reels-81","verifiedAt":"2026-10-08"},
  "wazdan-double-tigers": {"field":"3 барабана · 8 линий по Game Info","rtp":"96,43%","maxWin":"40x","volatility":"Низкая–средняя","releaseDate":"2018-08-05","source":"https://wazdan.com/games/double-tigers","verifiedAt":"2026-10-08"},
  "wazdan-draculas-castle": {"field":"5 барабанов · 5 линий","rtp":"96,56%","maxWin":"1000x","volatility":"Высокая","releaseDate":"2017-12-27","source":"https://wazdan.com/games/draculas-castle","verifiedAt":"2026-10-08"},
  "wazdan-dragons-lucky-8": {"field":"6 барабанов · 20 линий","rtp":"96,26%","maxWin":"1150x","volatility":"Низкая–средняя","releaseDate":"2019-08-20","source":"https://wazdan.com/games/dragons-lucky-8","verifiedAt":"2026-10-08"},
  "wazdan-dwarfs-fortune": {"field":"5 барабанов · 0 линий в Game Info","rtp":"96,16%","maxWin":"2500x","volatility":"Высокая","releaseDate":"2022-03-09","source":"https://wazdan.com/games/dwarfs-fortune","verifiedAt":"2026-10-08"},
  "wazdan-easter-coins": {"field":"25 позиций · 0 линий","rtp":"96,17%","maxWin":"2000x","volatility":"Высокая","releaseDate":"2026-03-20","source":"https://wazdan.com/games/easter-coins","verifiedAt":"2026-10-08"},
  "wazdan-eggs-of-fortune": {"field":"5 барабанов · 5 линий","rtp":"96,12%","maxWin":"5000x","volatility":"Экстремальная","releaseDate":"2025-08-07","source":"https://wazdan.com/games/eggs-of-fortune","verifiedAt":"2026-10-08"},
  "wazdan-fenix-play-27-deluxe": {"field":"3 барабана · 27 линий","rtp":"96,25%","maxWin":"748x","volatility":"Высокая","releaseDate":"2017-09-15","source":"https://wazdan.com/games/fenix-play-27-deluxe","verifiedAt":"2026-10-08"},
  "wazdan-fenix-play-deluxe": {"field":"3 барабана · 5 линий","rtp":"96,44%","maxWin":"75x","volatility":"Средняя","releaseDate":"2017-09-15","source":"https://wazdan.com/games/fenix-play-deluxe","verifiedAt":"2026-10-08"},
  "wazdan-fire-bird": {"field":"3 барабана · 5 линий","rtp":"96,05%","maxWin":"72x","volatility":"Стандартная","source":"https://wazdan.com/games/fire-bird","verifiedAt":"2026-10-08"},
  "wazdan-fishermans-luck": {"field":"10 барабанов · 0 линий по Game Info","rtp":"96,13%","maxWin":"2500x","volatility":"Средняя","releaseDate":"2026-03-05","source":"https://wazdan.com/games/fishermans-luck","verifiedAt":"2026-10-08"},
  "wazdan-football-mania-deluxe": {"field":"9 барабанов · 0 линий по Game Info","rtp":"96,59%","maxWin":"1000x","volatility":"Высокая","releaseDate":"2018-05-30","source":"https://wazdan.com/games/football-mania-deluxe","verifiedAt":"2026-10-08"},
  "wazdan-fortune-reels": {"field":"6 барабанов · 46 656 способов","rtp":"96,12%","maxWin":"2100x","volatility":"Высокая","releaseDate":"2021-07-27","source":"https://wazdan.com/games/fortune-reels","verifiedAt":"2026-10-08"},
  "wazdan-fruit-fiesta": {"field":"5 барабанов · 20 линий","rtp":"96,32%","maxWin":"730x","volatility":"Высокая","releaseDate":"2017-12-01","source":"https://wazdan.com/games/fruit-fiesta","verifiedAt":"2026-10-08"},
  "wazdan-fruit-mania": {"field":"9 барабанов · 0 линий по Game Info","rtp":"96,59%","maxWin":"1000x","volatility":"Высокая","releaseDate":"2014-09-08","source":"https://wazdan.com/games/fruit-mania","verifiedAt":"2026-10-08"},
  "wazdan-hot-slot-777-diamond-crown": {"field":"5 барабанов · 10 линий","rtp":"96,15%","maxWin":"5000x","volatility":"Средняя–высокая","releaseDate":"2025-09-26","source":"https://wazdan.com/games/hot-slot-777-diamond-crown","verifiedAt":"2026-10-09"},
  "wazdan-hot-slot-777-gold-crown": {"field":"5 барабанов · 10 линий","rtp":"96,14%","maxWin":"1500x","volatility":"Низкая–средняя","releaseDate":"2025-04-02","source":"https://wazdan.com/games/hot-slot-777-gold-crown","verifiedAt":"2026-10-09"},
  "wazdan-hot-slot-777-platinum-crown": {"field":"5 барабанов · 10 линий","rtp":"96,17%","maxWin":"2500x","volatility":"Средняя","releaseDate":"2025-07-10","source":"https://wazdan.com/games/hot-slot-777-platinum-crown","verifiedAt":"2026-10-09"},
  "wazdan-hot-slot-777-rubies": {"field":"5 барабанов · 20 линий","rtp":"96,14%","maxWin":"500x","volatility":"Настраиваемая","releaseDate":"2023-02-16","source":"https://wazdan.com/games/hot-slot-777-rubies","verifiedAt":"2026-10-09"},
  "wazdan-hot-slot-777-rubies-extremely-light": {"field":"5 барабанов · 20 линий","rtp":"96,14%","maxWin":"500x","volatility":"Высокая","releaseDate":"2024-02-21","source":"https://wazdan.com/games/hot-slot-777-rubies-extremely-light","verifiedAt":"2026-10-09"},
  "wazdan-hot-slot-777-stars-extremely-light": {"field":"5 барабанов · 20 линий","rtp":"96,10%","maxWin":"500x","volatility":"Средняя","releaseDate":"2024-01-10","source":"https://wazdan.com/games/hot-slot-777-stars-extremely-light","verifiedAt":"2026-10-09"},
  "wazdan-hot-slot-gold-coins": {"field":"15 барабанов · 10 линий","rtp":"96,15%","maxWin":"750x","volatility":"Средняя","releaseDate":"2025-04-24","source":"https://wazdan.com/games/hot-slot-gold-coins","verifiedAt":"2026-10-09"},
  "wazdan-hot-slot-magic-bombs": {"field":"5 барабанов · 10 линий","rtp":"96,17%","maxWin":"6000x","volatility":"Высокая","releaseDate":"2022-10-11","source":"https://wazdan.com/games/hot-slot-magic-bombs","verifiedAt":"2026-10-09"},

};

export function getCatalogVerifiedDetailsWazdanProviderWide(slug: string) {
  return details[slug];
}
