import type { CatalogVerifiedDetails } from "./catalog-verified-details";

type HacksawCloseoutDetails = Partial<
  Pick<CatalogVerifiedDetails, "field" | "rtp" | "maxWin" | "releaseDate">
> & {
  verifiedAt: string;
  fieldSource?: string;
  rtpSource?: string;
  maxWinSource?: string;
  releaseDateSource?: string;
};

const verifiedAt = "2026-09-24";
const sc = (slug: string) => `https://slotcatalog.com/en/slots/${slug}`;

const details: Record<string, HacksawCloseoutDetails> = {
  "hacksaw-gaming-3-cursed-chests-hold-and-win": {
    field: "5×3 · 17 линий",
    fieldSource: sc("3-cursed-chests"),
    verifiedAt,
  },
  "hacksaw-gaming-arizona-james-and-the-lost-relics": {
    field: "6×5 · Cluster Pays",
    fieldSource: sc("arizona-james-and-the-lost-relics"),
    verifiedAt,
  },
  "hacksaw-gaming-army-of-ares": {
    field: "5×4 · 14 линий",
    rtp: "96,26%",
    maxWin: "15000x",
    fieldSource: sc("army-of-ares"),
    rtpSource: sc("army-of-ares"),
    maxWinSource: sc("army-of-ares"),
    verifiedAt,
  },
  "hacksaw-gaming-beam-boys": {
    rtp: "96,35%",
    releaseDate: "2024-01-21",
    rtpSource: sc("Beam-Boys"),
    releaseDateSource: sc("Beam-Boys"),
    verifiedAt,
  },
  "hacksaw-gaming-benny-the-beer": {
    releaseDate: "2023-10-05",
    releaseDateSource: sc("Benny-The-Beer"),
    verifiedAt,
  },
  "hacksaw-gaming-bouncy-bombs": {
    rtp: "96,22%",
    rtpSource: sc("Bouncy-Bombs"),
    verifiedAt,
  },
  "hacksaw-gaming-cash-crew": {
    rtp: "94,23%",
    releaseDate: "2024-03-22",
    rtpSource: sc("cash-crew"),
    releaseDateSource: sc("cash-crew"),
    verifiedAt,
  },
  "hacksaw-gaming-cloud-princess": {
    field: "6×5 · Pay Anywhere",
    rtp: "94,21%",
    maxWin: "10000x",
    releaseDate: "2024-09-23",
    fieldSource: sc("cloud-princess"),
    rtpSource: sc("cloud-princess"),
    maxWinSource: sc("cloud-princess"),
    releaseDateSource: sc("cloud-princess"),
    verifiedAt,
  },
  "hacksaw-gaming-cursed-crypt": {
    rtp: "94,29%",
    rtpSource: sc("cursed-crypt"),
    verifiedAt,
  },
  "hacksaw-gaming-dandy-diamonds": {
    field: "5×5 · 19 линий",
    rtp: "96,33%",
    maxWin: "5000x",
    fieldSource: sc("dandy-diamonds"),
    rtpSource: sc("dandy-diamonds"),
    maxWinSource: sc("dandy-diamonds"),
    verifiedAt,
  },
  "hacksaw-gaming-dawn-of-kings": {
    rtp: "96,24%",
    releaseDate: "2024-02-23",
    rtpSource: sc("Dawn-of-Kings"),
    releaseDateSource: sc("Dawn-of-Kings"),
    verifiedAt,
  },
  "hacksaw-gaming-divine-drop": {
    rtp: "94,34%",
    releaseDate: "2024-04-10",
    rtpSource: sc("divine-drop"),
    releaseDateSource: sc("divine-drop"),
    verifiedAt,
  },
  "hacksaw-gaming-donny-dough": {
    rtp: "96,23%",
    maxWin: "10000x",
    releaseDate: "2024-08-14",
    rtpSource: sc("donny-dough"),
    maxWinSource: sc("donny-dough"),
    releaseDateSource: sc("donny-dough"),
    verifiedAt,
  },
  "hacksaw-gaming-donut-division": {
    field: "6×5 · 19 линий",
    rtp: "94,29%",
    maxWin: "12500x",
    releaseDate: "2024-12-12",
    fieldSource: sc("donut-division"),
    rtpSource: sc("donut-division"),
    maxWinSource: sc("donut-division"),
    releaseDateSource: sc("donut-division"),
    verifiedAt,
  },
  "hacksaw-gaming-dragons-domain": {
    field: "6×5 · Pay Anywhere",
    rtp: "96,31%",
    releaseDate: "2024-08-01",
    fieldSource: sc("dragon-s-domain"),
    rtpSource: sc("dragon-s-domain"),
    releaseDateSource: sc("dragon-s-domain"),
    verifiedAt,
  },
  "hacksaw-gaming-duel-at-dawn": {
    field: "5×5 · 19 линий",
    rtp: "94,27%",
    maxWin: "15000x",
    releaseDate: "2024-11-21",
    fieldSource: sc("duel-at-dawn"),
    rtpSource: sc("duel-at-dawn"),
    maxWinSource: sc("duel-at-dawn"),
    releaseDateSource: sc("duel-at-dawn"),
    verifiedAt,
  },
  "hacksaw-gaming-dusk-princess": {
    rtp: "96,21%",
    releaseDate: "2026-03-17",
    rtpSource: sc("dusk-princess"),
    releaseDateSource: sc("dusk-princess"),
    verifiedAt,
  },
  "hacksaw-gaming-dynasty-of-death": {
    field: "5×4 · 14 линий",
    rtp: "96,27%",
    maxWin: "12500x",
    fieldSource: sc("dynasty-of-death"),
    rtpSource: sc("dynasty-of-death"),
    maxWinSource: sc("dynasty-of-death"),
    verifiedAt,
  },
  "hacksaw-gaming-epic-ze-zeus": {
    field: "6×5 · Cluster Pays",
    fieldSource: sc("epic-ze-zeus"),
    verifiedAt,
  },
  "hacksaw-gaming-eternal-duel": {
    field: "5×5 · 19 линий",
    rtp: "94,24%",
    maxWin: "15000x",
    fieldSource: sc("eternal-duel"),
    rtpSource: sc("eternal-duel"),
    maxWinSource: sc("eternal-duel"),
    verifiedAt,
  },
  "hacksaw-gaming-evil-eyes": {
    rtp: "96,24%",
    releaseDate: "2024-09-04",
    rtpSource: sc("evil-eyes"),
    releaseDateSource: sc("evil-eyes"),
    verifiedAt,
  },
  "hacksaw-gaming-eye-of-medusa": {
    field: "5×5 · 3125 способов",
    rtp: "94,24%",
    fieldSource: sc("eye-of-medusa"),
    rtpSource: sc("eye-of-medusa"),
    verifiedAt,
  },
  "hacksaw-gaming-eye-of-the-panda": {
    releaseDate: "2023-10-20",
    releaseDateSource: sc("Eye-of-the-Panda"),
    verifiedAt,
  },
  "hacksaw-gaming-fire-my-laser": {
    field: "6×6 · ReactWins",
    rtp: "94,16%",
    maxWin: "15000x",
    releaseDate: "2024-01-19",
    fieldSource: sc("fire-my-laser"),
    rtpSource: sc("fire-my-laser"),
    maxWinSource: sc("fire-my-laser"),
    releaseDateSource: sc("fire-my-laser"),
    verifiedAt,
  },
  "hacksaw-gaming-fist-of-destruction": {
    rtp: "94,30%",
    releaseDate: "2024-02-14",
    rtpSource: sc("Fist-of-Destruction"),
    releaseDateSource: sc("Fist-of-Destruction"),
    verifiedAt,
  },
  "hacksaw-gaming-frkn-bananas": {
    field: "6×5 · 19 линий",
    rtp: "94,29%",
    maxWin: "10000x",
    releaseDate: "2025-02-03",
    fieldSource: sc("frkn-bananas"),
    rtpSource: sc("frkn-bananas"),
    maxWinSource: sc("frkn-bananas"),
    releaseDateSource: sc("frkn-bananas"),
    verifiedAt,
  },
  "hacksaw-gaming-get-the-cheese": {
    field: "6×5 · Cluster Pays",
    rtp: "94,20%",
    maxWin: "10000x",
    releaseDate: "2024-09-30",
    fieldSource: sc("get-the-cheese"),
    rtpSource: sc("get-the-cheese"),
    maxWinSource: sc("get-the-cheese"),
    releaseDateSource: sc("get-the-cheese"),
    verifiedAt,
  },
  "hacksaw-gaming-great-game-rockies": {
    field: "5×3 · 17 линий",
    fieldSource: sc("great-game-rockies"),
    verifiedAt,
  },
  "hacksaw-gaming-grug-make-fire": {
    field: "5×4 · 14 линий",
    releaseDate: "2026-06-09",
    fieldSource: sc("grug-make-fire"),
    releaseDateSource: sc("grug-make-fire"),
    verifiedAt,
  },
  "hacksaw-gaming-hounds-of-hell": {
    field: "5×5 · Pay Anywhere",
    rtp: "96,27%",
    maxWin: "20000x",
    releaseDate: "2025-02-10",
    fieldSource: sc("hounds-of-hell"),
    rtpSource: sc("hounds-of-hell"),
    maxWinSource: sc("hounds-of-hell"),
    releaseDateSource: sc("hounds-of-hell"),
    verifiedAt,
  },
  "hacksaw-gaming-jaws-of-justice": {
    field: "5×4 · 14 линий",
    rtp: "96,20%",
    maxWin: "10000x",
    fieldSource: sc("jaws-of-justice"),
    rtpSource: sc("jaws-of-justice"),
    maxWinSource: sc("jaws-of-justice"),
    verifiedAt,
  },
  "hacksaw-gaming-jelly-slice": {
    rtp: "94,32%",
    releaseDate: "2024-05-06",
    rtpSource: sc("jelly-slice"),
    releaseDateSource: sc("jelly-slice"),
    verifiedAt,
  },
  "hacksaw-gaming-klowns": {
    rtp: "94,31%",
    releaseDate: "2025-01-02",
    rtpSource: sc("klowns"),
    releaseDateSource: sc("klowns"),
    verifiedAt,
  },
  "hacksaw-gaming-le-bunny": {
    field: "6×5 · Cluster Pays",
    rtp: "94,18%",
    maxWin: "20000x",
    fieldSource: sc("le-bunny"),
    rtpSource: sc("le-bunny"),
    maxWinSource: sc("le-bunny"),
    verifiedAt,
  },
  "hacksaw-gaming-le-digger": {
    field: "6×5 · Cluster Pays",
    rtp: "94,29%",
    maxWin: "15000x",
    fieldSource: sc("le-digger"),
    rtpSource: sc("le-digger"),
    maxWinSource: sc("le-digger"),
    verifiedAt,
  },
  "hacksaw-gaming-le-pharaoh": {
    field: "6×5 · 19 линий",
    rtp: "94,33%",
    releaseDate: "2024-09-26",
    fieldSource: sc("le-pharaoh"),
    rtpSource: sc("le-pharaoh"),
    releaseDateSource: sc("le-pharaoh"),
    verifiedAt,
  },
  "hacksaw-gaming-le-prechaun": {
    field: "6×5 · Cluster Pays",
    fieldSource: sc("le-prechaun"),
    verifiedAt,
  },
  "hacksaw-gaming-le-sortudo": {
    field: "3×3 · 9 линий",
    fieldSource: sc("le-sortudo"),
    verifiedAt,
  },
  "hacksaw-gaming-le-viking": {
    field: "6×5 · 15625 способов",
    rtp: "96,32%",
    maxWin: "10000x",
    releaseDate: "2025-01-16",
    fieldSource: sc("le-viking"),
    rtpSource: sc("le-viking"),
    maxWinSource: sc("le-viking"),
    releaseDateSource: sc("le-viking"),
    verifiedAt,
  },
  "hacksaw-gaming-magic-piggy-og": {
    field: "5×3 · 17 линий",
    fieldSource: sc("magic-piggy-og"),
    verifiedAt,
  },
  "hacksaw-gaming-mayan-stackways": {
    rtp: "96,23%",
    releaseDate: "2023-04-20",
    rtpSource: sc("Mayan-Stackways"),
    releaseDateSource: sc("Mayan-Stackways"),
    verifiedAt,
  },
  "hacksaw-gaming-octo-attack": {
    field: "6×5 · Cluster Pays",
    rtp: "94,26%",
    maxWin: "10000x",
    releaseDate: "2024-08-23",
    fieldSource: sc("octo-attack"),
    rtpSource: sc("octo-attack"),
    maxWinSource: sc("octo-attack"),
    releaseDateSource: sc("octo-attack"),
    verifiedAt,
  },
  "hacksaw-gaming-orb-of-destiny": {
    rtp: "94,29%",
    releaseDate: "2024-04-08",
    rtpSource: sc("orb-of-destiny"),
    releaseDateSource: sc("orb-of-destiny"),
    verifiedAt,
  },
  "hacksaw-gaming-phoenix-duelreels": {
    field: "5×4 · 14 линий",
    rtp: "96,28%",
    maxWin: "10000x",
    releaseDate: "2024-12-30",
    fieldSource: sc("phoenix-duelreels"),
    rtpSource: sc("phoenix-duelreels"),
    maxWinSource: sc("phoenix-duelreels"),
    releaseDateSource: sc("phoenix-duelreels"),
    verifiedAt,
  },
  "hacksaw-gaming-rainbow-princess": {
    field: "6×5 · Cluster Pays",
    rtp: "94,35%",
    maxWin: "10000x",
    releaseDate: "2025-08-07",
    fieldSource: sc("rainbow-princess"),
    rtpSource: sc("rainbow-princess"),
    maxWinSource: sc("rainbow-princess"),
    releaseDateSource: sc("rainbow-princess"),
    verifiedAt,
  },
  "hacksaw-gaming-red-rascal": {
    field: "5×5 · 19 линий",
    fieldSource: sc("red-rascal"),
    verifiedAt,
  },
  "hacksaw-gaming-rise-of-fortuna": {
    field: "5×4 · 14 линий",
    rtp: "96,28%",
    maxWin: "10000x",
    fieldSource: sc("rise-of-fortuna"),
    rtpSource: sc("rise-of-fortuna"),
    maxWinSource: sc("rise-of-fortuna"),
    verifiedAt,
  },
  "hacksaw-gaming-rise-of-ymir": {
    rtp: "94,24%",
    releaseDate: "2024-10-14",
    rtpSource: sc("rise-of-ymir"),
    releaseDateSource: sc("rise-of-ymir"),
    verifiedAt,
  },
  "hacksaw-gaming-sand-and-ashes": {
    field: "5×5 · 19 линий",
    fieldSource: sc("sand-and-ashes"),
    verifiedAt,
  },
  "hacksaw-gaming-shaolin-master": {
    field: "6×5 · Cluster Pays",
    rtp: "96,31%",
    maxWin: "10000x",
    releaseDate: "2024-12-05",
    fieldSource: sc("shaolin-master"),
    rtpSource: sc("shaolin-master"),
    maxWinSource: sc("shaolin-master"),
    releaseDateSource: sc("shaolin-master"),
    verifiedAt,
  },
  "hacksaw-gaming-sixsixsix": {
    field: "5×4 · 14 линий",
    rtp: "94,19%",
    maxWin: "16666x",
    fieldSource: sc("sixsixsix"),
    rtpSource: sc("sixsixsix"),
    maxWinSource: sc("sixsixsix"),
    verifiedAt,
  },
  "hacksaw-gaming-slayers-inc": {
    rtp: "96,28%",
    releaseDate: "2024-05-13",
    rtpSource: sc("slayers-inc"),
    releaseDateSource: sc("slayers-inc"),
    verifiedAt,
  },
  "hacksaw-gaming-snow-slingers": {
    rtp: "94,32%",
    releaseDate: "2024-11-18",
    rtpSource: sc("snow-slingers"),
    releaseDateSource: sc("snow-slingers"),
    verifiedAt,
  },
  "hacksaw-gaming-stormborn": {
    field: "5×4 · 14 линий",
    rtp: "96,27%",
    maxWin: "15000x",
    fieldSource: sc("stormborn"),
    rtpSource: sc("stormborn"),
    maxWinSource: sc("stormborn"),
    verifiedAt,
  },
  "hacksaw-gaming-supreme-zeus": {
    field: "5×4 · 1024 способа",
    fieldSource: sc("supreme-zeus"),
    verifiedAt,
  },
  "hacksaw-gaming-tai-the-toad": {
    rtp: "94,35%",
    releaseDate: "2024-06-24",
    rtpSource: sc("tai-the-toad"),
    releaseDateSource: sc("tai-the-toad"),
    verifiedAt,
  },
  "hacksaw-gaming-wings-of-horus": {
    field: "5×6 · 7776 способов",
    rtp: "94,27%",
    maxWin: "15000x",
    releaseDate: "2024-11-07",
    fieldSource: sc("wings-of-horus"),
    rtpSource: sc("wings-of-horus"),
    maxWinSource: sc("wings-of-horus"),
    releaseDateSource: sc("wings-of-horus"),
    verifiedAt,
  },
  "hacksaw-gaming-ze-zeus": {
    rtp: "92,17%",
    releaseDate: "2024-06-06",
    rtpSource: sc("ze-zeus"),
    releaseDateSource: sc("ze-zeus"),
    verifiedAt,
  },
};

export function getCatalogVerifiedDetailsHacksawCloseout2_20260924(slug: string) {
  return details[slug];
}
