import type { CatalogResearch } from "./catalog-research";

const verifiedAt = "2026-09-18";

const records: Record<string, CatalogResearch> = {
  "3-oaks-gaming-3-coin-volcanoes": { mechanics: ["Линии", "Респины", "Mystery Symbols", "Сбор символов", "Множители", "Расширяющиеся барабаны"], source: "https://3oaks.com/game/3_coin_volcanoes", verifiedAt, evidence: "Official page describes bonus respins, Mystery symbols, a Collect symbol, MULTI multipliers and GROW adding two extra rows." },
  "3-oaks-gaming-3-hot-teapots": { mechanics: ["Линии", "Респины", "Множители"], source: "https://3oaks.com/game/3_hot_teapots", verifiedAt, evidence: "Official Hold & Win bonus runs as respins, while the MULTI feature applies multipliers to random cells." },
  "3-oaks-gaming-3-jewel-crowns": { mechanics: ["Сбор символов", "Множители"], source: "https://3oaks.com/game/3_jewel_crowns", verifiedAt, evidence: "Official page says Wild symbols may carry x2 or x5 multipliers while Crown symbols fill the three feature metres." },
  "3-oaks-gaming-3-lucky-sparks": { mechanics: ["Линии", "Сбор символов", "Расширяющиеся барабаны"], source: "https://3oaks.com/game/3_lucky_sparks", verifiedAt, evidence: "Official COLLECT feature gathers visible Coin values and the RISE feature expands the grid with two extra rows during Free Spins." },
  "3-oaks-gaming-3-olymp-fortunes": { mechanics: ["Линии", "Респины", "Множители", "Бонусное колесо"], source: "https://3oaks.com/game/3_olymp_fortunes", verifiedAt, evidence: "Official page says EXTRA increases the respin count, MULTI applies multipliers, and a Super Wheel spins before every bonus round." },
  "3-oaks-gaming-3-super-coin-volcanoes": { mechanics: ["Линии", "Респины", "Mystery Symbols", "Сбор символов", "Множители", "Расширяющиеся барабаны", "Бонусное колесо"], source: "https://3oaks.com/game/3_super_coin_volcanoes", verifiedAt, evidence: "Official page describes respins, Mystery and Collect symbols, MULTI/GOLD VOLCANO multipliers, GROW extra rows and the Super Wheel." },
  "3-oaks-gaming-3-super-hot-chillies": { mechanics: ["Линии", "Респины", "Множители", "Бонусное колесо"], source: "https://3oaks.com/game/3_super_hot_chillies", verifiedAt, evidence: "Official page says EXTRA increases respins, MULTI adds multipliers to random symbols and the Super Wheel awards bonus enhancements." },
  "3-oaks-gaming-4-clover-pots": { mechanics: ["Линии", "Множители", "Сбор символов", "Mystery Symbols", "Расширяющиеся барабаны"], source: "https://3oaks.com/game/4_clover_pots", verifiedAt, evidence: "Official bonus features include MULTI multipliers, COLLECT, MYSTERY and a Super Bonus that expands the grid by two rows." },
  "3-oaks-gaming-4-fairy-flowers": { mechanics: ["Линии", "Сбор символов", "Множители", "Mystery Symbols", "Респины", "Расширяющиеся барабаны"], source: "https://3oaks.com/game/4_fairy_flowers", verifiedAt, evidence: "Official features include COLLECT, MULTI multipliers, MYSTERY, respin refills and a Magic Bonus with two extra grid rows." },
  "3-oaks-gaming-4-pots-of-egypt": { mechanics: ["Линии", "Респины", "Mystery Symbols", "Сбор символов", "Множители"], source: "https://3oaks.com/game/4_pots_of_egypt", verifiedAt, evidence: "Official Hold & Win rules collect Coin Bonus values during respins; POT features include COLLECT and MULTI, while Mystery Symbols transform into bonus features during respins." },
  "3-oaks-gaming-777-fruity-coins": { mechanics: ["Линии", "Сбор символов", "Респины"], source: "https://3oaks.com/game/777_fruity_coins", verifiedAt, evidence: "Official Collect Symbol gathers all visible Coin values and the Bonus Game starts with three respins that reset whenever a new symbol lands." },
  "3-oaks-gaming-4-wolf-drums": { mechanics: ["Линии", "Сбор символов", "Множители", "Расширяющиеся барабаны", "Респины"], source: "https://3oaks.com/game/4_wolf_drums", verifiedAt, evidence: "Official features include COLLECT, MULTI multipliers, MIRROR expanding the grid by two rows and the Master Drum resetting respins." },
  "3-oaks-gaming-aztec-fire-2": { mechanics: ["Линии", "Респины", "Сбор символов", "Расширяющиеся барабаны", "Множители"], source: "https://3oaks.com/game/aztec_fire_2", verifiedAt, evidence: "Official Hold & Win starts with three respins; collected Bonus Symbols unlock rows five through eight and extra rows carry multipliers up to x10." },
  "3-oaks-gaming-amazonia-wins": { mechanics: ["Линии", "Сбор символов", "Mystery Symbols", "Множители"], source: "https://3oaks.com/game/amazonia_wins", verifiedAt, evidence: "Official Extra Board can reveal Mystery Symbols; Collect Symbols award its prizes, the Golden Idol collects Bonus symbols and Bonus-game Win Symbols can carry multipliers." },
  "3-oaks-gaming-coin-princess-x1000": { mechanics: ["Каскады", "Множители"], source: "https://3oaks.com/game/coin_princess_x1000", verifiedAt, evidence: "Official page explicitly names Cascading Symbols and coin multipliers from x2 to x1000, with cumulative multipliers during Free Spins." },
  "3-oaks-gaming-coin-lamp": { mechanics: ["Респины", "Сбор символов", "Mystery Symbols", "Множители", "Расширяющиеся барабаны"], source: "https://3oaks.com/game/coin_lamp", verifiedAt, evidence: "Official Bonus Game uses respins with Collect and Mystery symbols, random multipliers up to x10 and three unlockable extra rows." },
  "3-oaks-gaming-coin-up-hot-fire": { mechanics: ["Респины", "Сбор символов", "Mystery Symbols", "Множители"], source: "https://3oaks.com/game/coin_up", verifiedAt, evidence: "Official bonus uses three resetting respins, Collect and Mystery symbols, while MULTI UP adds multipliers to symbols." },
  "3-oaks-gaming-coin-up-lightning": { mechanics: ["Респины", "Сбор символов", "Mystery Symbols", "Множители"], source: "https://3oaks.com/game/coin_lightning", verifiedAt, evidence: "Official bonus starts with three resetting respins and includes Collect, Mystery, MULTI UP and SUPER MULTI UP symbols." },
  "3-oaks-gaming-coin-volcano": { mechanics: ["Респины", "Сбор символов", "Mystery Symbols", "Множители"], source: "https://3oaks.com/game/coin_volcano", verifiedAt, evidence: "Official Bonus Game has three respins, Collect and Mystery symbols and the Volcano Multiplier feature." },
  "3-oaks-gaming-coin-volcano-2": { mechanics: ["Респины", "Сбор символов", "Mystery Symbols", "Множители"], source: "https://3oaks.com/game/coin_volcano_2", verifiedAt, evidence: "Official sequel keeps three respins and adds Collect, Mystery and Volcano Multiplier features across its larger grid." },
  "3-oaks-gaming-crystal-scarabs": { mechanics: ["Респины", "Сбор символов", "Множители"], source: "https://3oaks.com/game/crystal_scarabs", verifiedAt, evidence: "Official Hold & Win is a respin feature; Boost collects current values and the extra row includes Multiplier boosters." },
  "3-oaks-gaming-dj-tiger-x1000": { mechanics: ["Каскады", "Mystery Symbols", "Множители"], source: "https://3oaks.com/game/dj_tiger_x1000", verifiedAt, evidence: "Official page names Cascading Reels, multiplier symbols up to x1000, Mystery Multipliers and cumulative Free Spins multipliers." },
  "3-oaks-gaming-gold-nuggets": { mechanics: ["Респины", "Сбор символов", "Mystery Symbols", "Множители"], source: "https://3oaks.com/game/gold_nuggets", verifiedAt, evidence: "Official Hold & Win starts with three resetting respins; Collect gathers values with a x2–x20 multiplier and Mystery symbols can transform into Bonus or Jackpot symbols." },
  "3-oaks-gaming-golden-teapot": { mechanics: ["Респины", "Сбор символов", "Множители"], source: "https://3oaks.com/game/golden_teapot", verifiedAt, evidence: "Official Hold & Win is a respin game with a Collect symbol, Wild and total-win multipliers, plus an extra booster row." },
  "3-oaks-gaming-green-chilli-2": { mechanics: ["Линии", "Респины", "Сбор символов", "Множители"], source: "https://3oaks.com/game/green_chilli_2", verifiedAt, evidence: "Official Hold & Win grants three respins; Red Chillies leave additive multipliers and the Collect Symbol gathers all visible values." },
  "3-oaks-gaming-grab-the-gold": { mechanics: ["Линии", "Сбор символов", "Mystery Symbols", "Множители"], source: "https://3oaks.com/game/grab_the_gold", verifiedAt, evidence: "Official Collect feature gathers Gold Nugget values, Mystery symbols can reveal jackpots and progressive Free Spins increase the Collect multiplier up to x10." },
  "3-oaks-gaming-lava-coins": { mechanics: ["Линии", "Респины", "Сбор символов"], source: "https://3oaks.com/game/lava_coins", verifiedAt, evidence: "Official Hold & Win starts with three respins and a locked Collect Symbol repeatedly gathers Bonus Symbol values." },
  "3-oaks-gaming-china-festival": { mechanics: ["Линии", "Сбор символов", "Mystery Symbols", "Множители"], source: "https://3oaks.com/game/china_festival", verifiedAt, evidence: "Official Firecracker features include Collect and Double, while Mystery symbols can reveal jackpots, Bonus symbols or Firecracker features." },
  "3-oaks-gaming-grab-more-gold": { mechanics: ["Линии", "Сбор символов", "Mystery Symbols", "Множители"], source: "https://3oaks.com/game/grab_more_gold", verifiedAt, evidence: "Official Collect Symbol gathers Money values, Mystery symbols reveal jackpots and the Free Spins progress metre increases the Collect multiplier up to x10." },
  "3-oaks-gaming-dancing-joker": { mechanics: ["Линии", "Сбор символов", "Трансформация символов"], source: "https://3oaks.com/game/dancing_joker", verifiedAt, evidence: "Official Joker acts as the Collect Symbol and the Rewind modifier transforms random symbols into Jackpot Symbols." },
  "3-oaks-gaming-hit-more-gold": { mechanics: ["Линии", "Респины", "Сбор символов", "Mystery Symbols"], source: "https://3oaks.com/game/hit_more_gold", verifiedAt, evidence: "Official Hold & Win gives three resetting respins, Boost collects visible Bonus values and Mystery symbols can transform into jackpots." },
  "3-oaks-gaming-lava-coins-2": { mechanics: ["Линии", "Респины", "Сбор символов", "Множители"], source: "https://3oaks.com/game/lava_coins_2", verifiedAt, evidence: "Official Bonus Game starts with three respins, locked Collect Symbols gather values and Volcano eruptions add sticky multipliers while resetting the respin count." },
  "3-oaks-gaming-lucky-penny-power-scatter": { mechanics: ["Каскады", "Множители"], source: "https://3oaks.com/game/lucky_penny_powerscatter", verifiedAt, evidence: "Official page names Cascading Reels and Penny Coin multipliers from x2 to x1000, with a progressive Total Multiplier in Free Spins." },
  "3-oaks-gaming-lucky-penny": { mechanics: ["Каскады", "Множители"], source: "https://3oaks.com/game/lucky_penny", verifiedAt, evidence: "Official Scatter Pays title uses Cascading Reels and Penny multipliers up to x1000, with cumulative multipliers in Free Spins." },
  "3-oaks-gaming-lucky-apple-x1000": { mechanics: ["Каскады", "Множители"], source: "https://3oaks.com/game/lucky_apple_x1000", verifiedAt, evidence: "Official page explicitly names Cascading Reels and Apple multipliers from x2 to x1000, including a cumulative Total Multiplier in Free Spins." },
  "3-oaks-gaming-joker-glitz-x1000": { mechanics: ["Каскады", "Множители"], source: "https://3oaks.com/game/joker_glitz_x1000", verifiedAt, evidence: "Official page names Cascading Reels and multipliers up to x1000, with a progressive Total Multiplier during Free Spins." },
  "3-oaks-gaming-lord-of-thunder": { mechanics: ["Линии", "Сбор символов", "Респины"], source: "https://3oaks.com/game/lord_of_thunder", verifiedAt, evidence: "Official Collect Symbol gathers all visible Bonus values and the Hold & Win Bonus locks up to five Collect Symbols through a sequence of respins." },
  "3-oaks-gaming-little-farm": { mechanics: ["Линии", "Сбор символов", "Респины", "Walking Wilds"], source: "https://3oaks.com/game/little_farm", verifiedAt, evidence: "Official Boost gathers Bonus values, Hold & Win starts with three resetting respins and Free Spins explicitly feature a Walking Wild." },
  "3-oaks-gaming-grand": { mechanics: ["Линии", "Сбор символов", "Множители"], source: "https://3oaks.com/game/grand", verifiedAt, evidence: "Official G-R-A-N-D progression sweeps filled-reel symbols into the Total Win bar and the Star Boost applies a multiplier to visible symbols." },
  "3-oaks-gaming-lucky-penny-2": { mechanics: ["Каскады", "Множители"], source: "https://3oaks.com/game/lucky_penny_2", verifiedAt, evidence: "Official release describes cascades, Penny multipliers up to x1000 and a Mystery Multiplier revealed after the cascade ends." },
};

export function getCatalogResearch3OaksFill3(slug: string) {
  return records[slug];
}
