import type { CatalogVerifiedDetails } from "./catalog-verified-details";

type HacksawCloseoutDetails = Partial<
  Pick<CatalogVerifiedDetails, "field" | "rtp" | "maxWin" | "releaseDate">
> & {
  verifiedAt: string;
  fieldSource?: string;
  rtpSource?: string;
  maxWinSource?: string;
  releaseDateSource?: string;
};

const verifiedAt = "2026-09-24";
const catalogueSource = "https://betting.bet/casino/studios/hacksaw-gaming";
const slotCatalog = (slug: string) => `https://slotcatalog.com/en/slots/${slug}`;

const details: Record<string, HacksawCloseoutDetails> = {
  "hacksaw-gaming-2-wild-2-die": {
    rtp: "96,25%",
    releaseDate: "2024-01-04",
    rtpSource: slotCatalog("2-Wild-2-Die"),
    releaseDateSource: slotCatalog("2-Wild-2-Die"),
    verifiedAt,
  },
  "hacksaw-gaming-aiko-and-the-wind-spirit": {
    field: "5×4",
    rtp: "96,29%",
    maxWin: "10000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-bash-bros": {
    rtp: "96,26%",
    maxWin: "10000x",
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-booze-bash": {
    rtp: "96,31%",
    maxWin: "12500x",
    releaseDate: "2025-06-12",
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    releaseDateSource: slotCatalog("booze-bash"),
    verifiedAt,
  },
  "hacksaw-gaming-bullets-and-bounty": {
    rtp: "96,27%",
    releaseDate: "2025-08-11",
    rtpSource: catalogueSource,
    releaseDateSource: slotCatalog("bullets-and-bounty"),
    verifiedAt,
  },
  "hacksaw-gaming-chaos-crew-3": {
    field: "5×5",
    rtp: "96,18%",
    maxWin: "30000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-circle-of-life": {
    field: "5×4",
    rtp: "96,33%",
    maxWin: "15000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-danny-dollar": {
    rtp: "96,21%",
    releaseDate: "2025-04-09",
    rtpSource: catalogueSource,
    releaseDateSource: slotCatalog("danny-dollar"),
    verifiedAt,
  },
  "hacksaw-gaming-dark-spiral": {
    field: "6×4",
    rtp: "96,22%",
    maxWin: "10000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-deal-with-death": {
    field: "5×4",
    rtp: "96,25%",
    maxWin: "20000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-death-becomes-you": {
    field: "5×4",
    fieldSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-donny-and-danny": {
    field: "5×5",
    rtp: "96,29%",
    maxWin: "12500x",
    releaseDate: "2025-12-09",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    releaseDateSource: slotCatalog("donny-and-danny"),
    verifiedAt,
  },
  "hacksaw-gaming-dorks-of-the-deep": {
    field: "5×4",
    rtp: "96,20%",
    maxWin: "10000x",
    releaseDate: "2025-03-13",
    fieldSource: slotCatalog("dorks-of-the-deep"),
    rtpSource: slotCatalog("dorks-of-the-deep"),
    maxWinSource: slotCatalog("dorks-of-the-deep"),
    releaseDateSource: slotCatalog("dorks-of-the-deep"),
    verifiedAt,
  },
  "hacksaw-gaming-epic-bullets-and-bounty": {
    field: "5×5",
    rtp: "96,24%",
    maxWin: "20000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-fighter-pit": {
    rtp: "96,30%",
    releaseDate: "2025-04-17",
    rtpSource: catalogueSource,
    releaseDateSource: slotCatalog("fighter-pit"),
    verifiedAt,
  },
  "hacksaw-gaming-hot-ross": {
    field: "5×5",
    rtp: "96,32%",
    maxWin: "5000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-invictus": {
    field: "5×4",
    rtp: "96,24%",
    maxWin: "10000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-le-cowboy": {
    field: "6×5",
    rtp: "96,28%",
    maxWin: "25000x",
    releaseDate: "2025-10-26",
    fieldSource: slotCatalog("le-cowboy"),
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    releaseDateSource: slotCatalog("le-cowboy"),
    verifiedAt,
  },
  "hacksaw-gaming-le-fisherman": {
    field: "6×5",
    rtp: "96,33%",
    maxWin: "15000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-le-football-fan": {
    field: "6×5",
    fieldSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-le-hooligan": {
    field: "6×5",
    fieldSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-le-king": {
    field: "6×5",
    rtp: "96,14%",
    maxWin: "20000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-le-santa": {
    field: "6×5",
    rtp: "96,14%",
    maxWin: "20000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-le-zeus": {
    field: "6×5",
    rtp: "96,26%",
    maxWin: "20000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-marlin-masters": {
    field: "5×4",
    rtp: "96,24%",
    maxWin: "7500x",
    releaseDate: "2025-01-27",
    fieldSource: slotCatalog("marlin-masters"),
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    releaseDateSource: slotCatalog("marlin-masters"),
    verifiedAt,
  },
  "hacksaw-gaming-marlin-masters-atlantis": {
    field: "5×4",
    rtp: "94,26%",
    maxWin: "10000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-marlin-masters-the-big-haul": {
    rtp: "96,28%",
    releaseDate: "2025-08-04",
    rtpSource: catalogueSource,
    releaseDateSource: slotCatalog("marlin-masters-the-big-haul"),
    verifiedAt,
  },
  "hacksaw-gaming-miami-mayhem": {
    field: "5×4",
    rtp: "96,35%",
    maxWin: "15000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-munchy-milo": {
    field: "7×7",
    rtp: "96,30%",
    maxWin: "10000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-pray-for-six": {
    field: "6×5",
    rtp: "96,35%",
    maxWin: "20000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-pray-for-three": {
    field: "5×5",
    rtp: "96,33%",
    maxWin: "13333x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-reign-of-rome": {
    field: "5×5",
    rtp: "96,27%",
    maxWin: "15000x",
    releaseDate: "2025-04-14",
    fieldSource: slotCatalog("reign-of-rome"),
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    releaseDateSource: slotCatalog("reign-of-rome"),
    verifiedAt,
  },
  "hacksaw-gaming-smoking-dragon": {
    field: "5×4",
    rtp: "96,30%",
    maxWin: "10000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-spear-of-athena": {
    field: "6×5",
    rtp: "96,20%",
    maxWin: "15000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-spinman": {
    field: "5×4",
    rtp: "96,23%",
    maxWin: "10000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-steamrunners": {
    rtp: "96,32%",
    releaseDate: "2025-11",
    rtpSource: catalogueSource,
    releaseDateSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-strength-of-hercules": {
    field: "5×5",
    rtp: "96,31%",
    maxWin: "10000x",
    releaseDate: "2025-02-24",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    releaseDateSource: slotCatalog("strength-of-hercules"),
    verifiedAt,
  },
  "hacksaw-gaming-sun-princess": {
    field: "7×7",
    rtp: "96,29%",
    maxWin: "10000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-superstar-sevens": {
    field: "6×5",
    rtp: "96,37%",
    maxWin: "10000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-the-count": {
    field: "5×5",
    rtp: "96,36%",
    maxWin: "1200x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-the-luxe": {
    field: "5×4",
    rtp: "96,33%",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-the-wildwood-curse": {
    field: "6×5",
    rtp: "96,30%",
    maxWin: "10000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-tiger-legends": {
    rtp: "96,30%",
    rtpSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-toshi-ways-club": {
    field: "6×10",
    rtp: "96,09%",
    maxWin: "10000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-ultimate-slot-of-america": {
    field: "5×5",
    rtp: "96,35%",
    maxWin: "10000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
  "hacksaw-gaming-wishbringer": {
    rtp: "96,33%",
    releaseDate: "2025-04-03",
    rtpSource: catalogueSource,
    releaseDateSource: slotCatalog("wishbringer"),
    verifiedAt,
  },
  "hacksaw-gaming-zeus-ze-zecond": {
    field: "6×5",
    rtp: "96,26%",
    maxWin: "20000x",
    fieldSource: catalogueSource,
    rtpSource: catalogueSource,
    maxWinSource: catalogueSource,
    verifiedAt,
  },
};

export function getCatalogVerifiedDetailsHacksawCloseout20260924(slug: string) {
  return details[slug];
}
