import type { Slot } from "./data";

export const slotAdditions5: Slot[] = [
  {
    slug: "zeus-claws",
    name: "Zeus Claws",
    provider: "Clawbuster",
    year: 2025,
    mechanic: "Линии",
    mechanics: ["Линии", "Сбор символов"],
    tags: ["Hold & Win", "Сбор значений", "Джекпоты", "Collector", "Bonus Buy"],
    field: "5 барабанов",
    rtp: "95,00%",
    volatility: "Средняя",
    image: "/images/slots/zeus-claws.webp",
    description:
      "Классическая барабанная база соединена с Hold & Win: монеты удерживаются в бонусе, а механическая клешня может повышать их значения и превращать отдельные монеты в jackpot-символы.",
    feature:
      "Три монеты во втором ряду запускают Hold & Win с тремя попытками; новая монета обновляет счётчик, а Collector и Mystery-монеты меняют уже накопленное поле.",
    note:
      "Clawbuster публикует RTP 95% и среднюю волатильность. Структура бонуса важнее одного jackpot-значения: состояние сохраняется между респинами.",
    source: "https://clawbuster.com/games/zeus-claws.html",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/topic/373-%F0%9F%90%BE-claw-the-win-%E2%80%94-%E2%82%AC2000-by-clawbuster/",
      evidence: "Официальный турнир 1win Claw the Win прямо перечисляет Zeus Claws среди участвующих игр Clawbuster.",
    }],
  },
  {
    slug: "panda-claw-jackpot",
    name: "Panda Claw Jackpot",
    provider: "Clawbuster",
    year: 2025,
    mechanic: "Линии",
    mechanics: ["Линии", "Сбор символов"],
    tags: ["Claw", "Джекпоты", "Свободные вращения", "Сбор символов", "Bonus Buy"],
    field: "5 барабанов",
    rtp: "95,00%",
    volatility: "Средняя",
    image: "/images/slots/panda-claw-jackpot.webp",
    description:
      "Пять барабанов и отдельная Claw-система: несколько claw-символов сначала дают денежную выплату, а более крупный набор переводит игру в бонусный горизонтальный барабан.",
    feature:
      "В Bonus Claw Game клешня собирает cash prizes, дополнительные вращения и пять уровней jackpot; чем больше claw-символов в триггере, тем длиннее стартовый бонус.",
    note:
      "Официальная карточка Clawbuster указывает RTP 95% и среднюю волатильность. Jackpot Collection относится к бонусному состоянию, а не к обычным линиям.",
    source: "https://clawbuster.com/games/panda-claw-jackpot.html",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/topic/373-%F0%9F%90%BE-claw-the-win-%E2%80%94-%E2%82%AC2000-by-clawbuster/",
      evidence: "Официальный турнир 1win Claw the Win включает Panda Claw Jackpot в перечень участвующих игр.",
    }],
  },
  {
    slug: "wolf-hunt-claw-and-win",
    name: "Wolf Hunt: Claw and Win",
    provider: "Clawbuster",
    year: 2025,
    mechanic: "Линии",
    mechanics: ["Линии", "Сбор символов"],
    tags: ["Stacked Wild", "Hold & Win", "Claw", "Респины", "Множители", "Bonus Buy"],
    field: "5 барабанов",
    rtp: "95,00%",
    volatility: "Низкая",
    image: "/images/slots/wolf-hunt-claw-and-win.webp",
    description:
      "Stacked wild в базе сочетаются с Claw & Win-бонусом, где отдельные барабаны-клешни собирают множители, mystery-награды и новые scatter.",
    feature:
      "Бонус начинается с трёх респинов; новые scatter или собранный приз обновляют счётчик, а соседние клешни могут объединяться и усиливать общий множитель.",
    note:
      "Clawbuster указывает RTP 95%, низкую волатильность и максимум 6 992x. Низкая категория не означает ровную короткую сессию.",
    source: "https://clawbuster.com/games/wolf-hunt-claw-and-win.html",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/topic/373-%F0%9F%90%BE-claw-the-win-%E2%80%94-%E2%82%AC2000-by-clawbuster/",
      evidence: "Официальный турнир 1win Claw the Win прямо перечисляет Wolf Hunt: Claw and Win среди игр Clawbuster.",
    }],
  },
  {
    slug: "claw-bonanza-gold-rush",
    name: "Claw Bonanza: Gold Rush",
    provider: "Clawbuster",
    year: 2025,
    mechanic: "Каскады",
    mechanics: ["Каскады"],
    tags: ["Каскады", "Множители", "Свободные вращения", "Claw", "Bonus Buy", "Gamble"],
    field: "каскадное поле",
    rtp: "95,00%",
    volatility: "Высокая",
    image: "/images/slots/claw-bonanza-gold-rush.webp",
    description:
      "Каскадная структура с механическими клешнями: booster-символы открывают дополнительные claws, а выигрышные группы освобождают позиции для следующего падения.",
    feature:
      "Клешни могут собирать bomb-множители до 2 000x; три scatter открывают путь к free spins, а Gamble Feature меняет число стартовых вращений.",
    note:
      "Официальная карточка Clawbuster указывает RTP 95%, высокую волатильность и максимум 10 000x.",
    source: "https://clawbuster.com/games/claw-bonanza-gold-rush.html",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/topic/373-%F0%9F%90%BE-claw-the-win-%E2%80%94-%E2%82%AC2000-by-clawbuster/",
      evidence: "Официальный 1win Clawbuster-турнир включает Claw Bonanza: Gold Rush в список участвующих игр.",
    }],
  },
  {
    slug: "double-triple-burning-wilds",
    name: "Double Triple Burning Wilds",
    provider: "Clawbuster",
    year: 2025,
    mechanic: "Линии",
    mechanics: ["Линии"],
    tags: ["Расширяющийся wild", "Свободные вращения", "Claw", "Bonus Buy", "Scatter"],
    field: "5 барабанов",
    rtp: "95,00%",
    volatility: "Высокая",
    image: "/images/slots/double-triple-burning-wilds.webp",
    description:
      "Фруктовая линейная база с expanding wild: wild на центральных барабанах может растянуться на весь барабан, а Claw очищает соседние позиции внутри события.",
    feature:
      "Три, четыре или пять scatter дают соответственно 10, 20 или 50 free spins; отдельный Super Bonus гарантирует expanding wild во время бонуса.",
    note:
      "Clawbuster публикует RTP 95% и Medium-High volatility; Slotfolio укрупняет последнюю до высокой категории.",
    source: "https://clawbuster.com/games/double-triple-burning-wilds.html",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/topic/373-%F0%9F%90%BE-claw-the-win-%E2%80%94-%E2%82%AC2000-by-clawbuster/",
      evidence: "Официальный турнир 1win Claw the Win перечисляет Double Triple Burning Wilds среди участвующих игр.",
    }],
  },
  {
    slug: "clawbass-bonanza",
    name: "ClawBass Bonanza",
    provider: "Clawbuster",
    year: 2025,
    mechanic: "Каскады",
    mechanics: ["Каскады"],
    tags: ["Pay Anywhere", "Каскады", "Множители", "Свободные вращения", "Claw", "Шкала прогресса"],
    field: "6 × 5",
    rtp: "95,00%",
    volatility: "Высокая",
    image: "/images/slots/clawbass-bonanza.webp",
    description:
      "Рыболовная 6 × 5 сетка с выплатами по всему полю и каскадами. Progress-механика постепенно открывает fishing claws, которые усиливают выигрыши.",
    feature:
      "В free spins открытые fishing lines сохраняются и могут вытягивать множители; Bonus Buy позволяет начинать бонус с разным числом активных claws.",
    note:
      "Публичные каталоги расходятся по RTP отдельных сборок, поэтому Slotfolio хранит распространённую конфигурацию 95% и рекомендует проверять операторскую справку.",
    source: "https://clawbuster.com/games/clawbass-bonanza.html",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/topic/373-%F0%9F%90%BE-claw-the-win-%E2%80%94-%E2%82%AC2000-by-clawbuster/",
      evidence: "Официальный турнир 1win Claw the Win прямо включает ClawBass Bonanza в список участвующих игр.",
    }],
  },
  {
    slug: "clawbass-bonanza-free-rush",
    name: "ClawBass Bonanza: Free Rush",
    provider: "Clawbuster",
    year: 2025,
    mechanic: "Каскады",
    mechanics: ["Каскады"],
    tags: ["Каскады", "Свободные вращения", "Множители", "Claw", "Free Spins Purchase", "Шкала прогресса"],
    field: "6 × 5",
    rtp: "94,97%",
    volatility: "Высокая",
    image: "/images/slots/clawbass-bonanza-free-rush.webp",
    description:
      "Продолжение ClawBass на сетке 6 × 5: каскады сочетаются с bait-символами и прогрессом шести fishing lines, каждая из которых может вытащить множитель.",
    feature:
      "Treasure multipliers достигают 100x на одну линию, а Free Spins Purchase позволяет продолжить бонус с уже открытыми fishing lines без нового scatter-триггера.",
    note:
      "Clawbuster публикует RTP 94,97% и Very High volatility; в каталоге она отображается как высокая.",
    source: "https://clawbuster.com/games/clawbass-bonanza-free-rush.html",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/topic/527-%F0%9F%A6%80-clawbuster-%E2%82%AC10000-tournament/",
      evidence: "Официальный ноябрьский турнир 1win Clawbuster перечисляет ClawBass Bonanza: Free Rush среди участвующих игр.",
    }],
  },
  {
    slug: "3-claws-of-aztec-fire",
    name: "3 Claws of Aztec Fire",
    provider: "Clawbuster",
    year: 2025,
    mechanic: "Линии",
    mechanics: ["Линии", "Сбор символов"],
    tags: ["Hold & Win", "Респины", "Collector", "Множители", "Джекпоты", "Claw"],
    field: "5 × 3",
    rtp: "95,00%",
    volatility: "Высокая",
    image: "/images/slots/3-claws-of-aztec-fire.webp",
    description:
      "Поле 5 × 3 ведёт в Hold & Win с тремя типами клешней: одна удваивает значения, другая превращается в jackpot coin, третья собирает все видимые монеты.",
    feature:
      "Пять coin запускают три респина, новые бонусные символы возвращают счётчик к трём, а заполнение всех 15 позиций открывает Grand 10 000x.",
    note:
      "Официальная карточка Clawbuster указывает RTP 95% и высокую волатильность.",
    source: "https://clawbuster.com/games/3-claws-of-aztec-fire.html",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/topic/527-%F0%9F%A6%80-clawbuster-%E2%82%AC10000-tournament/",
      evidence: "Официальный турнир 1win Clawbuster перечисляет 3 Claws of Aztec Fire среди участвующих игр.",
    }],
  },
  {
    slug: "great-clawsby-deluxe",
    name: "The Great Clawsby Deluxe: Hold and Win",
    provider: "Clawbuster",
    year: 2025,
    mechanic: "Линии",
    mechanics: ["Линии", "Сбор символов"],
    tags: ["Hold & Win", "Stacked Wild", "Claw", "Mystery Box", "Респины", "Bonus Buy"],
    field: "5 × 4",
    rtp: "95,00%",
    volatility: "Низкая",
    image: "/images/slots/great-clawsby-deluxe.webp",
    description:
      "Пять барабанов и 50 линий сочетают stacked wild с Hold & Win. Claw-система собирает множители, увеличивает респины и может добавлять новые scatter.",
    feature:
      "Mystery Box меняет состояние бонуса через multiplier upgrade, дополнительные респины или scatter drop; прогресс развивается внутри одной Hold & Win-сессии.",
    note:
      "Публичная техническая карточка игры указывает RTP 95%, низкую волатильность и максимум 6 992x; активную операторскую конфигурацию стоит проверять отдельно.",
    source: "https://great-clawsby-deluxe-iframe-dev.clawbuster.com/",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/topic/373-%F0%9F%90%BE-claw-the-win-%E2%80%94-%E2%82%AC2000-by-clawbuster/",
      evidence: "Официальный турнир 1win Claw the Win включает The Great Clawsby Deluxe: Hold and Win в перечень игр.",
    }],
  },
  {
    slug: "fruit-train-express-hold-win",
    name: "Fruit Train Express: Hold & Win",
    provider: "Onlyplay",
    year: 2025,
    mechanic: "Линии",
    mechanics: ["Линии", "Сбор символов"],
    tags: ["Hold & Win", "Джекпоты", "Сбор значений", "Wild", "Bonus Buy"],
    field: "5 × 3",
    rtp: "97,00%",
    volatility: "Высокая",
    image: "/images/slots/fruit-train-express-hold-win.webp",
    description:
      "Фруктовая сетка 5 × 3 ведёт к Hold & Win с coin-символами и jackpot-уровнями. База остаётся простой, а основное состояние переносится в бонус.",
    feature:
      "Coin-символы закрепляются в Hold & Win, новые монеты поддерживают последовательность респинов, а buy/ante-опции меняют путь входа в функцию.",
    note:
      "Для опубликованной версии отраслевые каталоги указывают RTP 97%, высокую волатильность и максимум около 4 500x; операторскую конфигурацию стоит сверять в игре.",
    source: "https://onlyplay.com/games/fruit-train-express-hold-win",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/profile/235-daria/content/page/9/",
      evidence: "Официальный пост администратора 1win Express to Wins прямо перечисляет Fruit Train Express: Hold & Win среди игр Onlyplay.",
    }],
  },
  {
    slug: "hot-and-spicy-jackpot",
    name: "Hot And Spicy Jackpot",
    provider: "Onlyplay",
    year: 2021,
    mechanic: "Линии",
    mechanics: ["Линии"],
    tags: ["Джекпоты", "Мини-слот", "Множители", "Фрукты", "Wild"],
    field: "5 × 3 + 1 × 3",
    rtp: "96,06%",
    volatility: "Средняя",
    image: "/images/slots/hot-and-spicy-jackpot.webp",
    description:
      "Обычная фруктовая сетка 5 × 3 дополнена отдельным Chilly Mini Slot 1 × 3, который определяет множитель текущего вращения.",
    feature:
      "Над основной сеткой вращаются три pepper-reels, а отдельная Spicy Jackpots-система содержит пять локальных уровней от Minor до Grand.",
    note:
      "Onlyplay публикует RTP 96,06% и среднюю волатильность. Мини-слот является модификатором выплаты, а не второй независимой ставкой.",
    source: "https://onlyplay.com/games/hot-and-spicy-jackpot",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/profile/235-daria/content/page/9/",
      evidence: "Официальный пост 1win Express to Wins прямо включает Hot and Spicy Jackpot в список игр Onlyplay.",
    }],
  },
  {
    slug: "wild-west-girls",
    name: "Wild West Girls",
    provider: "Onlyplay",
    year: 2023,
    mechanic: "Линии",
    mechanics: ["Линии"],
    tags: ["Wild", "Scatter", "Множители", "Свободные вращения", "Western"],
    field: "5 × 3",
    rtp: "95,36%",
    volatility: "Средняя",
    image: "/images/slots/wild-west-girls.webp",
    description:
      "Вестерн на классической сетке 5 × 3 и двадцати линиях. Основной ритм не меняет геометрию поля, а специальные символы усиливают отдельные выигрыши и бонус.",
    feature:
      "Wild помогает собирать линейные комбинации, scatter открывают free spins, а случайные множители добавляют вариативность поверх фиксированной сетки.",
    note:
      "Публичная карточка релиза указывает RTP 95,36% и среднюю волатильность; перед реальной игрой стоит сверить конфигурацию оператора.",
    source: "https://onlyplay.com/games/wild-west-girls",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/profile/235-daria/content/page/9/",
      evidence: "Официальный пост администратора 1win Express to Wins перечисляет Wild West Girls среди участвующих игр Onlyplay.",
    }],
  },
  {
    slug: "caramelo-jackpot",
    name: "Caramelo Jackpot",
    provider: "Onlyplay",
    year: 2024,
    mechanic: "Линии",
    mechanics: ["Линии"],
    tags: ["Джекпоты", "Мини-слот", "Множители", "Sticky Wild", "Респины"],
    field: "5 × 3 + мини-слот",
    rtp: "96,14%",
    volatility: "Средняя",
    image: "/images/slots/caramelo-jackpot.webp",
    description:
      "Бразильская тематическая игра на 5 × 3 с отдельным mini-slot над основной сеткой. Специальная верхняя секция задаёт множители, не меняя базовый линейный способ выплаты.",
    feature:
      "Sticky Wild запускают цепочку дополнительных вращений, а отдельная jackpot-игра использует несколько уровней призов и собственный триггер.",
    note:
      "Onlyplay публикует RTP 96,14%, среднюю волатильность и максимум 10 000x для своей карточки игры.",
    source: "https://onlyplay.net/games/caramelo-jackpot",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/profile/235-daria/content/page/9/",
      evidence: "Официальный пост 1win Express to Wins прямо перечисляет Caramelo Jackpot среди игр Onlyplay.",
    }],
  },
  {
    slug: "coin-flynn",
    name: "Coin Flynn",
    provider: "Onlyplay",
    year: 2024,
    mechanic: "Линии",
    mechanics: ["Линии", "Сбор символов"],
    tags: ["Сбор монет", "Wild", "Множители", "Свободные вращения", "Джекпоты"],
    field: "две сетки 3 × 3",
    rtp: "97,00%",
    volatility: "Высокая",
    image: "/images/slots/coin-flynn.webp",
    description:
      "Две компактные сетки работают вместе: обычная часть формирует линейные выигрыши, а выпавшие coin переносятся на отдельное поле накопления.",
    feature:
      "Пять фиксированных линий сочетаются с Coin Reel, multiplier wild и free spins; накопление монет меняет состояние соседней сетки между событиями.",
    note:
      "Onlyplay публикует RTP 97% и high volatility; максимум для карточки игры указан как 5 831x.",
    source: "https://onlyplay.com/games/coin-flynn",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/profile/235-daria/content/page/9/",
      evidence: "Официальный пост 1win Express to Wins включает Coin Flynn в список участвующих игр Onlyplay.",
    }],
  },
  {
    slug: "coin-craze-jackpot",
    name: "Coin Craze Jackpot",
    provider: "Mancala Gaming",
    year: 2025,
    mechanic: "Линии",
    mechanics: ["Линии", "Сбор символов"],
    tags: ["Sticky", "Респины", "Джекпоты", "Claim Win", "Сбор значений"],
    field: "5 × 3",
    rtp: "95,00%",
    volatility: "Высокая",
    image: "/images/slots/coin-craze-jackpot.webp",
    description:
      "Линейная сетка 5 × 3 переходит в coin-respin состояние: специальные монеты удерживаются, а четыре jackpot-уровня и Claim Win меняют момент завершения бонуса.",
    feature:
      "Sticky coin остаются на поле во время респинов, новые монеты поддерживают бонус, а Claim Win позволяет зафиксировать накопленный результат внутри функции.",
    note:
      "В публичных каталогах для релиза встречается RTP 95%; конкретные максимум и конфигурацию следует сверять в справке оператора.",
    source: "https://mancalagaming.com/coin-craze-jackpot",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/profile/235-daria/content/page/9/",
      evidence: "Официальный пост 1win Xtreme Rush прямо перечисляет Coin Craze Jackpot среди участвующих игр Mancala Gaming.",
    }],
  },
  {
    slug: "caishen-gold-infinity-dragon",
    name: "Caishen Gold: Infinity Dragon",
    provider: "Mancala Gaming",
    year: 2025,
    mechanic: "Каскады",
    mechanics: ["Линии", "Каскады"],
    tags: ["Каскады", "Множители", "Свободные вращения", "Bonus Buy", "Wild"],
    field: "5 × 3",
    rtp: "95,00%",
    volatility: "Высокая",
    image: "/images/slots/caishen-gold-infinity-dragon.webp",
    description:
      "Сетка 5 × 3 сохраняет двадцать линий, но после выигрыша запускает каскады. По мере последовательности множители усиливают следующую выплату.",
    feature:
      "Cascades продолжают одно вращение, free spins повышают ценность длинной цепочки, а Bonus Buy даёт альтернативный вход в бонус.",
    note:
      "Mancala описывает игру как высоковолатильный каскадный слот; публичные карточки релиза указывают RTP 95%.",
    source: "https://mancalagaming.com/caishen-gold-infinity-dragon",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/profile/235-daria/content/page/9/",
      evidence: "Официальный пост 1win Xtreme Rush включает Caishen Gold: Infinity Dragon в список игр Mancala Gaming.",
    }],
  },
  {
    slug: "money-booster",
    name: "Money Booster",
    provider: "Mancala Gaming",
    year: 2025,
    mechanic: "Кластеры",
    mechanics: ["Кластеры"],
    tags: ["Pay Anywhere", "Множители", "Coin Booster", "Свободные вращения", "Bonus Buy"],
    field: "4 × 4",
    rtp: "95,00%",
    volatility: "Высокая",
    image: "/images/slots/money-booster.webp",
    description:
      "Компактное поле 4 × 4 без привычной сетки линий: выплаты читаются по совпадениям на всём поле, а специальные Booster-символы меняют итоговые значения.",
    feature:
      "Coin Booster усиливает отдельные денежные значения, а free spins добавляют более выраженную работу множителей и специального набора символов.",
    note:
      "Для публичной версии указывается RTP 95%; Very High variance в каталоге укрупнена до высокой.",
    source: "https://mancalagaming.com/money-booster",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/profile/235-daria/content/page/9/",
      evidence: "Официальный пост 1win Xtreme Rush прямо перечисляет Money Booster среди участвующих игр Mancala Gaming.",
    }],
  },
  {
    slug: "midas-hand-of-fortune",
    name: "Midas: Hand of Fortune",
    provider: "Mancala Gaming",
    year: 2025,
    mechanic: "Линии",
    mechanics: ["Линии"],
    tags: ["Wild", "Множители", "Свободные вращения", "40 линий", "Bonus Buy"],
    field: "5 × 3",
    rtp: "95,00%",
    volatility: "Высокая",
    image: "/images/slots/midas-hand-of-fortune.webp",
    description:
      "Сорок линий на поле 5 × 3 и тема золотого прикосновения: обычная линейная база постепенно усиливается wild-множителями и free spins.",
    feature:
      "Multiplier wild увеличивают линейные выплаты, а бонус сохраняет акцент на этих символах вместо перехода на другой способ подсчёта выигрышей.",
    note:
      "Публичные технические каталоги релиза указывают RTP 95% и высокую волатильность.",
    source: "https://mancalagaming.com/midas-hand-of-fortune",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/profile/235-daria/content/page/9/",
      evidence: "Официальный пост 1win Xtreme Rush включает Midas: Hand of Fortune в список участвующих игр Mancala Gaming.",
    }],
  },
  {
    slug: "mustang-rush",
    name: "Mustang Rush",
    provider: "Mancala Gaming",
    year: 2025,
    mechanic: "Линии",
    mechanics: ["Линии", "Сбор символов"],
    tags: ["Респины", "Множители", "Wild", "Джекпоты", "Hold & Earn"],
    field: "5 × 3",
    rtp: "95,00%",
    volatility: "Высокая",
    image: "/images/slots/mustang-rush.webp",
    description:
      "Двадцать линий на поле 5 × 3 сочетаются с respin-сценарием, wild-множителями и фиксированными jackpot-уровнями.",
    feature:
      "Специальные символы удерживают состояние бонуса между респинами, а множители и jackpot-значения определяют итог уже после обычного линейного триггера.",
    note:
      "Для публичной версии отраслевые карточки указывают RTP 95% и высокую волатильность.",
    source: "https://mancalagaming.com/mustang-rush",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/profile/235-daria/content/page/9/",
      evidence: "Официальный пост 1win Xtreme Rush прямо перечисляет Mustang Rush среди участвующих игр Mancala Gaming.",
    }],
  },
  {
    slug: "power-of-zeus-mancala",
    name: "Power of Zeus",
    provider: "Mancala Gaming",
    year: 2024,
    mechanic: "Линии",
    mechanics: ["Линии", "Сбор символов"],
    tags: ["Hold & Earn", "Stacked Wild", "Множители", "Джекпоты", "Респины"],
    field: "5 × 3",
    rtp: "95,00%",
    volatility: "Высокая",
    image: "/images/slots/power-of-zeus-mancala.webp",
    description:
      "Двадцать линий и stacked multiplier wild служат входом в Hold & Earn, где coin-символы и jackpot-уровни сохраняются в отдельной бонусной сетке.",
    feature:
      "Hold & Earn удерживает ценные позиции между респинами, а stacked wild с множителями усиливают обычные линейные комбинации в базе.",
    note:
      "Для опубликованной версии указывается RTP 95%; игру не следует путать с Hacksaw Power of Ten или серией Gates of Olympus.",
    source: "https://mancalagaming.com/power-of-zeus",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/profile/235-daria/content/page/9/",
      evidence: "Официальный пост 1win Xtreme Rush прямо перечисляет Power of Zeus среди участвующих игр Mancala Gaming.",
    }],
  },
  {
    slug: "rip-city",
    name: "RIP City",
    provider: "Hacksaw Gaming",
    year: 2023,
    mechanic: "Линии",
    mechanics: ["Линии"],
    tags: ["Расширяющийся wild", "Множители", "Свободные вращения", "Bonus Buy", "FeatureSpins"],
    field: "5 × 5",
    rtp: "96,22%",
    volatility: "Средняя",
    image: "/images/slots/rip-city.webp",
    description:
      "Пять барабанов, пять рядов и 19 линий. Wild Cat может расширяться на весь барабан и поглощать обычные wild, превращая их в множители.",
    feature:
      "Ro$$ Bonus повышает частоту Wild Cat, а Maxx Bonus постепенно активирует барабаны для новых кошачьих wild на оставшиеся свободные вращения.",
    note:
      "Hacksaw публикует volatility 3/5, максимум 12 500x и несколько RTP-конфигураций; в каталоге хранится верхняя 96,22%.",
    source: "https://www.hacksawgaming.com/games/rip-city",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/topic/468-%E2%80%8B-%F0%9F%92%A5-hacksaw-madness-are-these-bonuses-worth-the-risk-%E2%80%8B/",
      evidence: "Официальный материал 1win Hacksaw Madness прямо перечисляет RIP City и его expanding wild среди доступных Hacksaw-игр.",
    }],
  },
  {
    slug: "hand-of-anubis",
    name: "Hand of Anubis",
    provider: "Hacksaw Gaming",
    year: 2022,
    mechanic: "Кластеры",
    mechanics: ["Кластеры", "Каскады"],
    tags: ["Кластеры", "Каскады", "Soul Orbs", "Множители", "Bonus Buy", "Свободные вращения"],
    field: "5 × 6",
    rtp: "96,24%",
    volatility: "Высокая",
    image: "/images/slots/hand-of-anubis.webp",
    description:
      "Кластерная сетка 5 × 6 с каскадами: выигрышные группы исчезают, а Soul Orbs способны превратить дальнейшее состояние поля в серию множителей.",
    feature:
      "Soul multipliers накапливают силу в цепочке каскадов; bonus-функции усиливают эту же логику вместо перехода на классические линии.",
    note:
      "Для верхней публичной конфигурации обычно указываются RTP 96,24% и максимум 10 000x; в 1win отдельно отмечены soul multipliers.",
    source: "https://www.hacksawgaming.com/games/hand-of-anubis",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/topic/468-%E2%80%8B-%F0%9F%92%A5-hacksaw-madness-are-these-bonuses-worth-the-risk-%E2%80%8B/",
      evidence: "Официальный материал 1win Hacksaw Madness прямо перечисляет Hand of Anubis и отдельно упоминает soul multipliers.",
    }],
  },
  {
    slug: "life-and-death",
    name: "Life and Death",
    provider: "Hacksaw Gaming",
    year: 2025,
    mechanic: "Линии",
    mechanics: ["Линии"],
    tags: ["Wild", "Множители", "Расширяющийся wild", "Свободные вращения", "Death Reels", "Bonus Buy"],
    field: "6 × 5",
    rtp: "96,36%",
    volatility: "Высокая",
    image: "/images/slots/life-and-death.webp",
    description:
      "Шесть барабанов, пять рядов и 19 линий построены вокруг четырёх Horsemen Wild Multipliers со значениями от 2x до 200x.",
    feature:
      "Devastation и Reckoning развивают expanding wild reels; в Reckoning активированные Death Reels сохраняют способность расширять связанный множитель на последующих free spins.",
    note:
      "У игры есть несколько RTP-конфигураций. Slotfolio использует верхнее публичное значение 96,36%, поэтому активный вариант нужно проверять у оператора.",
    source: "https://www.hacksawgaming.com/games/life-and-death",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/23-slot-games/page/2/",
      evidence: "Официальный раздел Slot Games 1win публикует отдельный материал Life and Death — New Slot среди актуальных игр казино.",
    }],
  },
  {
    slug: "rad-maxx",
    name: "Rad Maxx",
    provider: "Hacksaw Gaming",
    year: 2025,
    mechanic: "Линии",
    mechanics: ["Линии"],
    tags: ["Wild", "Множители", "Несколько направлений", "Sticky Wild", "Свободные вращения"],
    field: "5 × 5",
    rtp: "96,32%",
    volatility: "Высокая",
    image: "/images/slots/rad-maxx.webp",
    description:
      "Сетка 5 × 5 использует направление линий как изменяемое состояние: стрелки вокруг поля определяют, в каких направлениях считаются текущие выигрыши.",
    feature:
      "Crazy Cat wild несут множители 2x–20x, Wild Plus открывает дополнительные pay-direction arrows, а три бонусных режима сохраняют sticky wild.",
    note:
      "Официальный 1win-материал подтверждает 360 направлений и максимум 12 500x; верхний RTP 96,32% взят из текущих технических каталогов и требует проверки конкретной сборки.",
    source: "https://www.hacksawgaming.com/games/rad-maxx",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/topic/161-%E2%80%8B%F0%9F%90%AD%E2%80%8B-meet-rad-maxx/",
      evidence: "Официальный пост администратора 1win Meet Rad Maxx подтверждает игру, 360 win directions, sticky wilds и три бонусных раунда.",
    }],
  },
  {
    slug: "mahjong-wins-super-scatter",
    name: "Mahjong Wins Super Scatter",
    provider: "Pragmatic Play",
    year: 2025,
    mechanic: "Способы",
    mechanics: ["Способы", "Каскады"],
    tags: ["Super Scatter", "Каскады", "Множители", "Свободные вращения", "Gold Wild", "Ways"],
    field: "5 × 5 · до 2 000 способов",
    rtp: "96,50%",
    volatility: "Высокая",
    image: "/images/slots/mahjong-wins-super-scatter.webp",
    description:
      "До 2 000 способов на 5 × 5 поле сочетаются с tumbles: последовательные выигрыши поднимают multiplier trail до 5x в базе.",
    feature:
      "Gold-символы на центральных барабанах оставляют wild после выигрышного tumble; free spins увеличивают multiplier trail до 10x, а Super Scatter способен дать до 100 000x.",
    note:
      "Pragmatic Play подтверждает релиз 29 мая 2025 года и максимум 100 000x. RTP зависит от операторской конфигурации; в каталоге указана верхняя распространённая версия 96,5%.",
    source: "https://www.pragmaticplay.com/en/games/mahjong-wins-super-scatter/",
    availability: [{
      operator: "1win",
      verifiedAt: "2026-09-08",
      source: "https://forum.1win.com/topic/353-%F0%9F%8F%86-champions-clash-%E2%80%94-%E2%82%AC500000-by-pragmatic-play/",
      evidence: "Официальный турнир 1win Champions Clash прямо перечисляет Mahjong Wins Super Scatter среди участвующих игр Pragmatic Play.",
    }],
  },
];
